-- Seed protocoles Reiki + Deep Hypnose (vagues 2 + 3)
-- IDs : 820-823 (Reiki) + 830-833 (Deep Hypnose / Dave Elman)
-- Sources : GS Formation REIKI USUI 4 degrés + Module Deep Hypnose Dave Elman 4 tomes

INSERT INTO public.protocols (id, name, category, practice, description, duration, level, tags, color, sessions, objectives, source, motifs)
VALUES
  -- ===== REIKI USUI (4 degrés GS Formation) =====
  (820,
   'Reiki Usui — 1er degré (Shoden)',
   'Reiki — Initiation',
   'Reiki',
   'Premier degré du Reiki Usui. Initiation par un Maître Reiki au canal énergétique universel. Apprentissage du protocole d''auto-traitement complet (positions des mains) et du soin physique sur autrui. Enseignement des 5 préceptes (Gokai) et de la respiration énergétique.',
   '2 jours d''initiation + pratique quotidienne',
   'Débutant',
   ARRAY['reiki', 'shoden', 'initiation', 'auto-traitement', 'énergétique', 'usui', 'gokai'],
   '#7C5CBF',
   1,
   ARRAY['Recevoir l''initiation au canal Reiki Usui', 'Maîtriser les 12 positions des mains pour l''auto-traitement', 'Pratiquer le soin Reiki sur autrui (corps physique)', 'Intégrer les 5 préceptes au quotidien', 'Pratiquer 21 jours de purification post-initiation'],
   'GS Formation — Reiki Usui',
   ARRAY['Anxiété & stress', 'Burn-out & fatigue', 'Quête de sens & spiritualité']
  ),
  (821,
   'Reiki Usui — 2nd degré (Okuden)',
   'Reiki — Symboles',
   'Reiki',
   'Deuxième degré : transmission des 3 symboles sacrés (Cho-Ku-Rei pour amplifier, Sei-He-Ki pour l''émotionnel/mental, Hon-Sha-Ze-Sho-Nen pour la distance). Permet le soin à distance dans le temps et l''espace, le travail sur les blessures émotionnelles et la programmation d''intentions.',
   '2 jours + pratique régulière',
   'Intermédiaire',
   ARRAY['reiki', 'okuden', 'symboles', 'distance', 'émotionnel', 'cho-ku-rei', 'sei-he-ki', 'hon-sha-ze-sho-nen'],
   '#C8A030',
   1,
   ARRAY['Recevoir et activer les 3 symboles sacrés', 'Pratiquer le soin Reiki à distance', 'Travailler sur les blessures émotionnelles', 'Programmer des intentions futures', 'Approfondir la pratique du 1er degré'],
   'GS Formation — Reiki Usui',
   ARRAY['Anxiété & stress', 'Trauma & deuil', 'Quête de sens & spiritualité']
  ),
  (822,
   'Reiki Usui — 3ème degré (Shinpiden)',
   'Reiki — Maître Praticien',
   'Reiki',
   'Troisième degré (Maître Praticien) : transmission du symbole Maître (Dai-Ko-Myo). Approfondissement spirituel, augmentation significative de la puissance énergétique, accès à l''essence du Reiki. Préparation possible à devenir Maître Enseignant (4ème degré).',
   '2-3 jours + pratique avancée',
   'Avancé',
   ARRAY['reiki', 'shinpiden', 'maître praticien', 'dai-ko-myo', 'spirituel', 'avancé'],
   '#2E8A7B',
   1,
   ARRAY['Recevoir et activer le symbole Maître Dai-Ko-Myo', 'Approfondir la pratique spirituelle du Reiki', 'Augmenter significativement la puissance énergétique des soins', 'Accéder à l''essence du Reiki', 'Préparer éventuellement le 4ème degré (enseignement)'],
   'GS Formation — Reiki Usui',
   ARRAY['Quête de sens & spiritualité', 'Anxiété & stress']
  ),
  (823,
   'Reiki Usui — 4ème degré (Maître Enseignant)',
   'Reiki — Maître Enseignant',
   'Reiki',
   'Quatrième degré : Maître Enseignant. Apprentissage de la transmission des initiations aux 4 degrés. Préparation du Maître à fonder sa propre lignée d''enseignement. Engagement éthique et spirituel profond. Plusieurs années de pratique entre 3ème et 4ème degré recommandées.',
   '3-5 jours d''enseignement intensif + suivi',
   'Avancé',
   ARRAY['reiki', 'maître enseignant', 'transmission', 'initiations', 'lignée', 'éthique'],
   '#B85450',
   1,
   ARRAY['Apprendre à transmettre les initiations aux 4 degrés', 'Fonder sa propre lignée d''enseignement Reiki', 'Engager une pratique éthique et spirituelle approfondie', 'Devenir guide pour ses propres élèves', 'Servir la transmission de la lignée Usui'],
   'GS Formation — Reiki Usui',
   ARRAY['Quête de sens & spiritualité']
  ),

  -- ===== DEEP HYPNOSE / DAVE ELMAN =====
  (830,
   'Induction Dave Elman — Rapide & profonde',
   'Deep Hypnose — Induction',
   'Hypnose Ericksonienne',
   'Induction emblématique de Dave Elman (1900-1967). Technique en 7 étapes pour atteindre une transe profonde (somnambulique) en 3-5 minutes. Repose sur la fixation visuelle, la fermeture des yeux par décret, le test de relâchement musculaire et la dissociation par les chiffres.',
   '5-10 min (induction seule)',
   'Intermédiaire',
   ARRAY['Dave Elman', 'induction rapide', 'transe profonde', 'somnambulique', 'deep hypnose'],
   '#1B2D47',
   1,
   ARRAY['Atteindre la transe profonde en 3-5 minutes', 'Maîtriser les 7 étapes de l''induction Elman', 'Vérifier la profondeur par test musculaire', 'Approfondir par la dissociation des chiffres', 'Préparer le terrain pour techniques avancées (régression, suggestions directes)'],
   'GS Formation / Dave Elman — Deep Hypnose Module 2 Tome 1',
   ARRAY['Anxiété & stress', 'Phobies & peurs', 'Performance & examens']
  ),
  (831,
   'Régression Elman — Vers l''événement initiateur',
   'Deep Hypnose — Régression',
   'Hypnose Ericksonienne',
   'Technique de régression en transe profonde de Dave Elman. Le client remonte chronologiquement sa vie jusqu''à l''événement initial du symptôme (Initial Sensitizing Event - ISE). Recadrage in situ avec ressources adultes. Particulièrement efficace pour phobies, blocages et symptômes psychosomatiques.',
   '60-90 min',
   'Avancé',
   ARRAY['Dave Elman', 'régression', 'ISE', 'événement initiateur', 'recadrage', 'transe profonde'],
   '#7C5CBF',
   1,
   ARRAY['Identifier l''événement initiateur du symptôme', 'Revivre la scène en transe profonde avec ressources adultes', 'Recadrer la signification de l''événement', 'Libérer le symptôme à sa racine', 'Pont sur le futur avec nouveau scénario'],
   'GS Formation / Dave Elman — Deep Hypnose Module 2 Tome 2',
   ARRAY['Phobies & peurs', 'Trauma & deuil', 'Anxiété & stress', 'Douleurs & psychosomatique']
  ),
  (832,
   'Anesthésie hypnotique — Méthode Elman',
   'Deep Hypnose — Anesthésie',
   'Hypnose Ericksonienne',
   'Protocole d''anesthésie hypnotique en transe profonde pour douleurs aiguës ou chroniques, soins dentaires, accouchement. Repose sur la dissociation et la suggestion directe en somnambulisme. Méthode utilisée par Dave Elman avec dentistes et chirurgiens dans les années 1950-60.',
   '20-40 min',
   'Avancé',
   ARRAY['Dave Elman', 'anesthésie', 'douleur', 'analgésie', 'dentaire', 'accouchement', 'somnambulique'],
   '#B85450',
   1,
   ARRAY['Atteindre l''anesthésie locale ou générale par hypnose', 'Soutenir un soin dentaire ou médical sans antalgique', 'Soulager une douleur chronique ponctuelle', 'Préparer un accouchement avec hypno-naissance', 'Permettre une chirurgie chez les patients allergiques aux anesthésiques'],
   'GS Formation / Dave Elman — Deep Hypnose Module 2 Tome 3',
   ARRAY['Douleurs & psychosomatique']
  ),
  (833,
   'Test des doigts collés — Vérification de la transe',
   'Deep Hypnose — Convicteur',
   'Hypnose Ericksonienne',
   'Convicteur classique de Dave Elman pour vérifier que le client est bien en transe profonde (somnambulique). Le client ne peut plus séparer ses doigts collés malgré ses efforts. Permet d''ancrer la conviction du client en sa propre transe et d''ouvrir la porte aux techniques avancées (régression, suggestions directes, anesthésie).',
   '5 min (intégré à l''induction)',
   'Intermédiaire',
   ARRAY['Dave Elman', 'convicteur', 'test', 'doigts collés', 'somnambulisme', 'vérification'],
   '#5B8FB9',
   1,
   ARRAY['Vérifier objectivement la profondeur de transe atteinte', 'Renforcer la conviction du client en l''hypnose', 'Préparer l''utilisation de techniques avancées', 'Lever les doutes du client résistant'],
   'GS Formation / Dave Elman — Deep Hypnose Module 2 Tome 4',
   ARRAY['Anxiété & stress']
  )
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  practice = EXCLUDED.practice,
  description = EXCLUDED.description,
  duration = EXCLUDED.duration,
  level = EXCLUDED.level,
  tags = EXCLUDED.tags,
  color = EXCLUDED.color,
  sessions = EXCLUDED.sessions,
  objectives = EXCLUDED.objectives,
  source = EXCLUDED.source,
  motifs = EXCLUDED.motifs;
