-- Seed protocoles Technicien PNL & Hypnose (couverture exhaustive)
-- IDs : 873-894 (22 protocoles)
-- Source : GS Formation — PNL & Hypnose Tech V3 (Technicien HYPNOSE & PNL)

INSERT INTO public.protocols (id, name, category, practice, description, duration, level, tags, color, sessions, objectives, source, motifs)
VALUES
  (873,
   'Cadre « comme si » — Projection ressource',
   'Technicien — Cadre',
   'PNL',
   'Outil PNL fondamental : faire agir le client « comme si » il avait déjà la ressource ou l''objectif. Permet de contourner les résistances conscientes et d''accéder immédiatement aux compétences latentes. Utilisé en entrée de séance ou en cours d''intervention.',
   '15-30 min (intégrable)',
   'Débutant',
   ARRAY['PNL', 'cadre', 'comme si', 'ressource', 'projection'],
   '#7C5CBF',
   1,
   ARRAY['Contourner les résistances conscientes', 'Accéder à des ressources latentes', 'Tester un objectif avant engagement', 'Préparer une induction ou un travail PNL'],
   'GS Formation — Technicien PNL & Hypnose',
   ARRAY['Estime & confiance en soi']
  ),
  (874,
   'Cercle d''excellence — Ancrage de ressources',
   'Technicien — Ancrage',
   'PNL',
   'Création d''un cercle imaginaire au sol dans lequel le client empile plusieurs états ressources (confiance, calme, joie). En entrant dans le cercle, le client active immédiatement l''état composé. Outil d''auto-régulation puissant et autonome.',
   '30-45 min',
   'Débutant',
   ARRAY['PNL', 'cercle excellence', 'ancrage', 'ressources', 'empilement'],
   '#C8A030',
   1,
   ARRAY['Empiler plusieurs ressources sur un même ancrage spatial', 'Apprendre l''auto-activation d''un état ressource', 'Préparer une situation stressante future', 'Outil quotidien d''auto-régulation'],
   'GS Formation — Technicien PNL & Hypnose',
   ARRAY['Anxiété & stress', 'Estime & confiance en soi', 'Performance & examens']
  ),
  (875,
   'Positions perceptuelles — Tourniquet',
   'Technicien — Systémique',
   'PNL',
   'Travail sur 3 positions perceptuelles : 1ère (soi), 2ème (l''autre), 3ème (observateur extérieur). Le tourniquet permet de visiter les 3 positions successivement pour résoudre un conflit ou comprendre une situation relationnelle.',
   '45-60 min',
   'Intermédiaire',
   ARRAY['PNL', 'positions perceptuelles', 'tourniquet', 'systémique', 'empathie'],
   '#2E8A7B',
   1,
   ARRAY['Sortir de la fixation sur une seule perspective', 'Développer l''empathie cognitive', 'Résoudre un conflit interpersonnel', 'Préparer une conversation difficile'],
   'GS Formation — Technicien PNL & Hypnose',
   ARRAY['Conflits & communication']
  ),
  (876,
   'Sous-modalités sensorielles — Modulation',
   'Technicien — Représentations',
   'PNL',
   'Modulation des qualités fines (sous-modalités) des représentations mentales : luminosité, taille, distance, son, température. En modifiant les sous-modalités d''une image limitante, on transforme le ressenti associé.',
   '30-45 min',
   'Intermédiaire',
   ARRAY['PNL', 'sous-modalités', 'VAK', 'représentations', 'modulation'],
   '#5B8FB9',
   1,
   ARRAY['Identifier les sous-modalités critiques d''un ressenti', 'Moduler une image limitante pour transformer l''émotion', 'Renforcer une représentation positive', 'Préparer le Swish ou autre travail de représentations'],
   'GS Formation — Technicien PNL & Hypnose',
   ARRAY['Anxiété & stress', 'Phobies & peurs']
  ),
  (877,
   'Association / Dissociation — Gestion émotionnelle',
   'Technicien — Émotionnel',
   'PNL',
   'Apprentissage volontaire de l''association (immersion totale dans une expérience) et de la dissociation (recul observateur). Permet de moduler l''intensité émotionnelle : amplifier le positif, désamorcer le négatif.',
   '30-45 min',
   'Intermédiaire',
   ARRAY['PNL', 'association', 'dissociation', 'émotion', 'distance'],
   '#B85450',
   1,
   ARRAY['Apprendre à dissocier d''une émotion envahissante', 'Apprendre à associer pleinement à une ressource', 'Outil de gestion émotionnelle quotidienne', 'Préparer le travail trauma léger'],
   'GS Formation — Technicien PNL & Hypnose',
   ARRAY['Anxiété & stress', 'Trauma & deuil']
  ),
  (878,
   'Générateur de nouveau comportement',
   'Technicien — Comportement',
   'PNL',
   'Protocole structuré pour créer un nouveau comportement : visualisation dissociée du comportement souhaité, ajustement, association et test. Particulièrement utile pour acquérir une compétence comportementale précise.',
   '45 min',
   'Intermédiaire',
   ARRAY['PNL', 'nouveau comportement', 'visualisation', 'apprentissage'],
   '#7C5CBF',
   1,
   ARRAY['Créer mentalement un nouveau comportement précis', 'Tester sa cohérence et son écologie', 'Ancrer le comportement par projection répétée', 'Faciliter son émergence en situation réelle'],
   'GS Formation — Technicien PNL & Hypnose',
   ARRAY['Estime & confiance en soi', 'Performance & examens']
  ),
  (879,
   'Le clonage — Modélisation rapide',
   'Technicien — Modélisation',
   'PNL',
   'Forme rapide de modélisation : le client se « clone » sur un modèle (réel ou imaginaire) qui possède la ressource ou la compétence visée. Adoption immédiate de la posture, de la voix, du regard, des stratégies internes.',
   '30-45 min',
   'Intermédiaire',
   ARRAY['PNL', 'clonage', 'modélisation', 'ressource', 'rapide'],
   '#C8A030',
   1,
   ARRAY['Adopter rapidement une ressource extérieure', 'Modéliser un mentor ou figure inspirante', 'Préparer une performance avec posture optimale', 'Faciliter le travail identitaire'],
   'GS Formation — Technicien PNL & Hypnose',
   ARRAY['Estime & confiance en soi', 'Performance & examens']
  ),
  (880,
   'Index de computation — Cartographie cognitive',
   'Technicien — Cognition',
   'PNL',
   'Cartographie de la séquence interne (V-A-K-O-G) qui produit un état ou un comportement. L''index de computation révèle « comment » le client construit son expérience subjective. Étape diagnostic préalable au travail PNL.',
   '30-45 min',
   'Avancé',
   ARRAY['PNL', 'index computation', 'VAKOG', 'cognition', 'diagnostic'],
   '#5B8FB9',
   1,
   ARRAY['Cartographier la séquence VAKOG d''un état', 'Identifier le canal sensoriel dominant', 'Préparer un travail de modélisation ou de transformation', 'Éclairer le client sur sa propre construction'],
   'GS Formation — Technicien PNL & Hypnose',
   ARRAY['Anxiété & stress', 'Estime & confiance en soi']
  ),
  (881,
   'Les états internes — Identification & calibration',
   'Technicien — États',
   'PNL',
   'Travail d''identification précise des états internes (émotion, sensation, pensée, posture) et de leur calibration externe. Outil de base pour toute intervention PNL : observer, nommer, moduler.',
   '30 min (intégré)',
   'Débutant',
   ARRAY['PNL', 'états internes', 'calibration', 'émotion', 'observation'],
   '#2E8A7B',
   1,
   ARRAY['Identifier ses états internes avec précision', 'Calibrer les états d''autrui par observation', 'Développer la conscience émotionnelle', 'Préparer toute intervention PNL ciblée'],
   'GS Formation — Technicien PNL & Hypnose',
   ARRAY['Estime & confiance en soi', 'Anxiété & stress']
  ),
  (882,
   'Boussole du langage — Direction sensorielle',
   'Technicien — Linguistique',
   'PNL',
   'Outil de cartographie linguistique : repérage des prédicats sensoriels (visuels, auditifs, kinesthésiques, olfactifs/gustatifs) dans le discours du client pour identifier son canal dominant et synchroniser sa propre communication.',
   '15-30 min (intégré)',
   'Débutant',
   ARRAY['PNL', 'boussole langage', 'prédicats', 'VAKOG', 'rapport'],
   '#C8A030',
   1,
   ARRAY['Identifier le canal sensoriel dominant du client', 'Synchroniser son langage sur celui du client', 'Renforcer le rapport thérapeutique', 'Améliorer la qualité de l''écoute'],
   'GS Formation — Technicien PNL & Hypnose',
   ARRAY['Conflits & communication']
  ),
  (883,
   'Erreurs cognitives d''étiquetage et de logique',
   'Technicien — Cognition',
   'PNL',
   'Identification et recadrage des erreurs cognitives classiques : étiquetage global, généralisation abusive, pensée binaire, filtrage négatif. Inspirée de la TCC croisée avec la PNL.',
   '45 min',
   'Intermédiaire',
   ARRAY['PNL', 'erreurs cognitives', 'étiquetage', 'TCC', 'recadrage'],
   '#B85450',
   1,
   ARRAY['Identifier les erreurs cognitives récurrentes du client', 'Recadrer chaque distorsion ciblée', 'Apprendre l''auto-recadrage au quotidien', 'Compléter un travail sur les croyances'],
   'GS Formation — Technicien PNL & Hypnose',
   ARRAY['Estime & confiance en soi', 'Anxiété & stress']
  ),
  (884,
   'Langage transformationnel — Reformulation positive',
   'Technicien — Linguistique',
   'PNL',
   'Apprentissage de la reformulation transformationnelle : passer du négatif au positif, du subi au choisi, du global au précis. Outil quotidien du praticien et du client.',
   '30 min (intégré)',
   'Débutant',
   ARRAY['PNL', 'langage transformationnel', 'reformulation', 'positif'],
   '#7C5CBF',
   1,
   ARRAY['Reformuler systématiquement les énoncés négatifs', 'Apprendre au client à se parler positivement', 'Modifier la perception par le langage', 'Outil quotidien d''auto-coaching'],
   'GS Formation — Technicien PNL & Hypnose',
   ARRAY['Estime & confiance en soi']
  ),
  (885,
   'Stratégie pour retrouver ses compétences',
   'Technicien — Compétences',
   'PNL',
   'Protocole pour retrouver une compétence perdue ou bloquée (parler en public, créativité, mémoire). Reconnexion au moment où la compétence existait, identification de la stratégie sous-jacente, restauration.',
   '60 min',
   'Intermédiaire',
   ARRAY['PNL', 'compétences', 'stratégie', 'récupération', 'blocage'],
   '#2E8A7B',
   1,
   ARRAY['Reconnecter à une compétence perdue', 'Identifier la stratégie interne qui la portait', 'Lever le blocage récent', 'Restaurer l''accès à la compétence'],
   'GS Formation — Technicien PNL & Hypnose',
   ARRAY['Estime & confiance en soi', 'Performance & examens']
  ),
  (886,
   'Souvenir agréable — Premier pas en hypnose',
   'Technicien — Induction',
   'Hypnose Ericksonienne',
   'Induction simple et rassurante via un souvenir agréable du client. Première mise en transe douce, idéale pour les débutants ou les craintifs. Permet l''ancrage d''un état ressource.',
   '20-30 min',
   'Débutant',
   ARRAY['hypnose', 'induction', 'souvenir agréable', 'débutant', 'douce'],
   '#7C5CBF',
   1,
   ARRAY['Première expérience d''hypnose en sécurité', 'Ancrer un état ressource accessible', 'Lever les peurs liées à l''hypnose', 'Préparer des inductions plus avancées'],
   'GS Formation — Technicien PNL & Hypnose',
   ARRAY['Anxiété & stress']
  ),
  (887,
   'Machine à phrases — Génération hypnotique',
   'Technicien — Linguistique',
   'Hypnose Ericksonienne',
   'Outil pédagogique pour générer mécaniquement des phrases hypnotiques en combinant patterns Milton, prédicats sensoriels et liens logiques. Permet au praticien débutant de fluidifier son discours hypnotique.',
   '15-20 min (entraînement)',
   'Débutant',
   ARRAY['hypnose', 'machine à phrases', 'Milton', 'génération', 'pédagogie'],
   '#C8A030',
   1,
   ARRAY['Fluidifier le discours hypnotique du praticien', 'Maîtriser la combinaison des patterns Milton', 'S''entraîner à improviser une induction', 'Outil de préparation avant séance réelle'],
   'GS Formation — Technicien PNL & Hypnose',
   ARRAY['Anxiété & stress']
  ),
  (888,
   'Induction standard 4-3-2-1 (VAKOG)',
   'Technicien — Induction',
   'Hypnose Ericksonienne',
   'Induction structurée par décompte sensoriel : 4 perceptions visuelles, 3 auditives, 2 kinesthésiques, 1 imaginaire ; puis reprise inverse 1-2-3-4. Approfondissement progressif et sécurisant.',
   '15-20 min',
   'Débutant',
   ARRAY['hypnose', 'induction', '4-3-2-1', 'VAKOG', 'décompte'],
   '#5B8FB9',
   1,
   ARRAY['Atteindre une transe légère à moyenne', 'Maîtriser une induction structurée et reproductible', 'Travailler la concentration sensorielle du client', 'Préparer un travail thérapeutique en transe'],
   'GS Formation — Technicien PNL & Hypnose',
   ARRAY['Anxiété & stress']
  ),
  (889,
   'Apprentissage hypnotique aux 5 éléments',
   'Technicien — Induction',
   'Hypnose Ericksonienne',
   'Induction par évocation des 5 éléments naturels (terre, eau, feu, air, éther). Le client traverse en imagination chaque élément, ressent ses qualités, intègre les ressources associées. Approche poétique et symbolique.',
   '30-45 min',
   'Intermédiaire',
   ARRAY['hypnose', 'induction', '5 éléments', 'symbolique', 'naturel'],
   '#2E8A7B',
   1,
   ARRAY['Induire la transe par voie symbolique', 'Travailler les ressources élémentales (ancrage, fluidité, énergie)', 'Approche poétique pour clients sensibles à l''imaginaire', 'Préparer un travail spirituel ou énergétique'],
   'GS Formation — Technicien PNL & Hypnose',
   ARRAY['Quête de sens & spiritualité', 'Anxiété & stress']
  ),
  (890,
   'Inductions par éléments naturels',
   'Technicien — Induction',
   'Hypnose Ericksonienne',
   'Inductions inspirées de la nature : ruisseau, forêt, montagne, océan, vent. Métaphores naturelles soutenues par évocation sensorielle riche. Approfondissement par immersion progressive dans le paysage.',
   '20-30 min',
   'Débutant',
   ARRAY['hypnose', 'induction', 'nature', 'paysage', 'immersion'],
   '#2E8A7B',
   1,
   ARRAY['Atteindre la transe via l''évocation naturelle', 'Adapter l''induction aux préférences du client', 'Faciliter l''immersion sensorielle', 'Outil pour clients sensibles à la nature'],
   'GS Formation — Technicien PNL & Hypnose',
   ARRAY['Anxiété & stress']
  ),
  (891,
   'Technique du tunnel — Approfondissement',
   'Technicien — Approfondissement',
   'Hypnose Ericksonienne',
   'Métaphore du tunnel pour approfondir la transe : le client descend dans un tunnel, chaque pas approfondit l''état. Au bout du tunnel, accès à un espace ressource ou à une scène thérapeutique.',
   '15-20 min (intégré)',
   'Intermédiaire',
   ARRAY['hypnose', 'approfondissement', 'tunnel', 'métaphore', 'descente'],
   '#1B2D47',
   1,
   ARRAY['Approfondir la transe atteinte par induction initiale', 'Préparer l''accès à un espace symbolique', 'Métaphore d''immersion progressive', 'Faciliter le travail dans l''inconscient'],
   'GS Formation — Technicien PNL & Hypnose',
   ARRAY['Anxiété & stress']
  ),
  (892,
   'Reprendre ses esprits — Sortie de transe',
   'Technicien — Sortie',
   'Hypnose Ericksonienne',
   'Protocole structuré de sortie de transe : reconnexion progressive aux sensations corporelles, comptage 1-5, ancrage des acquis, débrief court. Garantit un retour pleinement présent et intégré.',
   '5-10 min (en fin de séance)',
   'Débutant',
   ARRAY['hypnose', 'sortie de transe', 'réveil', 'ancrage', 'sécurité'],
   '#E08550',
   1,
   ARRAY['Sortir le client en sécurité de la transe', 'Ancrer les acquis du travail thérapeutique', 'Reconnecter pleinement aux sensations corporelles', 'Préparer le retour à l''activité normale'],
   'GS Formation — Technicien PNL & Hypnose',
   ARRAY['Anxiété & stress']
  ),
  (893,
   'Chevauchement VAKOG — Transition sensorielle',
   'Technicien — Représentations',
   'PNL',
   'Technique de transition douce d''un canal sensoriel à un autre (V→A→K→O→G) pour faciliter la transe ou enrichir une représentation. Particulièrement utile pour les clients monosensoriels.',
   '15-20 min (intégré)',
   'Intermédiaire',
   ARRAY['PNL', 'chevauchement', 'VAKOG', 'transition', 'monosensoriel'],
   '#5B8FB9',
   1,
   ARRAY['Faciliter la transition entre canaux sensoriels', 'Enrichir une représentation pauvre', 'Aider les clients monosensoriels', 'Préparer une induction VAKOG complète'],
   'GS Formation — Technicien PNL & Hypnose',
   ARRAY['Anxiété & stress']
  ),
  (894,
   'EP/ED/ECO — Modèle de changement',
   'Technicien — Changement',
   'PNL',
   'Modèle PNL de changement : État Présent (EP) → État Désiré (ED) → État de Conscience Optimale (ECO). Cartographie en 3 temps qui structure toute intervention PNL et garantit l''écologie.',
   '45-60 min',
   'Intermédiaire',
   ARRAY['PNL', 'EP', 'ED', 'ECO', 'modèle changement', 'écologie'],
   '#7C5CBF',
   1,
   ARRAY['Cartographier précisément l''état actuel du client', 'Définir un état désiré écologique', 'Identifier l''état de conscience optimale pour le changement', 'Structurer toute intervention PNL'],
   'GS Formation — Technicien PNL & Hypnose',
   ARRAY['Estime & confiance en soi', 'Anxiété & stress']
  )
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  practice = EXCLUDED.practice,
  description = EXCLUDED.description,
  duration = EXCLUDED.duration,
  level = EXCLUDED.level,
  tags = EXCLUDED.tags,
  color = EXCLUDED.color,
  sessions = EXCLUDED.sessions,
  objectives = EXCLUDED.objectives,
  source = EXCLUDED.source,
  motifs = EXCLUDED.motifs;
