-- Seed protocoles Maître Praticien PNL — couverture exhaustive
-- IDs : 950-972 (23 protocoles)
-- Source : GS Formation — Maitre-Praticien-PNL-GS

INSERT INTO public.protocols (id, name, category, practice, description, duration, level, tags, color, sessions, objectives, source, motifs)
VALUES
  -- ===== MÉTAPROGRAMMES (950-953) =====
  (950,
   'Métaprogrammes de perception — Attention, tri GALIC, découpage',
   'Maître Praticien PNL — Métaprogrammes',
   'PNL',
   'Cartographie des 3 métaprogrammes de perception : (1) Direction de l''attention soi/autres (7/93 %), (2) Tri GALIC (Gens/Activités/Lieux/Informations/Choses 15/50/20/15), (3) Tailles de découpage global/spécifique (60/25/15). Diagnostic profond du fonctionnement.',
   '60-90 min (diagnostic)',
   'Avancé',
   ARRAY['PNL', 'métaprogrammes', 'perception', 'GALIC', 'découpage', 'attention'],
   '#7C5CBF',
   1,
   ARRAY['Identifier le profil attentionnel du client (soi vs autres)', 'Cartographier le tri GALIC dominant', 'Identifier la taille de découpage préférentielle', 'Adapter sa communication au profil'],
   'GS Formation — Maitre Praticien PNL',
   ARRAY['Conflits & communication', 'Estime & confiance en soi']
  ),
  (951,
   'Métaprogrammes de traitement — Relation, temps, accession',
   'Maître Praticien PNL — Métaprogrammes',
   'PNL',
   'Cartographie des métaprogrammes de traitement de l''information : (1) Relation accord/désaccord/similitude/différence, (2) Orientation temporelle passé/présent/futur, (3) Accession au temps simultanée/séquentielle. Outil-clé pour comprendre les conflits cognitifs.',
   '60 min (diagnostic)',
   'Avancé',
   ARRAY['PNL', 'métaprogrammes', 'traitement', 'temps', 'relation', 'cognition'],
   '#5B8FB9',
   1,
   ARRAY['Identifier le mode relationnel (accord/désaccord/similitude/différence)', 'Cartographier l''orientation temporelle dominante', 'Comprendre l''accession au temps simultanée vs séquentielle', 'Adapter le coaching au profil cognitif'],
   'GS Formation — Maitre Praticien PNL',
   ARRAY['Conflits & communication', 'Performance & examens']
  ),
  (952,
   'Métaprogrammes de motivation — Direction, modaux, engagement',
   'Maître Praticien PNL — Métaprogrammes',
   'PNL',
   'Cartographie des métaprogrammes de motivation : (1) Direction aller-vers/s''éloigner-de, (2) Opérateurs modaux possibilité/nécessité/options/procédures, (3) Engagement actif/passif/proactif/réactif. Détermine la stratégie motivationnelle individuelle.',
   '60-90 min (diagnostic)',
   'Avancé',
   ARRAY['PNL', 'métaprogrammes', 'motivation', 'aller vers', 'modaux', 'engagement'],
   '#C8A030',
   1,
   ARRAY['Identifier la direction motivationnelle (vers vs loin de)', 'Cartographier les opérateurs modaux dominants', 'Comprendre le mode d''engagement', 'Construire un coaching motivationnel sur mesure'],
   'GS Formation — Maitre Praticien PNL',
   ARRAY['Procrastination & motivation', 'Performance & examens']
  ),
  (953,
   'Cartographie complète des métaprogrammes — Profil PNL',
   'Maître Praticien PNL — Métaprogrammes',
   'PNL',
   'Séance dédiée à l''établissement du profil PNL complet du client via les 9+ dimensions de métaprogrammes. Document écrit remis au client. Base d''un parcours de coaching personnalisé. Outil de diagnostic en première séance Maître Praticien.',
   '90-120 min',
   'Avancé',
   ARRAY['PNL', 'métaprogrammes', 'cartographie', 'profil', 'diagnostic'],
   '#2E8A7B',
   1,
   ARRAY['Établir le profil PNL complet (9+ dimensions)', 'Remettre un document écrit au client', 'Préparer un coaching personnalisé', 'Outil de première séance Maître Praticien'],
   'GS Formation — Maitre Praticien PNL',
   ARRAY['Estime & confiance en soi', 'Performance & examens']
  ),

  -- ===== STRATÉGIES AVANCÉES (954-957) =====
  (954,
   'Méta-objectif & stratégie d''objectif avancée',
   'Maître Praticien PNL — Stratégies',
   'PNL',
   'Travail en deux temps : (1) Méta-objectif — l''objectif au-delà de l''objectif (« Si vous aviez X, qu''est-ce que cela vous apporterait de plus important ? »), (2) Stratégie d''objectif structurée VAKOG avec critères SMART et écologie systémique.',
   '60-75 min',
   'Avancé',
   ARRAY['PNL', 'méta-objectif', 'stratégie', 'objectif', 'écologie'],
   '#7C5CBF',
   1,
   ARRAY['Identifier le méta-objectif (sens profond)', 'Construire une stratégie d''objectif VAKOG', 'Vérifier l''écologie systémique', 'Aligner objectif et valeurs profondes'],
   'GS Formation — Maitre Praticien PNL',
   ARRAY['Quête de sens & spiritualité', 'Performance & examens']
  ),
  (955,
   'Stratégies de motivation — Aller vers / S''éloigner de',
   'Maître Praticien PNL — Stratégies',
   'PNL',
   'Identification de la stratégie motivationnelle dominante du client (« aller vers » l''objectif souhaité, ou « s''éloigner de » l''état non désiré). Travail d''équilibrage si trop polarisé. Construction d''une motivation hybride durable.',
   '60 min',
   'Avancé',
   ARRAY['PNL', 'motivation', 'aller vers', 'éloigner', 'équilibrage'],
   '#C8A030',
   1,
   ARRAY['Identifier le mode motivationnel dominant', 'Équilibrer si trop polarisé', 'Construire une motivation hybride', 'Pérenniser la motivation au-delà du déclencheur initial'],
   'GS Formation — Maitre Praticien PNL',
   ARRAY['Procrastination & motivation', 'Performance & examens']
  ),
  (956,
   'Les Mentors — Intégration de ressources archétypales',
   'Maître Praticien PNL — Ressources',
   'PNL',
   'Technique d''intégration de ressources externes via la figure du Mentor. Le client choisit 3 mentors (réels ou imaginaires) qui possèdent les ressources visées. Visite imaginaire de chaque mentor, dialogue, intégration des ressources, ancrage.',
   '60-90 min',
   'Avancé',
   ARRAY['PNL', 'mentors', 'ressources', 'archétypes', 'intégration'],
   '#5B8FB9',
   1,
   ARRAY['Choisir 3 mentors porteurs de ressources visées', 'Dialoguer avec chaque mentor en imagination', 'Intégrer les ressources captées', 'Ancrer pour activation future'],
   'GS Formation — Maitre Praticien PNL',
   ARRAY['Estime & confiance en soi', 'Quête de sens & spiritualité']
  ),
  (957,
   'Schéma de Dickens & Modèle SOAR — Projection temporelle',
   'Maître Praticien PNL — Stratégies temporelles',
   'PNL',
   'Deux outils complémentaires : (1) Schéma de Dickens (3 projections — passé coût, présent réalité, futur sans changement vs avec changement), (2) Modèle SOAR (Situation, Outcome, Action, Resources) pour la planification stratégique. Particulièrement puissants pour décision majeure.',
   '90 min',
   'Avancé',
   ARRAY['PNL', 'Dickens', 'SOAR', 'projection', 'décision', 'temporel'],
   '#2E8A7B',
   1,
   ARRAY['Visualiser passé, présent et futur sans changement', 'Construire le futur avec changement', 'Appliquer SOAR pour la planification', 'Décider en conscience d''un changement majeur'],
   'GS Formation — Maitre Praticien PNL',
   ARRAY['Procrastination & motivation', 'Estime & confiance en soi']
  ),

  -- ===== MODÉLISATION MP (958-959) =====
  (958,
   'Modélisation des compétences — Protocole complet',
   'Maître Praticien PNL — Modélisation',
   'PNL',
   'Protocole MP complet de modélisation : choix du modèle, observation directe ou interview, identification des facteurs critiques (croyances, valeurs, capacités, comportements), test sur soi, transmission. Compétence-clé du Maître Praticien.',
   '120-180 min × plusieurs séances',
   'Avancé',
   ARRAY['PNL', 'modélisation', 'compétences', 'observation', 'transmission'],
   '#7C5CBF',
   3,
   ARRAY['Choisir un modèle d''excellence', 'Identifier les facteurs critiques de la compétence', 'Tester la modélisation sur soi', 'Transmettre la compétence à un tiers'],
   'GS Formation — Maitre Praticien PNL',
   ARRAY['Performance & examens', 'Estime & confiance en soi']
  ),
  (959,
   'Modélisation par les niveaux logiques',
   'Maître Praticien PNL — Modélisation',
   'PNL',
   'Variante de modélisation utilisant les 6 niveaux logiques de Dilts pour une analyse exhaustive. Pour chaque niveau (Environnement, Comportement, Capacités, Croyances/Valeurs, Identité, Mission), capture des éléments-clés du modèle. Transposition adaptée au contexte du client.',
   '120 min',
   'Avancé',
   ARRAY['PNL', 'modélisation', 'niveaux logiques', 'Dilts', 'transposition'],
   '#C8A030',
   1,
   ARRAY['Modéliser un expert via les 6 niveaux logiques', 'Capturer les éléments-clés à chaque niveau', 'Transposer au contexte du client', 'Construire un plan d''appropriation progressive'],
   'GS Formation — Maitre Praticien PNL',
   ARRAY['Performance & examens']
  ),

  -- ===== VALEURS & CRITÈRES AVANCÉS (960-962) =====
  (960,
   'Pyramide de Maslow appliquée à la PNL',
   'Maître Praticien PNL — Valeurs',
   'PNL',
   'Application de la pyramide de Maslow (besoins physiologiques, sécurité, appartenance, estime, accomplissement, transcendance) à la cartographie des valeurs du client. Identification du palier de motivation actuel et du palier visé. Stratégie d''ascension.',
   '60 min',
   'Intermédiaire',
   ARRAY['PNL', 'Maslow', 'pyramide', 'besoins', 'valeurs'],
   '#5B8FB9',
   1,
   ARRAY['Identifier le palier de Maslow actuel du client', 'Visualiser le palier visé', 'Construire la stratégie d''ascension', 'Aligner valeurs et besoins'],
   'GS Formation — Maitre Praticien PNL',
   ARRAY['Estime & confiance en soi', 'Quête de sens & spiritualité']
  ),
  (961,
   'Déstabiliser un critère limitant',
   'Maître Praticien PNL — Valeurs',
   'PNL',
   'Technique avancée pour déstabiliser un critère devenu limitant (« Pour être heureux, il faut absolument être riche »). Recherche de contre-exemples, mise en doute des équivalences complexes, élargissement des références. Permet l''émergence de nouveaux critères.',
   '60 min',
   'Avancé',
   ARRAY['PNL', 'critère', 'déstabilisation', 'contre-exemples', 'limitant'],
   '#B85450',
   1,
   ARRAY['Identifier un critère devenu limitant', 'Trouver 5+ contre-exemples solides', 'Mettre en doute les équivalences complexes', 'Permettre l''émergence d''un critère plus écologique'],
   'GS Formation — Maitre Praticien PNL',
   ARRAY['Estime & confiance en soi', 'Conflits & communication']
  ),
  (962,
   'Étendre les équivalences d''un critère',
   'Maître Praticien PNL — Valeurs',
   'PNL',
   'Technique inverse de la déstabilisation : élargir les façons concrètes dont un critère peut être satisfait. Ex : « liberté » peut être satisfait par voyages, choix de carrière, autonomie financière, créativité. Ouvre l''espace des satisfactions possibles.',
   '45-60 min',
   'Intermédiaire',
   ARRAY['PNL', 'critère', 'équivalences', 'extension', 'satisfaction'],
   '#2E8A7B',
   1,
   ARRAY['Identifier un critère mal défini ou trop étroit', 'Lister 10+ équivalences concrètes possibles', 'Élargir l''espace des satisfactions', 'Réduire la frustration liée à une définition trop étroite'],
   'GS Formation — Maitre Praticien PNL',
   ARRAY['Estime & confiance en soi', 'Quête de sens & spiritualité']
  ),

  -- ===== CROYANCES AVANCÉES (963-967) =====
  (963,
   'Détecteur de croyances « Oh ! Oh ! »',
   'Maître Praticien PNL — Croyances',
   'PNL',
   'Outil de détection des croyances cachées dans le discours du client. Le praticien repère les phrases qui sonnent comme une vérité absolue (« Oh, ça c''est une croyance ! »). Mise au jour systématique. Cartographie de la matrice de croyances limitantes.',
   '45 min (intégré)',
   'Avancé',
   ARRAY['PNL', 'croyances', 'détecteur', 'cartographie', 'matrice'],
   '#C8A030',
   1,
   ARRAY['Détecter les croyances cachées dans le discours', 'Cartographier la matrice de croyances', 'Distinguer croyances limitantes vs aidantes', 'Préparer le travail de transformation'],
   'GS Formation — Maitre Praticien PNL',
   ARRAY['Estime & confiance en soi', 'Anxiété & stress']
  ),
  (964,
   'Marche de transformation des croyances',
   'Maître Praticien PNL — Croyances',
   'PNL',
   'Protocole spatial de transformation : 5 espaces au sol (croyance ancienne, doute, ouverture, nouvelle croyance, intégration). Le client traverse physiquement chaque espace, vit l''évolution kinesthésique de la croyance. Particulièrement puissant pour croyances ancrées.',
   '60-90 min',
   'Avancé',
   ARRAY['PNL', 'croyances', 'marche', 'spatial', 'transformation'],
   '#7C5CBF',
   1,
   ARRAY['Vivre la transformation kinesthésiquement', 'Traverser les 5 espaces (ancienne → doute → ouverture → nouvelle → intégration)', 'Ancrer la nouvelle croyance par marche', 'Lever les croyances très ancrées'],
   'GS Formation — Maitre Praticien PNL',
   ARRAY['Estime & confiance en soi', 'Anxiété & stress']
  ),
  (965,
   'Marelle des croyances',
   'Maître Praticien PNL — Croyances',
   'PNL',
   'Variante ludique et puissante de transformation : carrés au sol (comme une marelle) représentant les étapes de transformation d''une croyance. Le client saute d''un carré à l''autre, ancrant chaque étape physiquement. Particulièrement adapté aux clients kinesthésiques.',
   '45-60 min',
   'Avancé',
   ARRAY['PNL', 'marelle', 'croyances', 'spatial', 'kinesthésique'],
   '#E08550',
   1,
   ARRAY['Transformer une croyance par jeu spatial', 'Ancrer kinesthésiquement chaque étape', 'Aborder le travail avec légèreté', 'Particulièrement efficace pour kinesthésiques'],
   'GS Formation — Maitre Praticien PNL',
   ARRAY['Estime & confiance en soi']
  ),
  (966,
   'Re-imprinting — Empreinte parentale (Dilts)',
   'Maître Praticien PNL — Croyances',
   'PNL',
   'Protocole emblématique de Robert Dilts pour transformer les empreintes parentales (croyances/comportements installés tôt par les figures parentales). Voyage temporel, dialogue avec les figures parentales, transmission des ressources actuelles à l''enfant intérieur, intégration.',
   '90-120 min',
   'Avancé',
   ARRAY['PNL', 're-imprinting', 'Dilts', 'empreinte', 'parentale', 'enfant intérieur'],
   '#B85450',
   1,
   ARRAY['Identifier l''empreinte parentale limitante', 'Voyager symboliquement à la scène d''empreinte', 'Transmettre les ressources adultes à l''enfant', 'Réécrire l''empreinte au niveau identitaire'],
   'GS Formation — Maitre Praticien PNL',
   ARRAY['Trauma & deuil', 'Estime & confiance en soi']
  ),
  (967,
   'Transgénéralisateur — Universalisation d''une ressource',
   'Maître Praticien PNL — Croyances',
   'PNL',
   'Technique avancée pour généraliser une ressource ou une nouvelle croyance à TOUS les contextes de vie. Ancrage massif, transposition mentale aux multiples situations, vérification écologique. Outil de pérennisation du changement post-PNL.',
   '60 min',
   'Avancé',
   ARRAY['PNL', 'transgénéralisateur', 'universalisation', 'ressource', 'pérennisation'],
   '#5B8FB9',
   1,
   ARRAY['Universaliser une ressource à tous les contextes', 'Transposer mentalement à 10+ situations', 'Pérenniser le changement post-séance', 'Vérifier l''écologie globale'],
   'GS Formation — Maitre Praticien PNL',
   ARRAY['Estime & confiance en soi']
  ),

  -- ===== IDENTITÉ (968-972) =====
  (968,
   '6 clés de la confiance en soi — Pratique quotidienne',
   'Maître Praticien PNL — Identité',
   'PNL',
   'Protocole quotidien des 6 clés de la confiance en soi : (1) Vivre conscient, (2) S''accepter, (3) Se responsabiliser, (4) S''affirmer, (5) Vivre intentionnellement, (6) S''engager dans l''intégrité. Inspiré de Nathaniel Branden. Pratique quotidienne 21 jours.',
   '15-30 min/jour pendant 21 jours',
   'Intermédiaire',
   ARRAY['PNL', 'confiance en soi', '6 clés', 'Branden', 'pratique quotidienne'],
   '#C8A030',
   1,
   ARRAY['Pratiquer les 6 piliers quotidiennement', 'Renforcer durablement l''estime de soi', 'Outil d''auto-coaching à long terme', 'Inspiration : Nathaniel Branden'],
   'GS Formation — Maitre Praticien PNL',
   ARRAY['Estime & confiance en soi']
  ),
  (969,
   'Restaurer l''estime de soi — Protocole complet',
   'Maître Praticien PNL — Identité',
   'PNL',
   'Protocole complet de restauration de l''estime de soi : identification des blessures fondatrices, recadrage, ancrage des réussites, dialogue avec l''enfant intérieur, transmission des ressources adultes, intégration au niveau identitaire. Travail en profondeur.',
   '90 min × 3-5 séances',
   'Avancé',
   ARRAY['PNL', 'estime de soi', 'restauration', 'enfant intérieur', 'identité'],
   '#7C5CBF',
   4,
   ARRAY['Identifier les blessures fondatrices de l''estime', 'Recadrer les expériences clés', 'Dialoguer avec l''enfant intérieur', 'Reconstruire l''estime au niveau identitaire'],
   'GS Formation — Maitre Praticien PNL',
   ARRAY['Estime & confiance en soi', 'Trauma & deuil']
  ),
  (970,
   'Faire taire l''auto-critique',
   'Maître Praticien PNL — Identité',
   'PNL',
   'Technique précise pour identifier et désamorcer la voix auto-critique intérieure. Cartographie sensorielle de la voix (tonalité, volume, position), modulation par sous-modalités, transformation en voix bienveillante, ancrage. Outil quotidien d''auto-régulation.',
   '45-60 min',
   'Intermédiaire',
   ARRAY['PNL', 'auto-critique', 'voix intérieure', 'sous-modalités auditives'],
   '#B85450',
   1,
   ARRAY['Cartographier la voix auto-critique sensoriellement', 'Moduler la voix par sous-modalités auditives', 'Transformer en voix bienveillante', 'Ancrer pour activation quotidienne'],
   'GS Formation — Maitre Praticien PNL',
   ARRAY['Estime & confiance en soi', 'Anxiété & stress']
  ),
  (971,
   'Le Centre de l''Étoile — Identité-noyau',
   'Maître Praticien PNL — Identité',
   'PNL',
   'Visualisation puissante du centre identitaire : étoile à plusieurs branches (rôles sociaux, talents, valeurs) avec un cœur central immuable (l''Identité-noyau). Le client visite chaque branche puis se recentre. Particulièrement utile en perte de sens, transition.',
   '60 min',
   'Avancé',
   ARRAY['PNL', 'Centre Étoile', 'identité', 'noyau', 'transition'],
   '#7C5CBF',
   1,
   ARRAY['Visualiser ses branches identitaires (rôles, talents, valeurs)', 'Se reconnecter au cœur immuable', 'Sortir d''une crise identitaire', 'Préparer une transition de vie majeure'],
   'GS Formation — Maitre Praticien PNL',
   ARRAY['Quête de sens & spiritualité', 'Burn-out & fatigue']
  ),
  (972,
   'Mission & Vision personnelle — Alignement profond',
   'Maître Praticien PNL — Identité',
   'PNL',
   'Travail d''identification de la mission et de la vision personnelle. Visualisation au niveau Spirituel/Mission des niveaux logiques. Formulation écrite de la mission (à quoi je sers) et de la vision (le monde que je veux contribuer à créer). Alignement de tous les niveaux logiques.',
   '90-120 min',
   'Avancé',
   ARRAY['PNL', 'mission', 'vision', 'sens', 'spirituel', 'alignement'],
   '#2E8A7B',
   1,
   ARRAY['Identifier sa mission personnelle (à quoi je sers)', 'Définir sa vision (monde à co-créer)', 'Aligner tous les niveaux logiques sur la mission', 'Décider en conscience des prochains pas de vie'],
   'GS Formation — Maitre Praticien PNL',
   ARRAY['Quête de sens & spiritualité']
  )
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  practice = EXCLUDED.practice,
  description = EXCLUDED.description,
  duration = EXCLUDED.duration,
  level = EXCLUDED.level,
  tags = EXCLUDED.tags,
  color = EXCLUDED.color,
  sessions = EXCLUDED.sessions,
  objectives = EXCLUDED.objectives,
  source = EXCLUDED.source,
  motifs = EXCLUDED.motifs;
