-- Seed protocoles Praticien PNL (livret GS Formation)
-- IDs : 855-859 + 895-899 (10 protocoles)
-- Source : GS Formation — PNL Prat (livret Praticien PNL)

INSERT INTO public.protocols (id, name, category, practice, description, duration, level, tags, color, sessions, objectives, source, motifs)
VALUES
  (855,
   'Stratégie de Walt Disney — Rêveur, Réalisateur, Critique',
   'Praticien PNL — Créativité',
   'PNL',
   'Stratégie de créativité de Walt Disney : 3 espaces ancrés au sol — Rêveur (vision libre, dissocié), Réalisateur (planification associée), Critique (évaluation auditive). Le sujet visite chaque espace successivement avec un projet, intégrant les 3 perspectives.',
   '60-75 min',
   'Intermédiaire',
   ARRAY['PNL', 'Walt Disney', 'créativité', 'rêveur', 'réalisateur', 'critique', '3 positions'],
   '#7C5CBF',
   1,
   ARRAY['Développer un projet créatif équilibré', 'Aligner vision, plan et critique sans qu''ils s''interfèrent', 'Sortir d''un blocage créatif', 'Préparer un projet professionnel ou personnel'],
   'GS Formation — Praticien PNL',
   ARRAY['Estime & confiance en soi', 'Performance & examens']
  ),
  (856,
   'Stratégie de Léonard de Vinci — Modélisation du génie',
   'Praticien PNL — Modélisation',
   'PNL',
   'Modélisation des stratégies de pensée de Léonard de Vinci : observation aiguë (V), questionnement permanent, lien entre disciplines (synesthésie), expérimentation pratique. Outil d''excellence pour développer curiosité, créativité et apprentissage.',
   '60 min',
   'Avancé',
   ARRAY['PNL', 'Léonard de Vinci', 'modélisation', 'génie', 'observation', 'curiosité'],
   '#C8A030',
   1,
   ARRAY['Modéliser la stratégie d''un génie créatif', 'Développer la curiosité multidisciplinaire', 'Affûter l''observation sensorielle', 'Cultiver le questionnement permanent'],
   'GS Formation — Praticien PNL',
   ARRAY['Estime & confiance en soi', 'Performance & examens']
  ),
  (857,
   'Négociation entre parties — Conflit espace-temps',
   'Praticien PNL — Conflit interne',
   'PNL',
   'Technique de négociation entre 2 parties qui se gênent mutuellement (ex : partie « travail » vs partie « détente »). Identification des intentions positives, négociation d''un accord pour ne plus s''interrompre, vérification écologique. Différent du Recadrage 6 pas.',
   '60-90 min',
   'Avancé',
   ARRAY['PNL', 'parties', 'négociation', 'conflit interne', 'espace-temps'],
   '#5B8FB9',
   1,
   ARRAY['Identifier 2 parties en conflit séquentiel', 'Comprendre l''intention positive de chaque partie', 'Négocier un accord de non-interférence', 'Vérifier l''écologie (autres parties impliquées)'],
   'GS Formation — Praticien PNL',
   ARRAY['Conflits & communication', 'Procrastination & motivation']
  ),
  (858,
   'Squash visuel — Intégration de parties par les mains',
   'Praticien PNL — Conflit interne',
   'PNL',
   'Technique d''intégration de 2 parties en conflit simultané (ex : « vivre l''amour » vs « préserver liberté »). Visualisation des 2 parties dans chaque main avec VAK et symboles, dialogue, recherche de la valeur commune (chunk up), rapprochement des mains, fusion au cœur.',
   '60-90 min',
   'Avancé',
   ARRAY['PNL', 'squash visuel', 'intégration parties', 'mains', 'chunk up', 'valeur commune'],
   '#7C5CBF',
   1,
   ARRAY['Intégrer 2 parties en conflit simultané', 'Identifier la valeur commune au-dessus du conflit', 'Fusionner symboliquement au chakra du cœur', 'Travail majeur sur les buts de vie'],
   'GS Formation — Praticien PNL',
   ARRAY['Conflits & communication', 'Quête de sens & spiritualité']
  ),
  (859,
   'Hiérarchie des valeurs — Reclassement par domaine',
   'Praticien PNL — Valeurs',
   'PNL',
   'Protocole d''identification et de reclassement des valeurs dans 3 domaines (personnel, sentimental, professionnel). 10 valeurs par domaine, sélection des 5 principales, classement par priorité, exploration de chacune. Outil d''alignement de vie.',
   '90-120 min',
   'Intermédiaire',
   ARRAY['PNL', 'valeurs', 'hiérarchie', 'critères', 'alignement', 'sens'],
   '#2E8A7B',
   1,
   ARRAY['Identifier 10 valeurs par domaine de vie', 'Reclasser les 5 principales par ordre d''importance', 'Vérifier la cohérence avec la vie actuelle', 'Aligner les choix de vie avec les valeurs profondes'],
   'GS Formation — Praticien PNL',
   ARRAY['Estime & confiance en soi', 'Quête de sens & spiritualité']
  ),
  (895,
   'Croyances — Identification & transformation',
   'Praticien PNL — Croyances',
   'PNL',
   'Travail sur les croyances limitantes : identification (« Je suis... », « Les gens sont... », « Le monde est... », « Il faut... »), exploration de l''origine, recherche de l''expérience de référence, transformation par sous-modalités et changement d''histoire personnelle.',
   '60-90 min',
   'Intermédiaire',
   ARRAY['PNL', 'croyances', 'limitantes', 'transformation', 'sous-modalités'],
   '#B85450',
   1,
   ARRAY['Identifier les croyances limitantes principales', 'Distinguer croyances héritées vs personnelles', 'Transformer par modulation des sous-modalités', 'Installer une croyance aidante à la place'],
   'GS Formation — Praticien PNL',
   ARRAY['Estime & confiance en soi', 'Anxiété & stress']
  ),
  (896,
   'Double dissociation — Trauma léger en sécurité',
   'Praticien PNL — Trauma',
   'PNL',
   'Technique PNL emblématique de traitement des traumas légers et phobies. Le sujet est dissocié 2 fois : il se voit dans la salle de cinéma se regardant à l''écran. Permet de revisiter un événement traumatique avec sécurité maximale et recadrage à distance.',
   '60-90 min',
   'Avancé',
   ARRAY['PNL', 'double dissociation', 'trauma léger', 'phobie', 'sécurité', 'cinéma'],
   '#7C5CBF',
   1,
   ARRAY['Traiter un trauma léger ou phobie sans revivification directe', 'Dissocier 2 fois pour sécurité maximale', 'Recadrer la scène à distance', 'Réintégrer en associé seulement si le SUDS est < 2'],
   'GS Formation — Praticien PNL',
   ARRAY['Trauma & deuil', 'Phobies & peurs']
  ),
  (897,
   'Fondu visuel — Substitution d''image',
   'Praticien PNL — Sous-modalités',
   'PNL',
   'Technique de substitution rapide d''une image limitante par une image ressource. Variante du Swish basée sur le fondu progressif (l''image cible apparaît progressivement à la place de l''image source). Particulièrement efficace sur représentations visuelles persistantes.',
   '20-30 min',
   'Intermédiaire',
   ARRAY['PNL', 'fondu visuel', 'substitution', 'sous-modalités', 'image'],
   '#C8A030',
   1,
   ARRAY['Substituer une image limitante par une image ressource', 'Variante du Swish à fondu progressif', 'Modifier durablement une représentation persistante', 'Outil rapide de reconditionnement visuel'],
   'GS Formation — Praticien PNL',
   ARRAY['Anxiété & stress', 'Phobies & peurs']
  ),
  (898,
   'Carré magique — Alignement de l''ego par 3 perspectives × 3 temps',
   'Praticien PNL — Alignement',
   'PNL',
   'Méthode d''alignement de l''ego pour généraliser une ressource. Carré de 9 cases (3 perspectives : Moi/Autres/Sage × 3 temps : Passé/Présent/Futur). Le sujet visite chaque case avec sa ressource, reçoit un message de chaque perspective, intègre.',
   '60-90 min',
   'Avancé',
   ARRAY['PNL', 'carré magique', 'alignement', 'ego', '3 positions', '3 temps'],
   '#5B8FB9',
   1,
   ARRAY['Généraliser une ressource sur tous les contextes', 'Intégrer 3 perspectives (soi, autres, sage)', 'Intégrer les 3 temps (passé, présent, futur)', 'Renforcer l''ancrage d''une ressource majeure'],
   'GS Formation — Praticien PNL',
   ARRAY['Estime & confiance en soi', 'Quête de sens & spiritualité']
  ),
  (899,
   'Réparation de relation endommagée — 7 étapes',
   'Praticien PNL — Relation',
   'PNL',
   'Protocole de Leslie Cameron Bandler en 7 étapes : identification des critères, identification des différences (passé/présent/futur), satisfactions, vérification écologique, traitement des comportements problématiques, changement d''histoire de la relation, construction du futur.',
   '90-120 min × 2-3 séances',
   'Avancé',
   ARRAY['PNL', 'relation', 'couple', 'amitié', 'professionnel', 'Leslie Cameron Bandler', '7 étapes'],
   '#B85450',
   3,
   ARRAY['Évaluer une relation endommagée objectivement', 'Identifier les évolutions des critères dans le temps', 'Reconnaître les satisfactions reçues', 'Reconstruire ou décider en conscience'],
   'GS Formation — Praticien PNL',
   ARRAY['Conflits & communication', 'Couple & sexualité']
  )
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  practice = EXCLUDED.practice,
  description = EXCLUDED.description,
  duration = EXCLUDED.duration,
  level = EXCLUDED.level,
  tags = EXCLUDED.tags,
  color = EXCLUDED.color,
  sessions = EXCLUDED.sessions,
  objectives = EXCLUDED.objectives,
  source = EXCLUDED.source,
  motifs = EXCLUDED.motifs;
