-- INTIO — Protocoles Hammond 1990 (ASCH Handbook of Hypnotic Suggestions and Metaphors)
-- Source : D. Corydon Hammond (dir.), American Society of Clinical Hypnosis
-- IDs 600-720 pour éviter collision avec NLP (100-475) et Hypnose Spirituelle (500-514)
-- JSON sources : supabase/data/hammond/

delete from public.protocols where source = 'Hammond 1990 (ASCH)';

insert into public.protocols (id, name, category, practice, description, duration, level, tags, color, sessions, objectives, source, motifs)
values

-- ========================================================
-- CH-DENT — Hypnose dentaire (19 protocoles, IDs 600-618)
-- ========================================================
(600, 'ATM & bruxisme — Suggestions humoristiques (Golan)', 'Hypnose dentaire', 'Hypnose médicale',
 'Recadrage humoristique du serrement comme arme secrète. Phrase du soir « Rien n''est suffisamment important pour que je me mange ». Anesthésie en gant pour ratifier le contrôle.',
 '1 séance', 'Intermédiaire',
 array['Golan', 'ATM', 'Bruxisme', 'Anesthésie en gant', 'Auto-suggestion'],
 '#5B8FB9', 1,
 array['ATM', 'Bruxisme', 'Serrement', 'Stress dentaire'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(601, 'ATM — Langue entre les dents (Neiburger)', 'Hypnose dentaire', 'Hypnose médicale',
 'Réflexe protecteur : glisser la langue entre les dents du fond pour empêcher la contracture. Métaphore du « coton mouillé ».',
 '1 séance', 'Débutant',
 array['Neiburger', 'ATM', 'Réflexe protecteur'],
 '#5B8FB9', 1,
 array['ATM', 'Bruxisme'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(602, 'Bruxisme adulte — Erickson (poignée de main + chewing-gum)', 'Hypnose dentaire', 'Hypnose Ericksonienne',
 'Trois techniques : sommeil paradoxal, auto-réveil avec entraînement à la poignée de main, gomme à mâcher coincée entre joue et dents au coucher.',
 '1-2 séances', 'Avancé',
 array['Erickson', 'Bruxisme', 'Paradoxal', 'Chewing-gum'],
 '#5B8FB9', 2,
 array['Bruxisme nocturne', 'Habitudes inconscientes'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(603, 'ATM & céphalées — Tension/relaxation (Glazer)', 'Hypnose dentaire', 'Hypnose médicale',
 'Induction courte par contraste tension/relaxation des paumes. Tour du corps relaxé puis massage selon le même cheminement. 5 minutes, autohypnotisable.',
 '1 séance', 'Débutant',
 array['Glazer', 'ATM', 'Céphalées de tension', 'Courte durée'],
 '#5B8FB9', 1,
 array['ATM', 'Céphalées de tension'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(604, 'Hygiène — Fil dentaire (Kelly, McKinty, Carr)', 'Hypnose dentaire', 'Hypnose médicale',
 'Trois angles motivationnels : santé, esthétique, charme social. Étude contrôlée : 67 % d''amélioration gingivale à 8 mois vs 15 % témoin.',
 '1 séance', 'Débutant',
 array['Kelly', 'Fil dentaire', 'Prévention'],
 '#5B8FB9', 1,
 array['Hygiène bucco-dentaire'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(605, 'Haut-le-cœur — Anesthésie en gant + transfert (Golan)', 'Hypnose dentaire', 'Hypnose médicale',
 'Pseudo-injection au crayon, anesthésie en gant ratifiée par aiguille, transfert aux structures buccales (palais, gorge, gencives). Variante enfant : catalepsie du bras.',
 '1-2 séances', 'Avancé',
 array['Golan', 'Haut-le-coeur', 'Anesthésie en gant', 'Transfert'],
 '#5B8FB9', 2,
 array['Haut-le-coeur', 'Phobie dentaire'],
 'Hammond 1990 (ASCH)', array['Phobies & peurs']),

(606, 'Réflexe nauséeux — Respirer par le cou (Clarke & Persichetti)', 'Hypnose dentaire', 'Hypnose médicale',
 'Image de respiration par une ouverture crico-thyroïdienne pour détourner l''attention de la zone pharyngée. Cassettes audio + entraînement au port du dentier.',
 '1 séance', 'Intermédiaire',
 array['Clarke', 'Réflexe nauséeux', 'Imagerie'],
 '#5B8FB9', 1,
 array['Réflexe nauséeux'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(607, 'Dentier & haut-le-cœur — Décompte 1 à 10 (Beebe)', 'Hypnose dentaire', 'Hypnose médicale',
 'Décompte progressif d''estompement des sensations bizarres post-extraction. Renforcement à 1 semaine. Suivi 7 ans documenté.',
 '1-2 séances', 'Débutant',
 array['Beebe', 'Dentier', 'Décompte'],
 '#5B8FB9', 2,
 array['Adaptation dentier', 'Post-extraction'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(608, 'Haut-le-cœur — Transfert d''anesthésie (Secter)', 'Hypnose dentaire', 'Hypnose médicale',
 'Reconditionnement bref : le stimulus déclencheur (radio, brossage) produit l''anesthésie au lieu du haut-le-cœur. Prérequis : maîtrise préalable de l''anesthésie en gant.',
 '1 séance', 'Intermédiaire',
 array['Secter', 'Haut-le-coeur', 'Reconditionnement'],
 '#5B8FB9', 1,
 array['Haut-le-coeur'],
 'Hammond 1990 (ASCH)', array['Phobies & peurs']),

(609, 'Haut-le-cœur — Le film comme nourriture (Heron)', 'Hypnose dentaire', 'Hypnose médicale',
 'Yes set + recadrage du film de radio comme nourriture agréable en bouche. Sans induction formelle.',
 '1 séance', 'Débutant',
 array['Heron', 'Haut-le-coeur', 'Recadrage'],
 '#5B8FB9', 1,
 array['Haut-le-coeur radiographie'],
 'Hammond 1990 (ASCH)', array['Phobies & peurs']),

(610, 'Salivation excessive — Robinet d''eau (Secter)', 'Hypnose dentaire', 'Hypnose médicale',
 'Métaphore mécanique du robinet à fermer. Avalement de la salive puis réouverture juste assez pour humidité minimale.',
 '1 séance', 'Débutant',
 array['Secter', 'Salivation', 'Imagerie'],
 '#5B8FB9', 1,
 array['Hyper-salivation'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(611, 'Phobies dentaires — 5 techniques exploratoires (Dubin)', 'Hypnose dentaire', 'Hypnose médicale',
 'Calendrier-scanner, paresthésies, haut-le-cœur (autoritaire ou jargon technique), bruxisme, anesthésie/modification douleur en 4 étapes (manège, anneau d''or, neige).',
 '2-3 séances', 'Avancé',
 array['Dubin', 'Phobie dentaire', 'Calendrier-scanner', 'Paresthésies'],
 '#5B8FB9', 3,
 array['Phobie dentaire', 'Paresthésies', 'Bruxisme', 'Haut-le-coeur'],
 'Hammond 1990 (ASCH)', array['Phobies & peurs']),

(612, 'Extraction — Induction rapide & anesthésie complète (Finkelstein)', 'Hypnose dentaire', 'Hypnose médicale',
 'Induction par hausse des épaules. Suggestion d''anesthésique de surface très efficace, contrôle vasculaire et cicatrisation. Logique de transe : anesthésie suggérée APRÈS extraction.',
 '1 séance', 'Intermédiaire',
 array['Finkelstein', 'Extraction', 'Induction rapide', 'Cicatrisation'],
 '#5B8FB9', 1,
 array['Extraction dentaire'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(613, 'Hypnose dentaire — Selon douleur (Rausch)', 'Hypnose dentaire', 'Hypnose médicale',
 'Diagnostic préalable : douleur intense → induction autoritaire courte (pression remplace douleur). Sinon induction permissive. Anesthésie + contrôle saignement + autohypnose.',
 '1-2 séances', 'Avancé',
 array['Rausch', 'Pression vs douleur', 'Autohypnose'],
 '#5B8FB9', 2,
 array['Soins dentaires', 'Douleur dentaire'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(614, 'Hypnodontie — Production & test d''anesthésie (Kroger)', 'Hypnose dentaire', 'Hypnose médicale',
 'Production de l''anesthésie par bascule de la dent + suggestions, puis test obligatoire par sonde pointue avec comparaison contrastive côté traité vs côté témoin.',
 '1 séance', 'Intermédiaire',
 array['Kroger', 'Test obligatoire', 'Sonde pointue'],
 '#5B8FB9', 1,
 array['Anesthésie hypnotique'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(615, 'Enfant — Le jeu du « faisons comme si » (Staples)', 'Hypnose dentaire', 'Hypnose pédiatrique',
 'Personnage rigolo dessiné sur l''ongle du pouce, immersion dans une émission TV ou activité préférée (ski nautique). Réveil par A-B-C.',
 '1 séance', 'Intermédiaire',
 array['Staples', 'Enfants', 'Faisons comme si', 'TV'],
 '#5B8FB9', 1,
 array['Soins dentaires enfant'],
 'Hammond 1990 (ASCH)', array['Phobies & peurs']),

(616, 'Bruxisme enfant — Suggestion paradoxale (Erickson)', 'Hypnose dentaire', 'Hypnose Ericksonienne',
 'Vœu chimérique qu''il ne s''éveille pas au bruxisme — paradoxe qui conditionne précisément le réveil. Variante directe : entendre le bruxisme et se rassurer.',
 '1-2 séances', 'Avancé',
 array['Erickson', 'Enfants', 'Bruxisme', 'Paradoxal'],
 '#5B8FB9', 2,
 array['Bruxisme enfant'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(617, 'Poussée de la langue — Hallucinations & ancrage (Secter)', 'Hypnose dentaire', 'Hypnose médicale',
 'Hallucination scène déplaisante puis heureuse. Ancrage par contraste : poussée anormale → sensations désagréables / position correcte → sensations merveilleuses.',
 '1-2 séances', 'Intermédiaire',
 array['Secter', 'Orthodontie', 'Ancrage'],
 '#5B8FB9', 2,
 array['Poussée de la langue', 'Orthodontie'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(618, 'Poussée de la langue — Contact palatin (Rosinski)', 'Hypnose dentaire', 'Hypnose médicale',
 'Identification du point palatin (tissus mous derrière les incisives centrales). Étapes de déglutition normale implantées dans la mémoire subconsciente. Renforcement par compliments orthodontiste.',
 '2-3 séances', 'Intermédiaire',
 array['Rosinski', 'Orthodontie', 'Déglutition'],
 '#5B8FB9', 3,
 array['Poussée de la langue', 'Rééducation déglutition'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

-- ========================================================
-- CH-CHIR — Préparation à la chirurgie (13 protocoles, IDs 619-631)
-- ========================================================
(619, 'Préparation chirurgie — Consultation préopératoire (Fredericks)', 'Hypnoanesthésie & chirurgie', 'Hypnose médicale',
 'Personnalisation prénom + lieu refuge. Engagement de présence, réduction anesthésique, éveil paisible, restauration physiologique. Métaphore du voilier qui n''avance que vers l''avant.',
 '1-2 séances', 'Intermédiaire',
 array['Fredericks', 'Préopératoire', 'Lieu refuge', 'Voilier'],
 '#2E8A7B', 2,
 array['Préparation chirurgicale'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(620, 'Suggestions chirurgie en 10 points (Rodger)', 'Hypnoanesthésie & chirurgie', 'Hypnose médicale',
 'Cadre exhaustif pré/per/postopératoire. Filtrage attentionnel, zone opérée détendue, cicatrisation, système immunitaire, suggestions cancéreuses, sens unique digestif.',
 '1-2 séances', 'Intermédiaire',
 array['Rodger', 'Préopératoire', 'Peropératoire', 'Postopératoire'],
 '#2E8A7B', 2,
 array['Chirurgie', 'Cancer'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(621, 'Anesthésiste — Conversation avec lévitation (Corley)', 'Hypnoanesthésie & chirurgie', 'Hypnose médicale',
 'Visite préopératoire conversationnelle. Lévitation de la main, ancrage par toucher de l''épaule droite réactivable en salle d''op.',
 '1 séance', 'Intermédiaire',
 array['Corley', 'Anesthésiste', 'Lévitation', 'Ancrage épaule'],
 '#2E8A7B', 1,
 array['Préparation anesthésique'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(622, 'Hypnose préopératoire — Étapes Rossi & Cheek', 'Hypnoanesthésie & chirurgie', 'Hypnose médicale',
 'Signaux idéomoteurs, voyage mental (injection = ticket de départ), filtrage attentionnel, ratification cicatrisation, projection de confiance.',
 '2-3 séances', 'Avancé',
 array['Rossi', 'Cheek', 'Idéomoteurs', 'Voyage mental'],
 '#2E8A7B', 3,
 array['Préparation chirurgicale', 'Cicatrisation'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(623, 'Approche ericksonienne — Salle d''urgence & préparation (Rodger)', 'Hypnoanesthésie & chirurgie', 'Hypnose Ericksonienne',
 'Truismes, démonstrations physiques (poing/poupée de chiffon), structuration des attentes (analgésie = rhéostat), panique en travail (paradoxal), globe de Boston, non-douleur.',
 '1-2 séances', 'Avancé',
 array['Rodger', 'Ericksonien', 'Urgence', 'Soliloque', 'Globe Boston'],
 '#2E8A7B', 2,
 array['Urgence', 'Patient résistant', 'Accouchement panique', 'Cancer'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress', 'Phobies & peurs']),

(624, 'Suggestions préopératoires en 7 points (Barber)', 'Hypnoanesthésie & chirurgie', 'Hypnose médicale',
 'Liste opérationnelle : sommeil veille, calme matinal, rêverie, confort sommeil anesthésique, rêvasserie post-réveil, respirations/mictions/saignement, surprise infirmières.',
 '1 séance', 'Intermédiaire',
 array['Barber', 'Préopératoire', 'Suggestions courtes'],
 '#2E8A7B', 1,
 array['Préparation chirurgicale'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(625, 'Préparation chirurgie — Cassette autohypnose (Sylvester)', 'Hypnoanesthésie & chirurgie', 'Hypnose médicale',
 'Enregistrable. Fixation visuelle, fixation des bruits hospitaliers, confiance dans le système nerveux autonome, guérison inconsciente. Travail à plein temps les jours suivants.',
 '1 séance + autohypnose', 'Intermédiaire',
 array['Sylvester', 'Cassette', 'Système nerveux autonome'],
 '#2E8A7B', 1,
 array['Préparation chirurgicale', 'Autohypnose'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(626, 'Éteindre les sens — 9 points avec emphases (Rodger)', 'Hypnoanesthésie & chirurgie', 'Hypnose médicale',
 'Fermeture sensorielle, lourdeur du bras dominant, indifférence aux sensations, thermostat personnel, auto-réveil « réveille-toi » synchronisé sur la respiration.',
 '1 séance', 'Intermédiaire',
 array['Rodger', 'Fermeture sensorielle', 'Auto-réveil'],
 '#2E8A7B', 1,
 array['Préparation chirurgicale'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(627, 'Induction rapide d''analgésie — Escalier 20 marches (Barber)', 'Hypnoanesthésie & chirurgie', 'Hypnose médicale',
 'Induction par escalier descendant 20 marches synchronisé sur l''expiration. Ancrage post-hypnotique épaule droite. Amnésie tissée. Réveil par escalier remontant.',
 '1 séance', 'Intermédiaire',
 array['Barber', 'Escalier', 'Ancrage épaule droite', 'Amnésie tissée'],
 '#2E8A7B', 1,
 array['Induction rapide', 'Analgésie'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(628, 'Postopératoire — Réchauffement par lampe (Hammond)', 'Hypnoanesthésie & chirurgie', 'Hypnose médicale',
 'Suggestion brève en salle de réveil avec lampe chauffante réelle. Métaphores de chaleur familières (blotti dans le lit, bain chaud).',
 '1 séance brève', 'Débutant',
 array['Hammond', 'Postopératoire', 'Réchauffement'],
 '#2E8A7B', 1,
 array['Salle de réveil', 'Chirurgie thoracique/abdominale'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(629, 'Analgésie chirurgicale & obstétricale — Lac imaginaire (Rossi & Cheek)', 'Hypnoanesthésie & chirurgie', 'Hypnose médicale',
 'Lac froid imaginaire à hauteur croissante. Geste pouce-index gauche = engourdissement, droit = restauration. Recadrage accouchement = scier du bois.',
 '1-2 séances', 'Intermédiaire',
 array['Rossi', 'Cheek', 'Lac froid', 'Geste pouce-index'],
 '#2E8A7B', 2,
 array['Préparation chirurgicale', 'Accouchement'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(630, 'Répétition en chirurgie — Simulation détaillée (Kroger)', 'Hypnoanesthésie & chirurgie', 'Hypnose médicale',
 'Simulation par étapes (alcool, crayon-incision, écartement, bruit de pince). Catalepsie cutanée + glaçon pour saignement. Ancrage épaule droite pour postopératoire.',
 '2 séances', 'Avancé',
 array['Kroger', 'Répétition chirurgicale', 'Catalepsie cutanée'],
 '#2E8A7B', 2,
 array['Hypnoanesthésie', 'Chirurgie'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(631, 'Aiguilles & interventions brèves (Bartlett)', 'Hypnoanesthésie & chirurgie', 'Hypnose médicale',
 'Suggestion brève intégrée au geste réel : antiseptique froid « emporte les sensations » + chiquenaudes + insertion rapide. Idéal prises de sang.',
 '1 séance brève', 'Débutant',
 array['Bartlett', 'Aiguille', 'Prise de sang'],
 '#2E8A7B', 1,
 array['Prise de sang', 'Ponction', 'Cerballiance'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

-- ========================================================
-- CH-DOUL — Douleur (41 protocoles, IDs 632-672)
-- ========================================================
(632, 'Cadre des 4 méthodes de contrôle hypnotique (Barber)', 'Hypnose - Douleur', 'Hypnose médicale',
 'Cadre théorique : analgésie/anesthésie suggérée, substitution sensorielle, déplacement, dissociation. Évaluation 0-10. Préfère suggérer le confort plutôt que la diminution.',
 'Cadre théorique', 'Intermédiaire',
 array['Barber', 'Cadre théorique', 'Échelle de douleur'],
 '#B85450', 1,
 array['Douleur aiguë', 'Douleur chronique'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(633, 'Chiffres décroissants pour créer le confort (Barber)', 'Hypnose - Douleur', 'Hypnose médicale',
 'Transformation graphique progressive du chiffre de douleur (8→7→6...). Métaphore du cygne. Permissivité radicale, jamais de 0 absolu.',
 '1 séance + autohypnose', 'Intermédiaire',
 array['Barber', 'Échelle de douleur', 'Cygne'],
 '#B85450', 1,
 array['Douleur chronique'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(634, 'Dissociation pour douleur chronique résistante (Barber)', 'Hypnose - Douleur', 'Hypnose médicale',
 'Stratégie paradoxale subtile : découplage radical entre séance et effets, disqualification préventive, confusion temporelle, sortie du thérapeute.',
 '1 séance', 'Avancé',
 array['Barber', 'Patient résistant', 'Permissivité radicale'],
 '#B85450', 1,
 array['Douleur chronique résistante'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(635, 'Modifier la douleur — Rembourrage de coton (Wright)', 'Hypnose - Douleur', 'Hypnose médicale',
 'Couches épaisses de coton qui transforment l''agression (couteau pointu) en pression sourde. Épaisseur ajustable par le patient. Énergie économisée pour la guérison.',
 '1-2 séances', 'Intermédiaire',
 array['Wright', 'Métaphore concrète', 'Rembourrage'],
 '#B85450', 2,
 array['Douleur aiguë', 'Douleur lancinante'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(636, 'Transformation — Déplacement & changement de qualité (Golden, Dowd, Friedberg)', 'Hypnose - Douleur', 'Hypnose médicale',
 'Choix collaboratif de la nouvelle zone (gros orteil, lobe d''oreille). Transfert physique par le toucher. Variante : transformation en chaleur, démangeaison, picotement.',
 '1-2 séances', 'Intermédiaire',
 array['Déplacement', 'Transformation sensorielle', 'Toucher'],
 '#B85450', 2,
 array['Lombalgie', 'Céphalée', 'Douleur chronique'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(637, 'Truismes ericksoniens pour anesthésies (Erickson)', 'Hypnose - Douleur', 'Hypnose Ericksonienne',
 'Convocation d''anesthésies naturelles quotidiennes (chaussures, lunettes, collier, conférence ennuyeuse). Recadrage : couper et rétablir des sensations est une aptitude apprise.',
 '1 module bref', 'Débutant',
 array['Erickson', 'Truisme', 'Anesthésie naturelle'],
 '#B85450', 1,
 array['Préparation à l''analgésie'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(638, 'Saupoudrage — Plant de tomate (cas Joe, Erickson)', 'Hypnose - Douleur', 'Hypnose Ericksonienne',
 'Insertion de termes thérapeutiques (confort, paix, croissance) dans un récit de plant de tomate. Pour patient résistant ou cancéreux non-communicant. Demande virtuosité.',
 '1 séance longue', 'Avancé',
 array['Erickson', 'Saupoudrage', 'Cancer', 'Patient résistant'],
 '#B85450', 1,
 array['Douleur cancéreuse', 'Patient résistant'],
 'Hammond 1990 (ASCH)', array['Trauma & deuil']),

(639, 'Fragmentation en composantes sensorielles (Erickson)', 'Hypnose - Douleur', 'Hypnose Ericksonienne',
 'Décomposer l''expérience globale en sensations distinctes (brûlante, lourde, coupante). Le patient choisit quelle composante traiter. La fragmentation elle-même réduit l''intensité.',
 '1 module', 'Intermédiaire',
 array['Erickson', 'Fragmentation', 'Décomposition'],
 '#B85450', 1,
 array['Douleur composite', 'Douleur cancéreuse'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(640, 'Déplacement douleur cancéreuse vers la main (Erickson)', 'Hypnose - Douleur', 'Hypnose Ericksonienne',
 'Apprendre à la douleur de se déplacer du torse menaçant vers la main neutre — où elle peut être ressentie « avec joie » car elle a perdu son caractère menaçant.',
 '1 module', 'Avancé',
 array['Erickson', 'Cancer', 'Recadrage existentiel'],
 '#B85450', 1,
 array['Douleur cancéreuse'],
 'Hammond 1990 (ASCH)', array['Trauma & deuil']),

(641, 'Amnésie — Cinéma absorbant (Erickson)', 'Hypnose - Douleur', 'Hypnose Ericksonienne',
 'Métaphore brève : l''absorption dans le suspense d''un film fait oublier le mal de tête. Amnésie différée possible (« trois jours pour vous souvenir »).',
 '1 module bref', 'Débutant',
 array['Erickson', 'Absorption', 'Cinéma'],
 '#B85450', 1,
 array['Céphalée'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(642, 'Diminution progressive par pourcentages (Erickson)', 'Hypnose - Douleur', 'Hypnose Ericksonienne',
 'Décomposition arithmétique : la perte d''1 % ne se remarque pas. Stratégie de négociation par paliers (75 % puis 80 % puis 85 %). Préserver toujours un résiduel.',
 '1 module', 'Intermédiaire',
 array['Erickson', 'Pourcentages', 'Négociation'],
 '#B85450', 1,
 array['Patient résistant'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(643, 'Désorientation & confusion (Erickson)', 'Hypnose - Douleur', 'Hypnose Ericksonienne',
 'Confusion délibérée sur la latéralité (droite/gauche, externe/interne). Une fois désorienté, déplacer la douleur vers une zone sans cause organique pour anesthésier facilement.',
 '1 module', 'Avancé',
 array['Erickson', 'Confusion', 'Désorientation'],
 '#B85450', 1,
 array['Patient résistant'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(644, 'Métaphore neurosynaptique — Étincelles (Erickson)', 'Hypnose - Douleur', 'Hypnose Ericksonienne',
 'Pour patient logique : neurosynapses qui transmettent la douleur comme étincelles électriques. L''hypnose écarte les synapses pour qu''il ne saute plus.',
 '1 module bref', 'Intermédiaire',
 array['Erickson', 'Métaphore neurophysiologique'],
 '#B85450', 1,
 array['Patient cartésien', 'Douleur organique'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(645, 'Principes pour douleur persistante — 10 étapes (Rossi & Cheek)', 'Hypnose - Douleur', 'Hypnose médicale',
 'Structure complète d''entretien initial : signaux idéomoteurs, exploration des origines, mot-signal d''arrêt, pseudo-orientation dans l''avenir, autohypnose 3 min × 4/jour.',
 '1ère séance + suivi', 'Avancé',
 array['Rossi', 'Cheek', 'Idéomoteurs', '10 étapes'],
 '#B85450', 4,
 array['Douleur chronique'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(646, 'Imagerie religieuse de guérison universelle (Wright)', 'Hypnose - Douleur', 'Hypnose médicale',
 'Travail sur le pardon de soi et des autres. Esprit universel de guérison qui libère les tensions. Énergie de la colère libérée pour la guérison. Adaptable laïquement.',
 '1-2 séances', 'Intermédiaire',
 array['Wright', 'Pardon', 'Spiritualité', 'PNI'],
 '#B85450', 2,
 array['Douleur chronique avec ressentiment'],
 'Hammond 1990 (ASCH)', array['Trauma & deuil']),

(647, 'Oreille compatissante pour bénéfices secondaires (Fogel)', 'Hypnose - Douleur', 'Hypnose médicale',
 'Substitut hypnotique aux bénéfices interpersonnels : auditeur intérieur compatissant, attentif, sans fatigue ni jugement. Pratique quotidienne en autohypnose.',
 '1 séance + autohypnose', 'Intermédiaire',
 array['Fogel', 'Bénéfices secondaires', 'Auditeur intérieur'],
 '#B85450', 1,
 array['Douleur chronique avec bénéfices secondaires'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(648, 'Réactivation de souvenirs libres de douleur (Wright)', 'Hypnose - Douleur', 'Hypnose médicale',
 'Trois phases : régression vers période sans douleur, intensification contrôlée pour démontrer le contrôle, apaisement. Dissociation observateur-participant.',
 '2-3 séances', 'Avancé',
 array['Wright', 'Régression en âge', 'Intensification contrôlée'],
 '#B85450', 3,
 array['Douleur chronique'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(649, 'Cadre relationnel & anesthésie en gant (Garver)', 'Hypnose - Douleur', 'Hypnose médicale',
 'Validation explicite de la douleur. Recadrage de la déclaration médicale comme suggestion négative. Cycle douleur-tension expliqué. Démonstration : c''est le patient qui produit l''effet.',
 '1ère séance', 'Intermédiaire',
 array['Garver', 'Validation', 'Anesthésie en gant'],
 '#B85450', 1,
 array['Douleur chronique'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(650, 'Théorie du portillon — Visualisation (Garver)', 'Hypnose - Douleur', 'Hypnose médicale',
 'Métaphore neurologique compatible Melzack-Wall : portillons qui se ferment, zone de réception comme pièce avec rhéostat. Couplage échelle 0-10. Distorsion temps + dissociation.',
 '1-2 séances', 'Intermédiaire',
 array['Garver', 'Portillon', 'Rhéostat', 'Distorsion temps'],
 '#B85450', 2,
 array['Douleur chronique'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(651, 'Métaphore informatique — Reprogrammation (Garver)', 'Hypnose - Douleur', 'Hypnose médicale',
 'Double signal post-hypnotique : oreille droite = programmer confort, épaule gauche = déprogrammer douleur. Préservation du signal protecteur. Triple signal pour cancer/chimio.',
 '1-2 séances', 'Intermédiaire',
 array['Garver', 'Informatique', 'Signaux post-hypnotiques'],
 '#B85450', 2,
 array['Douleur chronique', 'Chimiothérapie', 'Migraine'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(652, 'États mystiques — Introversion / Extraversion (Sacerdote)', 'Hypnose - Douleur', 'Hypnose médicale',
 'Avancé. Sphères concentriques ou montée de montagne avec vue panoramique multisensorielle. Pour cancer en stade avancé, douleurs réfractaires. Préparation préalable indispensable.',
 '1 séance longue', 'Avancé',
 array['Sacerdote', 'États mystiques', 'Cancer'],
 '#B85450', 1,
 array['Douleur cancéreuse', 'Phase terminale'],
 'Hammond 1990 (ASCH)', array['Trauma & deuil']),

(653, 'Stratégies selon hypnotisabilité (Spiegel & Spiegel)', 'Hypnose - Douleur', 'Hypnose médicale',
 'Adaptation au profil HIP : élevée → engourdissement direct, flottement ; moyenne → modification de température, transfert d''anesthésie dentaire ; faible → distraction.',
 'Cadre orientateur', 'Intermédiaire',
 array['Spiegel', 'HIP', 'Stratégie adaptative'],
 '#B85450', 1,
 array['Douleur'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(654, 'Voyant rouge — Recadrage protecteur (Mutter)', 'Hypnose - Douleur', 'Hypnose médicale',
 'Métaphore mécanique : voyant rouge sur tableau de bord d''une voiture qui chauffe. Recadrer la douleur comme signal protecteur, pas comme processus invalidant.',
 '1 module bref', 'Débutant',
 array['Mutter', 'Métaphore mécanique', 'Voiture'],
 '#B85450', 1,
 array['Recadrage de la douleur'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(655, 'Attelle hypnotique pour musculo-squelettique (Mutter)', 'Hypnose - Douleur', 'Hypnose médicale',
 'L''inconscient limite automatiquement les mouvements aux limites des aptitudes physiques. Évite la rechute par sur-utilisation après amélioration.',
 '1 séance', 'Intermédiaire',
 array['Mutter', 'Lombalgie', 'Inconscient protecteur'],
 '#B85450', 1,
 array['Lombalgie chronique', 'Prévention rechute'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(656, 'Coucher du soleil (Levitan)', 'Hypnose - Douleur', 'Hypnose médicale',
 'Pour douleur décrite comme sphère rouge flamboyante. Plage tropicale, transformation visuelle progressive du rouge. Ancrage geste pouce-index « OK magique ».',
 '1 séance', 'Débutant',
 array['Levitan', 'Coucher de soleil', 'Ancrage OK'],
 '#B85450', 1,
 array['Douleur rouge', 'Migraine'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(657, 'Nourriture mexicaine — Callosités (Hammond)', 'Hypnose - Douleur', 'Hypnose Ericksonienne',
 'Récit autobiographique d''adaptation au piment. Permettre aux nerfs de la douleur de développer des callosités tout en restant sensible aux saveurs.',
 '1 module bref', 'Débutant',
 array['Hammond', 'Callosités', 'Récit autobiographique'],
 '#B85450', 1,
 array['Douleur chronique'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(658, 'Métaphore du golf — Callosités progressives (Hammond)', 'Hypnose - Douleur', 'Hypnose Ericksonienne',
 'Variante sportive : pratique régulière → callosités, pratique massive → ampoules. Adaptation progressive du corps. Idéal athlètes.',
 '1 module bref', 'Débutant',
 array['Hammond', 'Golf', 'Callosités'],
 '#B85450', 1,
 array['Douleur chronique', 'Sportifs'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(659, 'Suggestions positives & beurre qui fond (Fredericks)', 'Hypnose - Douleur', 'Hypnose médicale',
 'Métaphore du voilier (à la barre de sa vie). Soleil qui pénètre, beurre/crème qui fond emportant l''inconfort. Carrefour des chemins (droite = confort).',
 '1 séance + autohypnose', 'Intermédiaire',
 array['Fredericks', 'Voilier', 'Beurre'],
 '#B85450', 1,
 array['Douleur chronique'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(660, 'Bibliothèque respiratoire antalgique (Jencks)', 'Hypnose - Douleur', 'Hypnose médicale',
 'Sous-techniques par type : sourde (bouillotte), aiguë (mousse), brûlante (lotion froide), crampes, céphalées (« ouvrir la tête »), thoracique (fleur, entonnoir, ascenseur).',
 '1 séance + autohypnose', 'Intermédiaire',
 array['Jencks', 'Respiration', 'Bibliothèque'],
 '#B85450', 1,
 array['Douleurs sourdes', 'Aiguës', 'Céphalées', 'Crampes', 'Rhumatismales'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(661, 'Lumières du corps — Polyarthrite (Rossi & Cheek)', 'Hypnose - Douleur', 'Hypnose médicale',
 'Symptômes convertis en lampes colorées devant un miroir. Commencer par les zones les moins douloureuses. Régression vers le moment d''apparition. Question pivot.',
 '2-3 séances', 'Avancé',
 array['Rossi', 'Cheek', 'Polyarthrite', 'Régression'],
 '#B85450', 3,
 array['Polyarthrite rhumatoïde', 'Inflammations articulaires'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(662, 'Zona — Personnalisation & placard (Stoler)', 'Hypnose - Douleur', 'Hypnose médicale',
 'Signal pouce-index + respiration profonde. Placard à dossiers fermé à clé pour sentiments négatifs (préservation du choix conscient de récupération). Recadrage corps-esprit.',
 '1 séance + autohypnose', 'Intermédiaire',
 array['Stoler', 'Zona', 'Placard', 'Personnalisation'],
 '#B85450', 1,
 array['Douleur post-zostérienne', 'Patient âgé'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(663, 'Zona — Cadrans & immunité (Stoler)', 'Hypnose - Douleur', 'Hypnose médicale',
 'Activation imaginaire des mécanismes antiviraux. Cadrans de réglage avec contrôle de volume. Niveau confort = pression sans douleur. Préservation du signal d''alerte.',
 '1 séance + autohypnose', 'Intermédiaire',
 array['Stoler', 'Cadrans', 'Activation immunitaire'],
 '#B85450', 1,
 array['Douleur post-zostérienne'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(664, 'Hémorroïdectomie — Catalepsie & gant (Werbel)', 'Hypnose - Douleur', 'Hypnose médicale',
 'Étude : 8/11 sans douleur post-op vs 2/11 témoin. Ratification par catalepsie + anesthésie en gant. Suggestion ciblée première selle.',
 '1 séance pré + 1 post', 'Intermédiaire',
 array['Werbel', 'Hémorroïdectomie', 'Catalepsie'],
 '#B85450', 2,
 array['Post-opératoire'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(665, 'Soulagement avec douleur signal préservée (Gibbons)', 'Hypnose - Douleur', 'Hypnose médicale',
 'Suggestion brève de fin de transe : il restera un léger inconfort pour rappeler de se ménager. Le reste de la douleur, celle qui ne sert à rien, disparaît.',
 '1 module bref', 'Débutant',
 array['Gibbons', 'Convalescence', 'Préservation protectrice'],
 '#B85450', 1,
 array['Convalescence'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(666, 'Migraines — Dauphin & réflexe de plongée (Gibbons)', 'Hypnose - Douleur', 'Hypnose médicale',
 'Activation du réflexe de plongée des mammifères : ralentissement cardiaque, réduction congestion céphalique. Linge d''eau froide en renfort. Mot-clé « plongée ».',
 '1 séance + autohypnose', 'Intermédiaire',
 array['Gibbons', 'Migraine', 'Dauphin', 'Plongée'],
 '#B85450', 1,
 array['Migraine', 'Céphalée'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(667, 'Distorsion du temps — Convalescence (Gibbons)', 'Hypnose - Douleur', 'Hypnose médicale',
 'Les jours/heures semblent passer rapidement, performance normale maintenue. Limitation temporelle explicite obligatoire (date de fin). Ne pas utiliser pour éviter d''affronter.',
 '1 séance', 'Intermédiaire',
 array['Gibbons', 'Distorsion du temps', 'Convalescence'],
 '#B85450', 1,
 array['Convalescence prolongée'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(668, 'Migraines — Vent glacé & bain chaud (Fredericks)', 'Hypnose - Douleur', 'Hypnose médicale',
 'Différentiel thermique : tempes froides (neige, glaçon) sur corps chaud (bain). Tête plus claire, congestion qui disparaît. Ne JAMAIS dire « vivre avec la douleur ».',
 '1 séance + autohypnose', 'Intermédiaire',
 array['Fredericks', 'Migraine', 'Différentiel thermique'],
 '#B85450', 1,
 array['Migraine'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(669, 'Migraines — Visualisation des artères (Andersen, Basker, Dalton)', 'Hypnose - Douleur', 'Hypnose médicale',
 'Étude : 10/23 rémission complète vs 3/24. Visualisation directe des artères congestionnées qui deviennent plus petites, plus normales avec la relaxation.',
 '1 séance + autohypnose', 'Intermédiaire',
 array['Andersen', 'Migraine', 'Visualisation anatomique'],
 '#B85450', 1,
 array['Migraine'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(670, 'Diminution avec symptôme conservé (Secter)', 'Hypnose - Douleur', 'Hypnose Ericksonienne',
 'Approche paradoxale : conserver la céphalée mais la déplacer au moment du coucher où la respiration profonde déclenche son estompement et le sommeil.',
 '1 séance', 'Intermédiaire',
 array['Secter', 'Approche paradoxale', 'Céphalée'],
 '#B85450', 1,
 array['Céphalée chronique'],
 'Hammond 1990 (ASCH)', array['Sommeil & insomnie']),

(671, 'Substitution de symptôme (Elkins)', 'Hypnose - Douleur', 'Hypnose médicale',
 'Module bref permissif : « quand vous êtes prêt, vous pouvez avoir un autre symptôme pour remplacer la douleur ». Pont vers travail sur bénéfices secondaires.',
 '1 module bref', 'Intermédiaire',
 array['Elkins', 'Substitution', 'Permissivité'],
 '#B85450', 1,
 array['Douleur chronique'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(672, 'Anesthésie progressive en induction (Hammond, dérivé Watkins)', 'Hypnose - Douleur', 'Hypnose médicale',
 'Anesthésie qui se diffuse main → bras → tronc → jambes → tête par toucher progressif. Option « réveil au-dessus du cou » : le corps reste en transe anesthésiée.',
 '1 séance longue', 'Avancé',
 array['Hammond', 'Watkins', 'Anesthésie progressive', 'Réveil partiel'],
 '#B85450', 1,
 array['Préparation chirurgicale', 'Cancer', 'Brûlures'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

-- ========================================================
-- CH-ANX — Anxiété & stress (14 protocoles, IDs 673-686)
-- ========================================================
(673, 'Induction & approfondissement par relaxation progressive (Hammond)', 'Anxiété & stress', 'Hypnose médicale',
 'Scan corporel ascendant pieds → tête. Métaphore « chaussures trop serrées ». Synchronisation suggestions/respiration. Signaux idéomoteurs aux étapes clés.',
 '1 séance', 'Débutant',
 array['Hammond', 'Relaxation progressive', 'Induction'],
 '#C8A030', 1,
 array['Anxiété', 'Induction'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(674, 'Écran imaginaire pour résolution (Spiegel & Spiegel)', 'Anxiété & stress', 'Hypnose médicale',
 'Flottaison physique + écran mental segmenté : centre = problème, gauche = visualisation détaillée, droit = écran de résolution.',
 '1 séance + autohypnose', 'Intermédiaire',
 array['Spiegel', 'Écran mental', 'Dissociation'],
 '#C8A030', 1,
 array['Anxiété cognitive', 'Rumination'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(675, 'Refuge privé — Descente d''immeuble (Finkelstein)', 'Anxiété & stress', 'Hypnose médicale',
 'Approfondissement par descente d''immeuble (3 choix : ascenseur, escalier mécanique, grand escalier). Doublement de la relaxation à chaque étage. Lieu refuge entièrement contrôlable.',
 '1 séance', 'Débutant',
 array['Finkelstein', 'Lieu refuge', 'Ascenseur'],
 '#C8A030', 1,
 array['Anxiété', 'Lieu sûr'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(676, 'Trois scènes — Étang, Nuage, Jardin (Stanton)', 'Anxiété & stress', 'Hypnose médicale',
 'Trois imageries interchangeables : rocher dans l''étang qui s''apaise, nuage chaud enveloppant, dix marches vers un jardin multisensoriel.',
 '1 séance + autohypnose', 'Débutant',
 array['Stanton', 'Imagerie', 'Multisensoriel'],
 '#C8A030', 1,
 array['Anxiété', 'Relaxation'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(677, 'Île de la sérénité — Refuge inviolable (Stickney)', 'Anxiété & stress', 'Hypnose médicale',
 'Voyage symbolique vers une île intérieure (avion, bateau, nage). Sécurité absolue qui permet de baisser les défenses et autoriser l''émergence des sentiments.',
 '1 séance', 'Débutant',
 array['Stickney', 'Île', 'Inviolabilité'],
 '#C8A030', 1,
 array['Anxiété', 'Envahissement social'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(678, 'Transe méditative non-verbale (Meares)', 'Anxiété & stress', 'Hypnose médicale',
 'Approche radicale : sons non-verbaux « Ah, Humm », toucher ferme, posture progressivement inconfortable. Pour cancer, anxiété, syndrome prémenstruel. Cadre clinique solide requis.',
 '1/jour pendant 1 mois', 'Avancé',
 array['Meares', 'Méditation', 'Non-verbal', 'Cancer'],
 '#C8A030', 30,
 array['Anxiété profonde', 'Cancer', 'Syndrome prémenstruel'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(679, 'Méthodes respiratoires multiples (Jencks)', 'Anxiété & stress', 'Hypnose médicale',
 'Bibliothèque de 12 techniques : pierre dans le puits, soufflet, balançoire, vagues, médicament imaginaire, respirer par la peau, relâchement Alexander.',
 '1 séance + autohypnose', 'Débutant',
 array['Jencks', 'Respiration', 'Imagerie'],
 '#C8A030', 1,
 array['Anxiété', 'Stress', 'Approfondissement'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(680, 'Poupée de chiffon autogène (Jencks)', 'Anxiété & stress', 'Hypnose médicale',
 'Adaptation Schultz par images : bras retombe comme poupée de chiffon, sac de billes, ours en peluche. Synchronisation avec l''expiration.',
 '1 séance + autohypnose', 'Débutant',
 array['Jencks', 'Training autogène', 'Schultz'],
 '#C8A030', 1,
 array['Anxiété', 'Enfants', 'Préparation accouchement'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(681, 'Métaphore-recadrage pour démarrer le travail (Gurgevich)', 'Anxiété & stress', 'Hypnose médicale',
 'Pivot entre induction et travail thérapeutique. Métaphore de la lentille : chaque instant est une lentille à travers laquelle on voit le monde. Choix du cadre.',
 '1 module', 'Intermédiaire',
 array['Gurgevich', 'Lentille', 'Recadrage'],
 '#C8A030', 1,
 array['Travail sur les affects'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(682, 'RET hypnotique — Croyances irrationnelles (Ellis)', 'Anxiété & stress', 'Hypnose médicale',
 'Identification des « je dois » comme source autoproduite. Distinction radicale désirer/exiger. « Rien n''est horrible ». Style autoritaire. Cassette quotidienne 30 jours.',
 '1 séance + 30 jours cassette', 'Intermédiaire',
 array['Ellis', 'RET', 'TCC', 'Catastrophisme'],
 '#C8A030', 30,
 array['Anxiété', 'Catastrophisme'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(683, 'Transe naturaliste ericksonienne (Field)', 'Anxiété & stress', 'Hypnose Ericksonienne',
 'Permissivité radicale, dissociation conscient/inconscient, exploration des armoires à dossiers, découverte de ressources insoupçonnées, atmosphère lumineuse.',
 '1 séance longue', 'Avancé',
 array['Field', 'Ericksonien', 'Permissif'],
 '#C8A030', 1,
 array['Stress', 'Anxiété'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(684, 'Tiroir fermé pour stocker le stress (Alman)', 'Anxiété & stress', 'Hypnose médicale',
 'Outil ultra-pragmatique : tiroir physique réel au bureau. Geste rituel : papier + 2 respirations + dépôt + fermeture. Nettoyage hebdomadaire.',
 '1 séance + pratique quotidienne', 'Débutant',
 array['Alman', 'Tiroir', 'Stress professionnel'],
 '#C8A030', 1,
 array['Stress professionnel', 'Céphalée de tension'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(685, 'Occasion manquée — Ambivalence (Yapko)', 'Anxiété & stress', 'Hypnose Ericksonienne',
 'Métaphore narrative : un homme paralysé par l''hésitation perd un poste donné à plus enthousiaste. Examiner ce qu''on perd à rester bloqué. Un jour à la fois.',
 '1 module', 'Intermédiaire',
 array['Yapko', 'Ambivalence', 'Décision'],
 '#C8A030', 1,
 array['Paralysie décisionnelle', 'Dépression légère'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

(686, 'Désamorcer la panique — Inversion symptomatique (Hunter)', 'Anxiété & stress', 'Hypnose médicale',
 'Transe interactive. Mise en scène contrôlée de la panique. Reconnaissance du complexe symptomatique personnel. Inversion séquentielle commençant par la respiration.',
 '1-2 séances', 'Avancé',
 array['Hunter', 'Panique', 'Transe interactive', 'Sparadrap'],
 '#C8A030', 2,
 array['Attaque de panique'],
 'Hammond 1990 (ASCH)', array['Anxiété & stress']),

-- ========================================================
-- CH-PHOB — Phobies (6 protocoles, IDs 687-692)
-- ========================================================
(687, 'Phobie de l''avion — Paradigme Spiegel', 'Phobies', 'Hypnose médicale',
 'Trois points : avion = extension du corps, flotter avec l''avion, distinguer probabilité vs possibilité. Autohypnose avant et pendant le vol.',
 '1 séance', 'Intermédiaire',
 array['Spiegel', 'Avion', 'Dissociation'],
 '#E08550', 1,
 array['Phobie de l''avion'],
 'Hammond 1990 (ASCH)', array['Phobies & peurs']),

(688, 'Phobie avion — Recadrage vocabulaire (Bakal)', 'Phobies', 'Hypnose médicale',
 'Mise au jour des suggestions négatives (terminal, dernier appel, destination finale). Recadrage : turbulences = route cahoteuse, descente = voiture en côte. 21 patients suivis 3 ans.',
 '3 séances', 'Intermédiaire',
 array['Bakal', 'Avion', 'Recadrage vocabulaire'],
 '#E08550', 3,
 array['Phobie de l''avion'],
 'Hammond 1990 (ASCH)', array['Phobies & peurs']),

(689, 'Désensibilisation systématique en transe — Avion (Gibbons)', 'Phobies', 'Hypnose médicale',
 'Imagerie guidée du voyage complet, étape par étape. Livre passionnant comme ancrage attentionnel. Décollage à peine remarqué, atterrissage surprise.',
 '1-2 séances', 'Débutant',
 array['Gibbons', 'Désensibilisation', 'Avion', 'Livre'],
 '#E08550', 2,
 array['Phobie de l''avion'],
 'Hammond 1990 (ASCH)', array['Phobies & peurs']),

(690, 'Désensibilisation & fractionnement (Haberman)', 'Phobies', 'Hypnose médicale',
 'Hiérarchie graduée + fractionnement (entrer/sortir de transe). Signal idéomoteur dès anxiété → arrêt scène, stimulus neutre, approfondissement, reprise. Transition vers in vivo.',
 '3-5 séances', 'Intermédiaire',
 array['Haberman', 'Hiérarchie d''anxiété', 'Fractionnement', 'In vivo'],
 '#E08550', 4,
 array['Phobies simples', 'Phobies sociales'],
 'Hammond 1990 (ASCH)', array['Phobies & peurs']),

(691, 'Manque de confiance & trac (Waxman)', 'Phobies', 'Hypnose médicale',
 'Renforcement du moi + suggestions de rencontre des autres « sur un pied d''égalité ». Absorption complète dans le contenu du discours. Désensibilisation graduelle.',
 '2-3 séances', 'Débutant',
 array['Waxman', 'Trac', 'Prise de parole'],
 '#E08550', 3,
 array['Confiance en soi', 'Trac', 'Prise de parole'],
 'Hammond 1990 (ASCH)', array['Estime & confiance en soi']),

(692, 'Peur de parler en public — Décharge préalable (Gibbons)', 'Phobies', 'Hypnose médicale',
 'Décharge émotionnelle anticipée par expression libre. Métaphore de la soupape de sûreté. Recadrage anxiété résiduelle = vivacité utile à la performance.',
 '1 séance avant chaque échéance', 'Intermédiaire',
 array['Gibbons', 'Décharge émotionnelle', 'Performance'],
 '#E08550', 1,
 array['Trac', 'Prise de parole'],
 'Hammond 1990 (ASCH)', array['Estime & confiance en soi']),

-- ========================================================
-- CH-SPORT — Performances sportives (8 protocoles, IDs 693-700)
-- ========================================================
(693, 'Cadre général performance sportive (Henschen)', 'Performance sportive', 'Hypnose sportive',
 'Imagerie mentale + sensation kinesthésique simultanée. Suggestion post-hypnotique. Construction d''une « salle du bonheur » mentale avec poste TV et auto-visualisation.',
 'Variable', 'Intermédiaire',
 array['Henschen', 'Imagerie mentale', 'Salle du bonheur'],
 '#7C5CBF', 1,
 array['Performance sportive', 'Concentration', 'Confiance'],
 'Hammond 1990 (ASCH)', array['Estime & confiance en soi']),

(694, 'Contrôle stimulation & facilitation neuro-motrice (Garver)', 'Performance sportive', 'Hypnose sportive',
 'Triple modalité d''imagerie (externe dissociée, interne 1ère personne, kinesthésique). Double signal post-hypnotique : épaule droite = correct, épaule gauche = à corriger.',
 '2-3 séances', 'Intermédiaire',
 array['Garver', 'Imagerie 3 angles', 'Signaux post-hypnotiques'],
 '#7C5CBF', 3,
 array['Geste technique', 'Golf', 'Tennis', 'Gymnastique'],
 'Hammond 1990 (ASCH)', array['Estime & confiance en soi']),

(695, 'Métaphore du sprinter — Lenteur de démarrage (Wooton)', 'Performance sportive', 'Hypnose Ericksonienne',
 'Récit du sprinter junior talentueux qui perd faute de savoir partir des starting-blocks. Volet 2 : Van Gogh et conséquences de la colère après erreur.',
 '1 séance d''équipe', 'Débutant',
 array['Wooton', 'Sprinter', 'Équipe', 'Van Gogh'],
 '#7C5CBF', 1,
 array['Lenteur de démarrage', 'Gestion colère'],
 'Hammond 1990 (ASCH)', array['Estime & confiance en soi']),

(696, 'Parachutisme — Coopération d''équipe (Wooton)', 'Performance sportive', 'Hypnose Ericksonienne',
 'Métaphore de l''étoile à six branches : si UN seul rate sa réaction, l''étoile entière échoue et chacun atterrit seul. Activation de la dépendance interpersonnelle saine.',
 '1 séance d''équipe', 'Débutant',
 array['Wooton', 'Équipe', 'Parachutisme', 'Cohésion'],
 '#7C5CBF', 1,
 array['Esprit d''équipe', 'Cohésion'],
 'Hammond 1990 (ASCH)', array['Estime & confiance en soi']),

(697, 'Concentration par ancrage situationnel (Alman)', 'Performance sportive', 'Hypnose sportive',
 'Lacer chaussures = resserrement attention. Filet du tennis = filtrage distractions. Lignes du terrain = limites mentales. Pilotage automatique pour revenir au match.',
 '1 séance + autohypnose', 'Débutant',
 array['Alman', 'Concentration', 'Rituel pré-match'],
 '#7C5CBF', 1,
 array['Concentration', 'Rituel'],
 'Hammond 1990 (ASCH)', array['Estime & confiance en soi']),

(698, 'Cognitivo-hypnotique haltérophilie (Howard & Reardon)', 'Performance sportive', 'Hypnose sportive',
 'Restructuration cognitive (Tosi/Ellis) + imagerie physiologique (serviettes chaudes, gonflement). Échelle d''arousal 1-5. Étude expérimentale contrôlée publiée 1986.',
 '4-6 séances', 'Avancé',
 array['Howard', 'Reardon', 'Haltérophilie', 'TCC'],
 '#7C5CBF', 5,
 array['Sports de force', 'Haltérophilie', 'Powerlifting'],
 'Hammond 1990 (ASCH)', array['Estime & confiance en soi']),

(699, 'Performance & résilience face à l''échec (Gibbons)', 'Performance sportive', 'Hypnose sportive',
 'Précaution éthique : ne pas suggérer de cibles spécifiques. Diminution importance des échecs passés. Acceptation philosophique des revers comme prix de la joie de jouer.',
 '1 séance + autohypnose', 'Intermédiaire',
 array['Gibbons', 'Peur de l''échec', 'Résilience'],
 '#7C5CBF', 1,
 array['Peur de l''échec', 'Plaisir du jeu'],
 'Hammond 1990 (ASCH)', array['Estime & confiance en soi']),

(700, 'Endurance — Fatigue comme stimulus (Jackson, Gass, Camp)', 'Performance sportive', 'Hypnose sportive',
 'Recadrage majeur : la fatigue est le PREMIER signe qu''on approche du max, pas un signal d''arrêt. Si on continue, la sensation diminue. ATTENTION éthique : risque de blessure.',
 '1 séance', 'Avancé',
 array['Jackson', 'Endurance', 'Course de fond', 'Recadrage fatigue'],
 '#7C5CBF', 1,
 array['Endurance', 'Course de fond', 'Cyclisme'],
 'Hammond 1990 (ASCH)', array['Estime & confiance en soi'])

on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  practice = excluded.practice,
  description = excluded.description,
  duration = excluded.duration,
  level = excluded.level,
  tags = excluded.tags,
  color = excluded.color,
  sessions = excluded.sessions,
  objectives = excluded.objectives,
  source = excluded.source,
  motifs = excluded.motifs;
