-- Seed protocoles Maître Praticien en Hypnose (3 modules GS Formation)
-- IDs : 927-949 + 973-988 (28 protocoles)
-- Sources : GS Formation — Maitre Praticien en Hypnose Modules 1, 2, 3 (Laurent Martini)

INSERT INTO public.protocols (id, name, category, practice, description, duration, level, tags, color, sessions, objectives, source, motifs)
VALUES
  -- ===== MODULE 1 — DEEP HYPNOSE (927-933) =====
  (927,
   'Modèle Ramey-Miles — Conscient/Inconscient/Surconscient',
   'Maître Praticien Hypnose — Modèle de l''esprit',
   'Hypnose Ericksonienne',
   'Modèle de l''esprit en 3 parties (Ramey-Miles) : Conscient (analyse, jugement), Inconscient/subconscient (intuitions, programmes), Surconscient (sagesse, télépathie, neurones miroirs). Chaque composante fonctionne indépendamment et ensemble. Cadre théorique fondateur du Maître Praticien.',
   '60 min (présentation)',
   'Avancé',
   ARRAY['hypnose', 'modèle esprit', 'Ramey-Miles', 'surconscient', 'inconscient'],
   '#7C5CBF',
   1,
   ARRAY['Comprendre les 3 parties de l''esprit', 'Distinguer Inconscient et Surconscient', 'Adapter sa pratique à chaque niveau', 'Cadre théorique de référence Maître Praticien'],
   'GS Formation — Maitre Praticien Hypnose Module 1',
   ARRAY['Quête de sens & spiritualité']
  ),
  (928,
   'État Esdaile — Transe somnambulique chirurgicale',
   'Maître Praticien Hypnose — Profondeur',
   'Hypnose Ericksonienne',
   'État de transe extrêmement profonde décrit par James Esdaile (1808-1859), chirurgien écossais. Permet anesthésie totale pour chirurgie sans anesthésique chimique. Caractérisé par une absence de réaction aux stimuli douloureux, immobilité totale, mais conscience préservée.',
   '60 min (induction prolongée)',
   'Avancé',
   ARRAY['hypnose', 'Esdaile', 'somnambulisme', 'chirurgie', 'analgésie', 'transe profonde'],
   '#1B2D47',
   1,
   ARRAY['Atteindre la profondeur de transe Esdaile', 'Permettre une anesthésie hypnotique totale', 'Soutenir un soin chirurgical sans antalgique', 'Travail avancé exclusif praticien expérimenté'],
   'GS Formation — Maitre Praticien Hypnose Module 1',
   ARRAY['Douleurs & psychosomatique']
  ),
  (929,
   'État Sichort — Transe profonde proceduale',
   'Maître Praticien Hypnose — Profondeur',
   'Hypnose Ericksonienne',
   'État de transe profonde structurée décrit par Walter Sichort (1923-2001). Approche proceduale stricte combinée à la profondeur somnambulique. Permet un travail thérapeutique précis avec dialogue maintenu (signaling), idéal pour régression et travail systémique.',
   '60-90 min',
   'Avancé',
   ARRAY['hypnose', 'Sichort', 'transe profonde', 'proceduale', 'somnambulisme'],
   '#7C5CBF',
   1,
   ARRAY['Atteindre la transe Sichort en sécurité', 'Maintenir le dialogue en somnambulisme', 'Permettre régression et travail systémique avancé', 'Combiner profondeur et précision'],
   'GS Formation — Maitre Praticien Hypnose Module 1',
   ARRAY['Trauma & deuil', 'Anxiété & stress']
  ),
  (930,
   'Tests de pré-induction — Suggestibilité avancée',
   'Maître Praticien Hypnose — Pré-induction',
   'Hypnose Ericksonienne',
   'Batterie complète de tests de pré-induction pour évaluer la suggestibilité du client : doigts collés (déjà 833), se pencher en arrière, se pencher en avant, citron imaginaire, bras lourd. Permet d''adapter l''induction au profil et de renforcer la confiance.',
   '15-30 min (pré-induction)',
   'Intermédiaire',
   ARRAY['hypnose', 'suggestibilité', 'pré-induction', 'tests', 'évaluation'],
   '#5B8FB9',
   1,
   ARRAY['Évaluer la suggestibilité du client', 'Renforcer sa confiance par tests réussis', 'Adapter l''induction au profil', 'Préparer une transe profonde'],
   'GS Formation — Maitre Praticien Hypnose Module 1',
   ARRAY['Anxiété & stress']
  ),
  (931,
   'Speed Hypnose — Défi d''autorité (Elman)',
   'Maître Praticien Hypnose — Speed',
   'Hypnose Ericksonienne',
   'Approche hypnotique rapide d''Elman par défi d''autorité : suggestions directes ferme et structurées, induction en moins de 2 minutes. Particulièrement utilisée en hypnose médicale et en démonstration. Suppose une posture d''autorité bienveillante du praticien.',
   '5-15 min',
   'Avancé',
   ARRAY['hypnose', 'speed', 'Elman', 'défi autorité', 'suggestions directes'],
   '#B85450',
   1,
   ARRAY['Induire la transe en moins de 2 minutes', 'Maîtriser le défi d''autorité elmanien', 'Adapter à un cadre médical ou démonstratif', 'Posture d''autorité bienveillante'],
   'GS Formation — Maitre Praticien Hypnose Module 1',
   ARRAY['Anxiété & stress', 'Performance & examens']
  ),
  (932,
   'Fractionnement hypnotique — Approfondissement progressif',
   'Maître Praticien Hypnose — Approfondissement',
   'Hypnose Ericksonienne',
   'Technique d''approfondissement par fractionnement : entrer en transe, en ressortir partiellement, y replonger plus profondément. Répéter 3-5 fois. Chaque cycle approfondit considérablement la transe. Méthode emblématique de Sichort et Elman.',
   '15-25 min (intégré)',
   'Intermédiaire',
   ARRAY['hypnose', 'fractionnement', 'approfondissement', 'Sichort', 'cycles'],
   '#2E8A7B',
   1,
   ARRAY['Approfondir la transe par cycles successifs', 'Atteindre le somnambulisme rapidement', 'Combiner avec induction Elman ou Sichort', 'Préparer un travail thérapeutique profond'],
   'GS Formation — Maitre Praticien Hypnose Module 1',
   ARRAY['Anxiété & stress', 'Douleurs & psychosomatique']
  ),
  (933,
   'Hypnose médicale Elman — Cadre dentaire/chirurgical',
   'Maître Praticien Hypnose — Médical',
   'Hypnose Ericksonienne',
   'Cadre complet d''utilisation de l''hypnose en milieu médical (dentaire, chirurgie, accouchement) selon Dave Elman. Coordination avec équipe médicale, induction rapide, suggestions analgésiques précises, suggestions post-opératoires (cicatrisation, hémostase, confort).',
   '30-60 min × intervention',
   'Avancé',
   ARRAY['hypnose', 'médicale', 'Elman', 'dentaire', 'chirurgie', 'accouchement'],
   '#B85450',
   1,
   ARRAY['Soutenir une intervention médicale par hypnose', 'Induire et maintenir l''analgésie', 'Coordonner avec équipe médicale', 'Optimiser cicatrisation et récupération'],
   'GS Formation — Maitre Praticien Hypnose Module 1',
   ARRAY['Douleurs & psychosomatique']
  ),

  -- ===== MODULE 2 — SYSTÉMIE & SEXOTHÉRAPIE (934-944) =====
  (934,
   'Hypnose systémique — Approche relationnelle',
   'Maître Praticien Hypnose — Systémie',
   'Hypnose Ericksonienne',
   'Intégration de l''approche systémique (Bateson, Bowen, Minuchin, Satir, Hellinger) à l''hypnose. Le client est considéré comme partie d''un système (familial, social, professionnel). Les symptômes sont interprétés comme reflets de dynamiques systémiques. Travail sur soi ET sur le système.',
   '60-90 min',
   'Avancé',
   ARRAY['hypnose', 'systémie', 'Bateson', 'Minuchin', 'Hellinger', 'famille'],
   '#5B8FB9',
   1,
   ARRAY['Considérer le client comme partie d''un système', 'Identifier les dynamiques systémiques sous-jacentes', 'Intervenir sur soi ET sur le système', 'Approche holistique et durable'],
   'GS Formation — Maitre Praticien Hypnose Module 2',
   ARRAY['Conflits & communication', 'Trauma & deuil']
  ),
  (935,
   'Génogramme en hypnose — Cartographie familiale',
   'Maître Praticien Hypnose — Systémie',
   'Hypnose Ericksonienne',
   'Construction d''un génogramme (arbre généalogique enrichi des relations, conflits, traumatismes) en transe légère. Permet de visualiser les patterns familiaux récurrents, les loyautés invisibles, les répétitions transgénérationnelles. Outil diagnostic majeur en hypnose systémique.',
   '90 min',
   'Avancé',
   ARRAY['hypnose', 'génogramme', 'famille', 'transgénérationnel', 'patterns'],
   '#7C5CBF',
   1,
   ARRAY['Construire un génogramme complet du client', 'Identifier les patterns familiaux récurrents', 'Repérer les loyautés invisibles', 'Préparer un travail systémique ciblé'],
   'GS Formation — Maitre Praticien Hypnose Module 2',
   ARRAY['Trauma & deuil', 'Conflits & communication']
  ),
  (936,
   'Triangle dramatique de Karpman — Mise en scène hypnotique',
   'Maître Praticien Hypnose — Systémie',
   'Hypnose Ericksonienne',
   'Travail sur le triangle dramatique (Persécuteur / Victime / Sauveur) de Karpman, mis en scène en transe hypnotique. Le client visite chaque rôle, identifie son rôle préférentiel, comprend les dynamiques de son système relationnel. Sortie du triangle par responsabilisation.',
   '60-90 min',
   'Avancé',
   ARRAY['hypnose', 'Karpman', 'triangle dramatique', 'persécuteur', 'victime', 'sauveur'],
   '#B85450',
   1,
   ARRAY['Identifier son rôle dans le triangle dramatique', 'Visiter chaque rôle en transe', 'Comprendre les dynamiques relationnelles', 'Sortir du triangle par responsabilisation'],
   'GS Formation — Maitre Praticien Hypnose Module 2',
   ARRAY['Conflits & communication']
  ),
  (937,
   'Constellations familiales en hypnose (Hellinger)',
   'Maître Praticien Hypnose — Systémie',
   'Hypnose Ericksonienne',
   'Adaptation hypnotique des Constellations familiales de Bert Hellinger. En transe, le client visualise sa famille élargie, identifie les places, les exclus, les loyautés invisibles, les charges héritées. Réparation symbolique : remettre chacun à sa juste place.',
   '90-120 min',
   'Avancé',
   ARRAY['hypnose', 'constellations', 'Hellinger', 'famille', 'loyauté', 'transgénérationnel'],
   '#2E8A7B',
   1,
   ARRAY['Visualiser la constellation familiale complète', 'Identifier les exclus et les loyautés', 'Effectuer la réparation symbolique', 'Libérer les charges transgénérationnelles'],
   'GS Formation — Maitre Praticien Hypnose Module 2',
   ARRAY['Trauma & deuil', 'Quête de sens & spiritualité']
  ),
  (938,
   'Protocole relationnel en hypnoth — Réparation systémique',
   'Maître Praticien Hypnose — Systémie',
   'Hypnose Ericksonienne',
   'Protocole structuré d''hypnose pour les problèmes relationnels (couple, famille, équipe) : identification du système, cartographie des positions, dialogue intérieur avec chaque membre du système en transe, recadrage, négociation symbolique, intégration.',
   '90-120 min × 3-5 séances',
   'Avancé',
   ARRAY['hypnose', 'relationnel', 'systémique', 'couple', 'famille', 'équipe'],
   '#5B8FB9',
   3,
   ARRAY['Cartographier le système relationnel', 'Dialoguer en transe avec chaque membre', 'Recadrer les positions et les attentes', 'Négocier symboliquement les nouveaux équilibres'],
   'GS Formation — Maitre Praticien Hypnose Module 2',
   ARRAY['Conflits & communication', 'Couple & sexualité']
  ),
  (939,
   'Sexothérapie hypnose — Anamnèse approfondie',
   'Maître Praticien Hypnose — Sexothérapie',
   'Hypnose Ericksonienne',
   'Premier entretien sexothérapeutique structuré : histoire sexuelle, croyances héritées, éducation, blessures, contexte couple, demande précise. Cadre sécurisant et confidentiel. Coordination avec sexologue ou médecin.',
   '90 min (1ère séance)',
   'Avancé',
   ARRAY['hypnose', 'sexothérapie', 'anamnèse', 'histoire sexuelle', 'cadre'],
   '#B85450',
   1,
   ARRAY['Recueillir l''histoire sexuelle complète', 'Identifier les croyances et blessures', 'Établir le cadre thérapeutique sécurisant', 'Coordonner avec sexologue/médecin'],
   'GS Formation — Maitre Praticien Hypnose Module 2',
   ARRAY['Couple & sexualité']
  ),
  (940,
   'Dysfonctions sexuelles masculines — Protocole hypnose',
   'Maître Praticien Hypnose — Sexothérapie',
   'Hypnose Ericksonienne',
   'Protocole hypnotique pour dysfonctions sexuelles masculines : trouble érectile, éjaculation prématurée ou retardée, manque de désir. Travail sur l''anxiété de performance, la pression sociale, l''image corporelle, la communication avec le/la partenaire. Approche pluridisciplinaire.',
   '60-90 min × 5-8 séances',
   'Avancé',
   ARRAY['hypnose', 'sexothérapie', 'masculin', 'érection', 'éjaculation', 'désir'],
   '#7C5CBF',
   6,
   ARRAY['Lever l''anxiété de performance', 'Travailler les croyances limitantes masculines', 'Restaurer le désir et la spontanéité', 'Améliorer la communication intime'],
   'GS Formation — Maitre Praticien Hypnose Module 2',
   ARRAY['Couple & sexualité']
  ),
  (941,
   'Dysfonctions du désir — Hommes & femmes',
   'Maître Praticien Hypnose — Sexothérapie',
   'Hypnose Ericksonienne',
   'Protocole hypnotique pour les troubles du désir (hypoactif, aversif, désynchronisation de couple). Recherche des causes (médicales, psychologiques, relationnelles), recadrage des croyances, réveil progressif du désir par travail symbolique et imaginaire. Approche sans pression.',
   '60-90 min × 5-8 séances',
   'Avancé',
   ARRAY['hypnose', 'sexothérapie', 'désir', 'hypoactif', 'couple'],
   '#B85450',
   6,
   ARRAY['Identifier les causes du trouble du désir', 'Recadrer les croyances limitantes', 'Réveiller le désir par travail symbolique', 'Restaurer la synchronisation de couple si applicable'],
   'GS Formation — Maitre Praticien Hypnose Module 2',
   ARRAY['Couple & sexualité']
  ),
  (942,
   'Dysfonctions de l''élaboration sexuelle — Vaginisme, anorgasmie, douleurs',
   'Maître Praticien Hypnose — Sexothérapie',
   'Hypnose Ericksonienne',
   'Protocole hypnotique pour les troubles de l''élaboration sexuelle féminine : vaginisme, dyspareunie, anorgasmie. Désensibilisation des associations négatives, travail sur l''image corporelle, restauration du plaisir par sensate focus en transe. Coordination avec gynécologue.',
   '60-90 min × 6-10 séances',
   'Avancé',
   ARRAY['hypnose', 'sexothérapie', 'féminin', 'vaginisme', 'anorgasmie', 'dyspareunie'],
   '#7C5CBF',
   8,
   ARRAY['Désensibiliser les associations aversives', 'Restaurer l''image corporelle positive', 'Réapprendre le plaisir progressivement', 'Coordonner avec gynécologue/sexologue'],
   'GS Formation — Maitre Praticien Hypnose Module 2',
   ARRAY['Couple & sexualité']
  ),
  (943,
   'Hypnose & dysfonctions de couple — Approche systémique',
   'Maître Praticien Hypnose — Sexothérapie',
   'Hypnose Ericksonienne',
   'Approche combinée systémique + hypnose pour les dysfonctions de couple. Travail individuel ET en duo si possible. Identification des dynamiques relationnelles, des projections, des attentes non dites. Recadrage en transe légère, pont vers une nouvelle dynamique.',
   '90 min × 6-12 séances',
   'Avancé',
   ARRAY['hypnose', 'couple', 'systémique', 'dynamique', 'communication'],
   '#5B8FB9',
   8,
   ARRAY['Cartographier la dynamique de couple', 'Identifier projections et attentes non dites', 'Recadrer en transe individuelle puis en duo', 'Construire une nouvelle dynamique'],
   'GS Formation — Maitre Praticien Hypnose Module 2',
   ARRAY['Couple & sexualité', 'Conflits & communication']
  ),
  (944,
   'Approche Satir — 5 styles de communication en transe',
   'Maître Praticien Hypnose — Communication',
   'Hypnose Ericksonienne',
   'Travail sur les 5 styles de communication identifiés par Virginia Satir : Lénifiant (s''excuse), Accusateur (blâme), Calculateur (raisonneur), Distrayant (esquive), Niveleur (authentique). Identification du style dominant en stress, mise en scène en transe, intégration du style Niveleur.',
   '60-90 min',
   'Avancé',
   ARRAY['hypnose', 'Satir', 'communication', 'styles', 'famille'],
   '#C8A030',
   1,
   ARRAY['Identifier son style de communication en stress', 'Comprendre les 5 styles de Satir', 'Mettre en scène chaque style en transe', 'Intégrer le style Niveleur authentique'],
   'GS Formation — Maitre Praticien Hypnose Module 2',
   ARRAY['Conflits & communication', 'Couple & sexualité']
  ),

  -- ===== MODULE 3 — DÉPENDANCE/DÉPRESSION/DEUIL/SYMBOLISME (945-949 + 973-986) =====
  (945,
   'Hallucination thérapeutique positive',
   'Maître Praticien Hypnose — Hallucinations',
   'Hypnose Ericksonienne',
   'Création volontaire en transe profonde d''une hallucination positive (visuelle, auditive, kinesthésique, olfactive ou gustative) au service du travail thérapeutique. Ex : voir une figure protectrice, entendre une parole apaisante, sentir une chaleur. Travail avancé.',
   '45-60 min',
   'Avancé',
   ARRAY['hypnose', 'hallucination', 'positive', 'visuelle', 'thérapeutique'],
   '#7C5CBF',
   1,
   ARRAY['Créer une hallucination positive ressource', 'Renforcer une expérience thérapeutique', 'Outil avancé en somnambulisme', 'Compléter un travail symbolique'],
   'GS Formation — Maitre Praticien Hypnose Module 3',
   ARRAY['Anxiété & stress', 'Trauma & deuil']
  ),
  (946,
   'Hallucination thérapeutique négative',
   'Maître Praticien Hypnose — Hallucinations',
   'Hypnose Ericksonienne',
   'Suppression volontaire en transe profonde d''une perception (douleur, son intrusif, image obsessionnelle). « Vous ne percevez plus X. » Particulièrement utile pour douleur chronique, acouphènes (cf 842), souvenirs intrusifs.',
   '45-60 min',
   'Avancé',
   ARRAY['hypnose', 'hallucination', 'négative', 'suppression', 'douleur'],
   '#1B2D47',
   1,
   ARRAY['Supprimer une perception perturbante', 'Outil pour douleur, acouphènes, intrusion', 'Travail en somnambulisme exclusivement', 'Compléter une approche médicale'],
   'GS Formation — Maitre Praticien Hypnose Module 3',
   ARRAY['Douleurs & psychosomatique']
  ),
  (947,
   'Interrompre un schéma de comportement — Pattern interrupt avancé',
   'Maître Praticien Hypnose — Pattern',
   'Hypnose Ericksonienne',
   'Technique d''interruption d''un schéma comportemental ancré (rituel obsessionnel, geste compulsif, automatisme). Combinaison de confusion (cf 861), de surprise et de suggestion directe en transe. Crée une fenêtre de réorganisation comportementale.',
   '45-60 min',
   'Avancé',
   ARRAY['hypnose', 'pattern interrupt', 'schéma', 'compulsion', 'automatisme'],
   '#B85450',
   1,
   ARRAY['Interrompre un schéma comportemental ancré', 'Créer une fenêtre de réorganisation', 'Combiner avec confusion et surprise', 'Préparer un nouveau comportement'],
   'GS Formation — Maitre Praticien Hypnose Module 3',
   ARRAY['Addictions', 'Anxiété & stress']
  ),
  (948,
   'Faire grandir l''enfant intérieur — Hypnose réparatrice',
   'Maître Praticien Hypnose — Enfant intérieur',
   'Hypnose Ericksonienne',
   'Protocole hypnotique de réparation et de croissance de l''enfant intérieur blessé. Visualisation de l''enfant à l''âge de la blessure, dialogue avec lui, transmission des ressources adultes, accompagnement symbolique de sa croissance jusqu''à l''adulte intégré. Spécifique addictions.',
   '90 min × 3-5 séances',
   'Avancé',
   ARRAY['hypnose', 'enfant intérieur', 'addiction', 'réparation', 'croissance'],
   '#7C5CBF',
   4,
   ARRAY['Rencontrer l''enfant intérieur blessé', 'Dialoguer et transmettre les ressources', 'Accompagner sa croissance symbolique', 'Particulièrement efficace en addictions'],
   'GS Formation — Maitre Praticien Hypnose Module 3',
   ARRAY['Addictions', 'Trauma & deuil']
  ),
  (949,
   'Réconciliation métaphorique — Addictions',
   'Maître Praticien Hypnose — Addictions',
   'Hypnose Ericksonienne',
   'Approche hypnotique des addictions par réconciliation métaphorique avec la substance ou le comportement addictif. Dialogue symbolique : la substance comme « ami toxique », identification de ce qu''elle apportait, recherche d''alternatives, séparation respectueuse.',
   '90 min × 4-6 séances',
   'Avancé',
   ARRAY['hypnose', 'addictions', 'réconciliation', 'métaphore', 'substance'],
   '#E08550',
   5,
   ARRAY['Dialoguer symboliquement avec l''addiction', 'Identifier ce qu''elle apportait', 'Trouver des alternatives saines', 'Séparation respectueuse pour libération durable'],
   'GS Formation — Maitre Praticien Hypnose Module 3',
   ARRAY['Addictions']
  ),
  (973,
   'Hypnose pour la dépression — DSM-V & approche douce',
   'Maître Praticien Hypnose — Dépression',
   'Hypnose Ericksonienne',
   'Cadre d''accompagnement hypnotique de la dépression légère à modérée (DSM-V). Coordination obligatoire avec psychiatre/médecin traitant. Travail sur l''anhédonie, l''anergie, les ruminations, l''auto-dévalorisation. Hypnose ne remplace JAMAIS un traitement antidépresseur.',
   '60-90 min × 8-12 séances',
   'Avancé',
   ARRAY['hypnose', 'dépression', 'DSM-V', 'anhédonie', 'rumination'],
   '#5B8FB9',
   10,
   ARRAY['Compléter un suivi médical de dépression', 'Travailler sur anhédonie et ruminations', 'Restaurer l''accès au plaisir progressivement', 'Coordination obligatoire avec psychiatre'],
   'GS Formation — Maitre Praticien Hypnose Module 3',
   ARRAY['Burn-out & fatigue', 'Trauma & deuil']
  ),
  (974,
   'Phases du deuil — Accompagnement hypnotique',
   'Maître Praticien Hypnose — Deuil',
   'Hypnose Ericksonienne',
   'Accompagnement hypnotique des 5 phases du deuil (Kübler-Ross) : déni, colère, marchandage, dépression, acceptation. Identification de la phase actuelle, soutien adapté, travail symbolique de chaque étape, accompagnement vers l''acceptation et la reconstruction.',
   '60-90 min × selon besoin',
   'Avancé',
   ARRAY['hypnose', 'deuil', 'Kübler-Ross', 'phases', 'acceptation'],
   '#1B2D47',
   1,
   ARRAY['Identifier la phase de deuil actuelle', 'Soutenir adaptée à chaque phase', 'Travail symbolique du passage', 'Accompagner vers reconstruction identitaire'],
   'GS Formation — Maitre Praticien Hypnose Module 3',
   ARRAY['Trauma & deuil']
  ),
  (975,
   '4 types de deuil — Difficile, compliqué, pathologique',
   'Maître Praticien Hypnose — Deuil',
   'Hypnose Ericksonienne',
   'Diagnostic différentiel des 4 types de deuil : Normal (résolution naturelle 6-12 mois), Difficile (intensité accrue mais évolution), Compliqué (blocage > 12 mois), Pathologique (DSM-V, prolongé > 12 mois avec dysfonctionnement). Approche hypnotique adaptée à chaque type.',
   '90 min (diagnostic) + parcours adapté',
   'Avancé',
   ARRAY['hypnose', 'deuil', 'pathologique', 'compliqué', 'diagnostic'],
   '#B85450',
   1,
   ARRAY['Diagnostiquer le type de deuil', 'Adapter l''approche au type identifié', 'Coordonner avec psychiatre si pathologique', 'Plan thérapeutique sur mesure'],
   'GS Formation — Maitre Praticien Hypnose Module 3',
   ARRAY['Trauma & deuil', 'Burn-out & fatigue']
  ),
  (976,
   'Reconstitution identitaire post-deuil',
   'Maître Praticien Hypnose — Deuil',
   'Hypnose Ericksonienne',
   'Après la phase d''acceptation : reconstruction de l''identité du client en l''absence de la personne perdue. Travail sur les rôles laissés vacants, les ressources personnelles, la mission de vie révisée. Particulièrement utile après deuil de conjoint, parent, enfant.',
   '90 min × 3-5 séances',
   'Avancé',
   ARRAY['hypnose', 'deuil', 'identité', 'reconstruction', 'mission'],
   '#7C5CBF',
   4,
   ARRAY['Identifier les rôles vacants suite au deuil', 'Mobiliser les ressources personnelles', 'Réviser sa mission de vie', 'Reconstruire une identité intégrée'],
   'GS Formation — Maitre Praticien Hypnose Module 3',
   ARRAY['Trauma & deuil', 'Quête de sens & spiritualité']
  ),
  (977,
   'Sage intérieur — Ressource de sagesse profonde',
   'Maître Praticien Hypnose — Ressource',
   'Hypnose Ericksonienne',
   'Visualisation et dialogue avec la figure du Sage intérieur. En transe profonde, le client rencontre cette part profonde de lui-même qui « connaît » les éléments fondamentaux de sa vie. Particulièrement utile dans les transitions, deuils, choix majeurs.',
   '60-75 min',
   'Avancé',
   ARRAY['hypnose', 'sage intérieur', 'sagesse', 'ressource', 'archétype'],
   '#2E8A7B',
   1,
   ARRAY['Rencontrer le Sage intérieur en transe', 'Dialoguer et recevoir guidance', 'Mobiliser sa sagesse profonde', 'Outil pour transitions et choix majeurs'],
   'GS Formation — Maitre Praticien Hypnose Module 3',
   ARRAY['Quête de sens & spiritualité', 'Trauma & deuil']
  ),
  (978,
   'Technique Universelle Sacrée (TUS)',
   'Maître Praticien Hypnose — Hypno-symbolisme',
   'Hypnose Ericksonienne',
   'Technique avancée d''hypno-symbolisme rassemblant plusieurs traditions : centrage corporel, activation du chakra du cœur, connexion à la conscience universelle, demande, lâcher-prise, intégration. Particulièrement puissante pour quête de sens et travail spirituel.',
   '90 min',
   'Avancé',
   ARRAY['hypnose', 'TUS', 'sacré', 'spirituel', 'symbolique'],
   '#C8A030',
   1,
   ARRAY['Connecter à la conscience universelle', 'Formuler une demande sacrée', 'Lâcher-prise et recevoir', 'Intégrer une expérience spirituelle profonde'],
   'GS Formation — Maitre Praticien Hypnose Module 3',
   ARRAY['Quête de sens & spiritualité']
  ),
  (979,
   'Voyage du Héros — Exploration psychologique (Campbell)',
   'Maître Praticien Hypnose — Symbolique',
   'Hypnose Ericksonienne',
   'Adaptation hypnotique du Voyage du Héros de Joseph Campbell (12 étapes : Appel, Refus, Mentor, Seuil, Épreuves, Approche, Ordalie, Récompense, Retour, Résurrection, Don). Le client traverse en transe les étapes de sa propre transformation héroïque.',
   '120-150 min',
   'Avancé',
   ARRAY['hypnose', 'voyage du héros', 'Campbell', 'transformation', 'archétype'],
   '#7C5CBF',
   1,
   ARRAY['Traverser les 12 étapes du Voyage du Héros', 'Vivre symboliquement la transformation', 'Travail identitaire et de sens', 'Outil puissant en transition de vie'],
   'GS Formation — Maitre Praticien Hypnose Module 3',
   ARRAY['Quête de sens & spiritualité', 'Estime & confiance en soi']
  ),
  (980,
   'Vibrations cellulaires — Travail au niveau corporel profond',
   'Maître Praticien Hypnose — Énergétique',
   'Hypnose Ericksonienne',
   'Hypnose au niveau cellulaire : visualisation des cellules vibrant à une fréquence harmonisée, communication avec le corps physique au plan le plus fin. Inspiré des travaux sur la PNL générative et l''épigénétique. Approche complémentaire au médical.',
   '60-90 min',
   'Avancé',
   ARRAY['hypnose', 'vibrations', 'cellulaire', 'corps', 'énergétique'],
   '#2E8A7B',
   1,
   ARRAY['Visualiser les cellules en harmonie vibratoire', 'Communiquer avec le corps profond', 'Soutenir une guérison physiologique', 'Compléter un suivi médical'],
   'GS Formation — Maitre Praticien Hypnose Module 3',
   ARRAY['Douleurs & psychosomatique', 'Burn-out & fatigue']
  ),
  (981,
   'Purification des mémoires cellulaires',
   'Maître Praticien Hypnose — Énergétique',
   'Hypnose Ericksonienne',
   'Protocole hypnotique de purification des mémoires cellulaires (traumatismes, charges héritées). Visualisation d''une lumière purifiante traversant chaque cellule, libération symbolique des charges anciennes, intégration d''une nouvelle vibration. Travail spirituel profond.',
   '90 min',
   'Avancé',
   ARRAY['hypnose', 'purification', 'mémoires cellulaires', 'libération', 'énergétique'],
   '#5B8FB9',
   1,
   ARRAY['Identifier les charges cellulaires à libérer', 'Purifier symboliquement chaque zone du corps', 'Intégrer une nouvelle vibration', 'Approche complémentaire au travail trauma'],
   'GS Formation — Maitre Praticien Hypnose Module 3',
   ARRAY['Trauma & deuil', 'Quête de sens & spiritualité']
  ),
  (982,
   'Guérison transgénérationnelle — Libération des chaînes ancestrales',
   'Maître Praticien Hypnose — Transgénérationnel',
   'Hypnose Ericksonienne',
   'Travail hypnotique sur les héritages transgénérationnels : loyautés invisibles, secrets de famille, traumatismes hérités, répétitions. Visite symbolique des ancêtres, dialogue, restitution des charges qui ne nous appartiennent pas, libération des lignées.',
   '90-120 min',
   'Avancé',
   ARRAY['hypnose', 'transgénérationnel', 'ancêtres', 'lignée', 'libération'],
   '#7C5CBF',
   1,
   ARRAY['Identifier les charges transgénérationnelles', 'Visiter symboliquement les ancêtres', 'Restituer ce qui ne nous appartient pas', 'Libérer les lignées'],
   'GS Formation — Maitre Praticien Hypnose Module 3',
   ARRAY['Trauma & deuil', 'Quête de sens & spiritualité']
  ),
  (983,
   'Marche de Lumière & symbolique des couleurs',
   'Maître Praticien Hypnose — Symbolique',
   'Hypnose Ericksonienne',
   'Protocole hypnotique de marche symbolique à travers 7 lumières colorées (rouge ancrage, orange créativité, jaune confiance, vert harmonie, bleu communication, indigo intuition, violet spiritualité). Activation des chakras et travail vibratoire complet.',
   '60-90 min',
   'Avancé',
   ARRAY['hypnose', 'marche', 'lumière', 'couleurs', 'chakras', 'symbolique'],
   '#C8A030',
   1,
   ARRAY['Traverser les 7 couleurs/chakras', 'Activer chaque qualité énergétique', 'Travail vibratoire complet', 'Outil de centrage et harmonisation'],
   'GS Formation — Maitre Praticien Hypnose Module 3',
   ARRAY['Quête de sens & spiritualité', 'Anxiété & stress']
  ),
  (984,
   'Travail du rêve en hypnose — 3 techniques',
   'Maître Praticien Hypnose — Rêve',
   'Hypnose Ericksonienne',
   'Trois techniques de travail des rêves en hypnose : (1) Technique du souvenir (revisiter un rêve fait), (2) Technique de la sensation de rêve (induire un état onirique), (3) Méthode du rêve hypnotique (créer un rêve thérapeutique sur mesure).',
   '60-90 min',
   'Avancé',
   ARRAY['hypnose', 'rêve', 'onirique', 'symbolique', 'inconscient'],
   '#1B2D47',
   1,
   ARRAY['Maîtriser les 3 techniques de travail du rêve', 'Revisiter un rêve marquant', 'Induire un état onirique en transe', 'Créer un rêve thérapeutique'],
   'GS Formation — Maitre Praticien Hypnose Module 3',
   ARRAY['Sommeil & insomnie', 'Trauma & deuil']
  ),
  (985,
   'Apprentissage moteur via rêves lucides',
   'Maître Praticien Hypnose — Rêve',
   'Hypnose Ericksonienne',
   'Utilisation des rêves lucides (induits en transe) pour l''apprentissage moteur : sport, musique, gestes professionnels. La répétition mentale en état onirique active les mêmes circuits neuronaux que la pratique réelle. Technique avancée pour performance.',
   '60 min',
   'Avancé',
   ARRAY['hypnose', 'rêve lucide', 'apprentissage moteur', 'sport', 'performance'],
   '#2E8A7B',
   1,
   ARRAY['Induire un rêve lucide en transe', 'Répéter mentalement un geste moteur', 'Activer les circuits neuronaux par visualisation', 'Compléter l''entraînement physique réel'],
   'GS Formation — Maitre Praticien Hypnose Module 3',
   ARRAY['Performance & examens']
  ),
  (986,
   'Dessin & écriture automatiques — Accès à l''inconscient',
   'Maître Praticien Hypnose — Expression',
   'Hypnose Ericksonienne',
   'Techniques d''expression spontanée en transe légère : dessin automatique (laisser la main dessiner sans contrôle conscient) et écriture automatique. L''inconscient s''exprime directement par le geste. Outil diagnostic et thérapeutique. Pas de jugement esthétique.',
   '45-60 min',
   'Intermédiaire',
   ARRAY['hypnose', 'dessin automatique', 'écriture automatique', 'inconscient', 'expression'],
   '#E08550',
   1,
   ARRAY['Permettre l''expression directe de l''inconscient', 'Recueillir matière diagnostique non verbale', 'Travail créatif et thérapeutique', 'Outil pour clients verbaux bloqués'],
   'GS Formation — Maitre Praticien Hypnose Module 3',
   ARRAY['Trauma & deuil', 'Quête de sens & spiritualité']
  )
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  practice = EXCLUDED.practice,
  description = EXCLUDED.description,
  duration = EXCLUDED.duration,
  level = EXCLUDED.level,
  tags = EXCLUDED.tags,
  color = EXCLUDED.color,
  sessions = EXCLUDED.sessions,
  objectives = EXCLUDED.objectives,
  source = EXCLUDED.source,
  motifs = EXCLUDED.motifs;
