-- Seed protocoles avancés (vagues 4-8)
-- IDs : 840-849 (Maître Praticien Hypnose) + 850-859 (Maître Praticien PNL)
--       + 860-869 (Hypnose Erickson avancée) + 870-879 (Outils combinés PNL+Hypnose)
-- Sources : GS Formation modules avancés

INSERT INTO public.protocols (id, name, category, practice, description, duration, level, tags, color, sessions, objectives, source, motifs)
VALUES
  -- ===== MAÎTRE PRATICIEN HYPNOSE (840-845) =====
  (840,
   'Hypnose Conversationnelle — Milton model',
   'Maître Praticien — Communication',
   'Hypnose Ericksonienne',
   'Communication hypnotique sans induction formelle. Le client reste en état de conscience ordinaire mais reçoit des suggestions thérapeutiques par le langage Milton (vague, permissif, multi-sens). Particulièrement utile pour les résistants à l''hypnose formelle, les enfants, ou en complément d''autres approches.',
   '60 min (intégrable à toute séance)',
   'Avancé',
   ARRAY['hypnose conversationnelle', 'Milton model', 'Erickson', 'permissif', 'sans induction'],
   '#7C5CBF',
   1,
   ARRAY['Maîtriser le langage hypnotique permissif', 'Susciter le changement sans induction formelle', 'Travailler avec les résistants à l''hypnose', 'Intégrer l''hypnose à toute conversation thérapeutique'],
   'GS Formation — Maître Praticien Hypnose Module 1',
   ARRAY['Anxiété & stress', 'Conflits & communication']
  ),
  (841,
   'Hypnose & Sexothérapie — Troubles sexuels',
   'Maître Praticien — Sexothérapie',
   'Hypnose Ericksonienne',
   'Approche hypnotique des troubles sexuels (désir, érection, anorgasmie, vaginisme, éjaculation prématurée, douleurs). Travail sur les croyances limitantes, les blessures émotionnelles, l''image corporelle et la communication intime. Pluridisciplinaire avec sexologue ou médecin.',
   '5-8 séances de 60 min',
   'Avancé',
   ARRAY['sexologie', 'troubles sexuels', 'désir', 'image corporelle', 'intimité', 'couple'],
   '#B85450',
   6,
   ARRAY['Identifier les origines psychologiques du trouble', 'Recadrer les croyances limitantes sexuelles', 'Travailler l''image corporelle et l''estime', 'Restaurer la communication intime', 'Réapprendre le plaisir sans pression de performance'],
   'GS Formation — Hypnose et Sexothérapie',
   ARRAY['Couple & sexualité', 'Estime & confiance en soi']
  ),
  (842,
   'Hypnose & Acouphènes — Réduction de la perception',
   'Maître Praticien — Symptômes physiques',
   'Hypnose Ericksonienne',
   'Protocole hypnotique de gestion des acouphènes chroniques. Travail sur la perception du son (volume, présence, gêne) plutôt que sur la cause physique. Apprentissage de la dissociation perceptive et installation d''un filtre inconscient. Complément à un suivi ORL.',
   '4-6 séances de 60 min',
   'Avancé',
   ARRAY['acouphènes', 'perception', 'son', 'dissociation', 'ORL'],
   '#5B8FB9',
   5,
   ARRAY['Réduire la perception du volume des acouphènes', 'Diminuer la gêne et l''anxiété associées', 'Installer un filtre perceptif inconscient', 'Améliorer la qualité de vie quotidienne'],
   'GS Formation — Maître Praticien Hypnose Module 2',
   ARRAY['Douleurs & psychosomatique', 'Anxiété & stress']
  ),
  (843,
   'Hypnose & Sommeil — Réinitialisation des cycles',
   'Maître Praticien — Sommeil',
   'Hypnose Ericksonienne',
   'Protocole de réinitialisation du sommeil pour insomnies chroniques. Travail sur l''endormissement, les réveils nocturnes, la qualité du sommeil profond, l''anxiété d''anticipation du coucher. Combine techniques de relaxation profonde et reconditionnement comportemental.',
   '3-4 séances de 60 min + auto-hypnose quotidienne',
   'Intermédiaire',
   ARRAY['insomnie', 'sommeil', 'endormissement', 'réveils', 'anxiété d''anticipation'],
   '#7C5CBF',
   4,
   ARRAY['Restaurer un endormissement rapide et naturel', 'Réduire les réveils nocturnes', 'Améliorer la qualité du sommeil profond', 'Lever l''anxiété d''anticipation du coucher', 'Apprendre l''auto-hypnose pour les soirs difficiles'],
   'GS Formation — Maître Praticien Hypnose Module 3',
   ARRAY['Sommeil & insomnie', 'Anxiété & stress']
  ),
  (844,
   'Hypnose & Trauma complexe — Approche douce',
   'Maître Praticien — Trauma',
   'Hypnose Ericksonienne',
   'Approche hypnotique douce et sécurisée du trauma complexe. Pas de revivification directe (risque de retraumatisation). Travail par dissociation, métaphore et ressources. Préparation rigoureuse avec stabilisation émotionnelle. Pluridisciplinaire avec psychologue/psychiatre.',
   '8-12 séances de 75 min',
   'Avancé',
   ARRAY['trauma', 'PTSD', 'TSPT', 'dissociation', 'métaphore', 'stabilisation'],
   '#B85450',
   10,
   ARRAY['Stabiliser émotionnellement avant tout travail traumatique', 'Travailler par métaphore et dissociation (pas de revivification directe)', 'Restaurer le sentiment de sécurité intérieure', 'Réduire les symptômes (cauchemars, flashbacks, hypervigilance)', 'Reconstruire l''identité au-delà du trauma'],
   'GS Formation — Maître Praticien Hypnose Module 3',
   ARRAY['Trauma & deuil', 'Anxiété & stress']
  ),

  -- ===== MAÎTRE PRATICIEN PNL (850-855) =====
  (850,
   'Méta-modèle PNL — Précision linguistique',
   'Maître Praticien PNL — Linguistique',
   'PNL',
   'Outil linguistique fondamental de la PNL. 12 patterns de questionnement pour révéler les distorsions, généralisations et omissions du discours du client. Permet de remonter aux structures profondes du modèle du monde et de débloquer les croyances limitantes invisibles.',
   '60 min (intégrable à toute séance)',
   'Intermédiaire',
   ARRAY['méta-modèle', 'PNL', 'questionnement', 'distorsions', 'généralisations', 'Bandler', 'Grinder'],
   '#C8A030',
   1,
   ARRAY['Identifier les 12 patterns linguistiques limitants', 'Questionner pour révéler les structures profondes', 'Débloquer les croyances limitantes invisibles', 'Aider le client à enrichir sa carte du monde'],
   'GS Formation — Maître Praticien PNL',
   ARRAY['Anxiété & stress', 'Estime & confiance en soi']
  ),
  (851,
   'Niveaux logiques de Dilts — Réalignement complet',
   'Maître Praticien PNL — Alignement',
   'PNL',
   'Modèle de Robert Dilts en 6 niveaux : Environnement → Comportement → Capacités → Valeurs/Croyances → Identité → Mission/Spiritualité. Permet de localiser précisément la source d''un blocage et d''aligner tous les niveaux pour un changement profond et durable.',
   '90-120 min',
   'Avancé',
   ARRAY['Dilts', 'niveaux logiques', 'alignement', 'identité', 'valeurs', 'mission'],
   '#7C5CBF',
   1,
   ARRAY['Localiser le niveau précis du blocage', 'Aligner les 6 niveaux pour un changement durable', 'Travailler sur l''identité et la mission de vie', 'Résoudre les conflits internes entre niveaux'],
   'GS Formation — Maître Praticien PNL',
   ARRAY['Quête de sens & spiritualité', 'Décision & orientation', 'Estime & confiance en soi']
  ),
  (852,
   'Ligne du temps — Tad James',
   'Maître Praticien PNL — Temporalité',
   'PNL',
   'Outil de Tad James pour réorganiser la perception subjective du temps et libérer les émotions négatives accumulées (colère, tristesse, peur, blessure, culpabilité) à leur racine temporelle. Travail puissant sur les mémoires douloureuses sans les revivre.',
   '90-120 min',
   'Avancé',
   ARRAY['ligne du temps', 'Tad James', 'temporalité', 'mémoires', 'émotions négatives', 'racine'],
   '#7C5CBF',
   1,
   ARRAY['Cartographier la perception subjective du temps', 'Localiser la racine temporelle des émotions négatives', 'Libérer les 5 émotions fondamentales à leur racine', 'Réorganiser les ressources sur la ligne du temps'],
   'GS Formation — Maître Praticien PNL',
   ARRAY['Trauma & deuil', 'Anxiété & stress', 'Estime & confiance en soi']
  ),
  (853,
   'Stratégies d''excellence — Modélisation',
   'Maître Praticien PNL — Modélisation',
   'PNL',
   'Art de la modélisation PNL : décortiquer la stratégie inconsciente d''une personne qui excelle dans un domaine et la reproduire chez le client. Modélisation des stratégies de motivation, créativité, décision, apprentissage, prise de parole, etc.',
   '2-3 séances de 90 min',
   'Avancé',
   ARRAY['modélisation', 'stratégies', 'excellence', 'TOTE', 'sub-modalités'],
   '#C8A030',
   3,
   ARRAY['Identifier la stratégie d''un modèle d''excellence', 'Décortiquer en sub-modalités V/A/K précises', 'Installer la stratégie chez le client', 'Mesurer les résultats par contraste avant/après'],
   'GS Formation — Maître Praticien PNL',
   ARRAY['Performance & examens', 'Procrastination & motivation', 'Décision & orientation']
  ),
  (854,
   'SCORE — Diagnostic systémique',
   'Maître Praticien PNL — Diagnostic',
   'PNL',
   'Modèle de diagnostic PNL en 5 positions : Symptôme, Cause, Objectif, Ressources, Effets. Permet une exploration systémique d''une problématique en évitant les analyses linéaires simplistes. Particulièrement efficace en début de suivi long.',
   '60 min',
   'Intermédiaire',
   ARRAY['SCORE', 'diagnostic', 'systémique', 'symptôme', 'cause', 'objectif', 'ressources', 'effets'],
   '#5B8FB9',
   1,
   ARRAY['Cartographier une problématique en 5 dimensions systémiques', 'Distinguer symptôme et cause profonde', 'Définir un objectif écologique', 'Identifier les ressources disponibles', 'Anticiper les effets du changement'],
   'GS Formation — Maître Praticien PNL',
   ARRAY['Anxiété & stress', 'Décision & orientation']
  ),

  -- ===== HYPNOSE ERICKSONIENNE AVANCÉE (860-865) =====
  (860,
   'Métaphore thérapeutique sur mesure',
   'Hypnose Erickson — Métaphore',
   'Hypnose Ericksonienne',
   'Construction d''une métaphore thérapeutique sur mesure pour le client, suivant la structure ericksonienne classique : situation initiale → personnage similaire au client → péripétie → ressources mobilisées → résolution → retour transformé. Permet le contournement total de la résistance consciente.',
   '60-90 min',
   'Avancé',
   ARRAY['métaphore', 'Erickson', 'sur mesure', 'résistance', 'inconscient', 'isomorphisme'],
   '#C8A030',
   1,
   ARRAY['Construire une métaphore en isomorphisme avec la situation client', 'Contourner totalement la résistance consciente', 'Mobiliser les ressources inconscientes', 'Susciter le changement sans confrontation'],
   'GS Formation — Hypnose Ericksonienne Praticien V2',
   ARRAY['Anxiété & stress', 'Trauma & deuil', 'Phobies & peurs']
  ),
  (861,
   'Confusion technique — Briser les patterns',
   'Hypnose Erickson — Confusion',
   'Hypnose Ericksonienne',
   'Technique avancée de confusion (confusion d''Erickson) pour briser les patterns de pensée rigides et accélérer l''entrée en transe profonde. Saturation cognitive par paradoxes, ambiguïtés et changements de référentiel. Particulièrement efficace avec les clients très mentaux ou résistants.',
   '15-30 min (intégré à induction)',
   'Avancé',
   ARRAY['confusion', 'Erickson', 'paradoxe', 'patterns', 'résistant', 'mental'],
   '#5B8FB9',
   1,
   ARRAY['Saturer le mental conscient par confusion contrôlée', 'Briser les patterns de pensée rigides', 'Accélérer l''entrée en transe profonde', 'Travailler avec les clients très mentaux'],
   'GS Formation — Hypnose Ericksonienne Praticien V2',
   ARRAY['Anxiété & stress', 'Procrastination & motivation']
  ),
  (862,
   'Suggestions paradoxales & prescription du symptôme',
   'Hypnose Erickson — Paradoxe',
   'Hypnose Ericksonienne',
   'Prescription paradoxale du symptôme (héritage d''Erickson et Frankl) : demander au client d''amplifier ou de ritualiser le symptôme dont il veut se débarrasser. Court-circuite la résistance inconsciente et fait disparaître le symptôme par la conscience qui le sature.',
   '60 min',
   'Avancé',
   ARRAY['paradoxe', 'prescription', 'symptôme', 'Frankl', 'résistance', 'ritualisation'],
   '#B85450',
   1,
   ARRAY['Court-circuiter la résistance par paradoxe', 'Faire disparaître le symptôme par sa propre amplification', 'Restaurer le sentiment de contrôle du client', 'Briser les automatismes par ritualisation'],
   'GS Formation — Hypnose Ericksonienne Praticien V2',
   ARRAY['Anxiété & stress', 'Phobies & peurs', 'Procrastination & motivation']
  ),

  -- ===== OUTILS COMBINÉS PNL + HYPNOSE (870-873) =====
  (870,
   'Swish — Reconditionnement visuel rapide',
   'PNL & Hypnose Tech — Swish',
   'PNL',
   'Technique PNL classique de reconditionnement visuel rapide. Le client visualise l''image déclencheuse puis la « swish » avec une image de soi désirée. 5-7 répétitions suffisent à briser le pattern automatique. Très efficace pour habitudes, tics, comportements compulsifs ponctuels.',
   '20-30 min',
   'Intermédiaire',
   ARRAY['swish', 'PNL', 'reconditionnement', 'visuel', 'rapide', 'pattern'],
   '#C8A030',
   1,
   ARRAY['Briser un pattern visuel automatique en 20 min', 'Reconditionner la réponse à un déclencheur précis', 'Installer une image de soi désirée comme nouvelle réponse', 'Effet immédiat et mesurable'],
   'GS Formation — PNL & Hypnose Tech V3',
   ARRAY['Phobies & peurs', 'Procrastination & motivation', 'Estime & confiance en soi']
  ),
  (871,
   'Ancrage de ressources — Multimodal',
   'PNL & Hypnose Tech — Ancrage',
   'PNL',
   'Création d''ancres kinesthésiques, auditives ou visuelles pour réactiver à volonté un état ressource (calme, confiance, focus). Combinaison de plusieurs ancres pour effet potentialisé. Utilisable en autonomie après installation.',
   '30-45 min',
   'Débutant',
   ARRAY['ancrage', 'ressources', 'multimodal', 'PNL', 'autonomie'],
   '#2E8A7B',
   1,
   ARRAY['Identifier les états ressources disponibles', 'Créer des ancres kinesthésiques, auditives, visuelles', 'Combiner plusieurs ancres pour effet potentialisé', 'Permettre l''auto-déclenchement au quotidien'],
   'GS Formation — PNL & Hypnose Tech V3',
   ARRAY['Anxiété & stress', 'Performance & examens', 'Prise de parole']
  ),
  (872,
   'Recadrage en 6 étapes — Intention positive',
   'PNL & Hypnose Tech — Recadrage',
   'PNL',
   'Recadrage en 6 étapes de la PNL : identifier le comportement problématique, contacter la partie responsable, identifier l''intention positive, générer 3 alternatives, vérifier l''écologie, valider l''intégration. Permet de transformer un comportement gênant tout en préservant son intention positive.',
   '60-75 min',
   'Intermédiaire',
   ARRAY['recadrage', '6 étapes', 'intention positive', 'parts internes', 'PNL'],
   '#7C5CBF',
   1,
   ARRAY['Contacter la partie inconsciente responsable du comportement', 'Identifier son intention positive cachée', 'Générer des alternatives qui préservent cette intention', 'Vérifier l''écologie et valider l''intégration'],
   'GS Formation — PNL & Hypnose Tech V3',
   ARRAY['Conflits & communication', 'Anxiété & stress', 'Estime & confiance en soi']
  )
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  practice = EXCLUDED.practice,
  description = EXCLUDED.description,
  duration = EXCLUDED.duration,
  level = EXCLUDED.level,
  tags = EXCLUDED.tags,
  color = EXCLUDED.color,
  sessions = EXCLUDED.sessions,
  objectives = EXCLUDED.objectives,
  source = EXCLUDED.source,
  motifs = EXCLUDED.motifs;
