-- Seed protocoles Praticien Hypnose Ericksonienne (couverture exhaustive)
-- IDs : 900-926 (27 protocoles)
-- Source : GS Formation — Hypnose Ericksonienne Praticien V2

INSERT INTO public.protocols (id, name, category, practice, description, duration, level, tags, color, sessions, objectives, source, motifs)
VALUES
  (900,
   'Catalepsie du bras — Convicteur & approfondissement',
   'Praticien — Phénomène hypnotique',
   'Hypnose Ericksonienne',
   'Phénomène hypnotique classique : le bras du client devient cataleptique (rigide ou flottant) sous suggestion. Sert de convicteur de profondeur de transe et de tremplin pour approfondir l''état hypnotique.',
   '10-15 min (intégré)',
   'Intermédiaire',
   ARRAY['hypnose', 'catalepsie', 'convicteur', 'phénomène', 'approfondissement'],
   '#7C5CBF',
   1,
   ARRAY['Vérifier objectivement la profondeur de transe', 'Renforcer la conviction du client en sa transe', 'Approfondir l''état hypnotique', 'Préparer l''accès aux phénomènes plus complexes'],
   'GS Formation — Praticien Hypnose Ericksonienne',
   ARRAY['Anxiété & stress']
  ),
  (901,
   'Lévitation de la main — Induction Erickson',
   'Praticien — Induction',
   'Hypnose Ericksonienne',
   'Induction emblématique d''Erickson : la main du client se soulève seule, indépendamment de sa volonté. Approche permissive et fascinante. Idéale pour clients curieux et créatifs.',
   '15-25 min',
   'Intermédiaire',
   ARRAY['hypnose', 'induction', 'lévitation main', 'Erickson', 'idéomoteur'],
   '#C8A030',
   1,
   ARRAY['Induire la transe par mouvement idéomoteur', 'Susciter la fascination thérapeutique', 'Démontrer la puissance de l''inconscient', 'Préparer un travail thérapeutique avancé'],
   'GS Formation — Praticien Hypnose Ericksonienne',
   ARRAY['Anxiété & stress']
  ),
  (902,
   'Lévitation du bras — Variante avancée',
   'Praticien — Induction',
   'Hypnose Ericksonienne',
   'Variante de la lévitation : le bras entier se soulève. Permet d''atteindre une transe plus profonde par investissement moteur plus important. Convicteur très puissant.',
   '15-25 min',
   'Avancé',
   ARRAY['hypnose', 'induction', 'lévitation bras', 'Erickson', 'profondeur'],
   '#C8A030',
   1,
   ARRAY['Induire une transe profonde rapidement', 'Convicteur puissant pour clients résistants', 'Préparer le travail somnambulique', 'Variante créative de l''induction Erickson'],
   'GS Formation — Praticien Hypnose Ericksonienne',
   ARRAY['Anxiété & stress']
  ),
  (903,
   'Signaling idéomoteur — Communication inconsciente',
   'Praticien — Communication',
   'Hypnose Ericksonienne',
   'Communication directe avec l''inconscient via signaux idéomoteurs (doigts, tête, main). Méthode indirecte (laisse l''inconscient choisir le signal) ou directe (le praticien attribue les signaux). Outil de dialogue thérapeutique en transe.',
   '20-30 min (intégré)',
   'Avancé',
   ARRAY['hypnose', 'idéomoteur', 'signaling', 'inconscient', 'dialogue'],
   '#5B8FB9',
   1,
   ARRAY['Établir une communication oui/non avec l''inconscient', 'Vérifier l''accord d''une partie inconsciente', 'Faciliter le travail des parties (recadrage 6 étapes)', 'Outil indispensable du Praticien Erickson'],
   'GS Formation — Praticien Hypnose Ericksonienne',
   ARRAY['Anxiété & stress', 'Estime & confiance en soi']
  ),
  (904,
   'Amnésie post-hypnotique — 3 méthodes',
   'Praticien — Phénomène hypnotique',
   'Hypnose Ericksonienne',
   'Suggestion d''amnésie pour le contenu de la séance : 3 méthodes (suggestions verbales directes, mise entre parenthèses, redirection de l''attention). Permet à l''inconscient de travailler sans interférence consciente.',
   '5-10 min (en fin de séance)',
   'Avancé',
   ARRAY['hypnose', 'amnésie', 'post-hypnotique', 'inconscient', 'protection'],
   '#1B2D47',
   1,
   ARRAY['Faciliter le travail inconscient post-séance', 'Protéger un travail délicat de l''analyse consciente', 'Renforcer l''effet thérapeutique', 'Maîtriser les 3 méthodes d''amnésie'],
   'GS Formation — Praticien Hypnose Ericksonienne',
   ARRAY['Anxiété & stress']
  ),
  (905,
   'Travail sans contenu — Hypnose pure',
   'Praticien — Approche',
   'Hypnose Ericksonienne',
   'Approche ericksonienne radicale : induire la transe sans connaître le problème, laisser l''inconscient travailler en silence, sortir sans débrief. Le résultat émerge sans intervention consciente du praticien.',
   '45-60 min',
   'Avancé',
   ARRAY['hypnose', 'sans contenu', 'inconscient', 'silence', 'Erickson'],
   '#7C5CBF',
   1,
   ARRAY['Faire confiance à l''inconscient sans diriger', 'Travailler avec un client qui ne souhaite pas verbaliser', 'Approche radicalement permissive', 'Outil avancé de praticien expérimenté'],
   'GS Formation — Praticien Hypnose Ericksonienne',
   ARRAY['Anxiété & stress', 'Trauma & deuil']
  ),
  (906,
   'Suggestions post-hypnotiques — Emballage cadeau',
   'Praticien — Suggestion',
   'Hypnose Ericksonienne',
   'Insertion de suggestions post-hypnotiques par technique de l''emballage cadeau : la suggestion est encapsulée dans un récit, une métaphore, ou un geste rituel. Activation différée dans une situation future précise.',
   '15-20 min (intégré)',
   'Intermédiaire',
   ARRAY['hypnose', 'post-hypnotique', 'emballage cadeau', 'suggestion', 'différé'],
   '#C8A030',
   1,
   ARRAY['Programmer un changement comportemental futur', 'Insérer une suggestion résistante à l''oubli', 'Activation contextuelle (situation déclenchante)', 'Renforcer le travail thérapeutique post-séance'],
   'GS Formation — Praticien Hypnose Ericksonienne',
   ARRAY['Anxiété & stress', 'Estime & confiance en soi']
  ),
  (907,
   'Yes set — Acceptation cumulée',
   'Praticien — Pattern Milton',
   'Hypnose Ericksonienne',
   'Pattern Milton : empilement de truismes acceptés par le client (« vous êtes assis, vous m''écoutez, vous respirez... »). Crée un état d''acquiescement inconscient qui prépare à l''acceptation de la suggestion thérapeutique.',
   '5-10 min (intégré à l''induction)',
   'Débutant',
   ARRAY['hypnose', 'yes set', 'Milton', 'acquiescement', 'truisme'],
   '#2E8A7B',
   1,
   ARRAY['Préparer l''acceptation d''une suggestion clé', 'Établir un rapport inconscient', 'Faciliter l''entrée en transe', 'Outil quotidien du praticien hypnose'],
   'GS Formation — Praticien Hypnose Ericksonienne',
   ARRAY['Anxiété & stress']
  ),
  (908,
   'Induction couvrant tous les possibles',
   'Praticien — Induction',
   'Hypnose Ericksonienne',
   'Induction permissive qui anticipe et inclut toutes les réactions possibles du client (« peut-être vos paupières deviennent lourdes, ou peut-être vous ressentez une chaleur, ou peut-être... »). Aucune résistance possible.',
   '15-20 min',
   'Intermédiaire',
   ARRAY['hypnose', 'induction', 'permissive', 'tous possibles', 'Erickson'],
   '#7C5CBF',
   1,
   ARRAY['Induire la transe avec un client résistant', 'Éviter toute possibilité d''échec apparent', 'Approche radicalement permissive', 'Outil avancé pour clients méfiants'],
   'GS Formation — Praticien Hypnose Ericksonienne',
   ARRAY['Anxiété & stress']
  ),
  (909,
   'Induction par autorisation',
   'Praticien — Induction',
   'Hypnose Ericksonienne',
   'Induction qui donne explicitement la permission au client d''entrer en transe à son rythme, à sa façon, sans pression. Particulièrement adaptée aux clients hyper-contrôlants ou anxieux.',
   '15-25 min',
   'Intermédiaire',
   ARRAY['hypnose', 'induction', 'autorisation', 'permission', 'rythme'],
   '#7C5CBF',
   1,
   ARRAY['Lever les résistances liées au contrôle', 'Sécuriser les clients anxieux face à l''hypnose', 'Personnaliser l''entrée en transe', 'Renforcer l''autonomie du client'],
   'GS Formation — Praticien Hypnose Ericksonienne',
   ARRAY['Anxiété & stress']
  ),
  (910,
   'Dissociation conscient/inconscient + double lien',
   'Praticien — Pattern Milton',
   'Hypnose Ericksonienne',
   'Technique linguistique de dissociation : « pendant que votre conscient écoute ma voix, votre inconscient travaille en silence ». Combinée au double lien (« vous pouvez entrer en transe maintenant ou dans 30 secondes »), garantit l''entrée en transe.',
   '10-15 min (intégré)',
   'Avancé',
   ARRAY['hypnose', 'dissociation', 'double lien', 'Milton', 'inconscient'],
   '#5B8FB9',
   1,
   ARRAY['Dissocier conscient et inconscient pour libérer le travail', 'Garantir l''induction par double lien', 'Maîtriser les patterns Milton avancés', 'Outil quotidien du Praticien'],
   'GS Formation — Praticien Hypnose Ericksonienne',
   ARRAY['Anxiété & stress']
  ),
  (911,
   'Expressions composées — Liens hypnotiques',
   'Praticien — Pattern Milton',
   'Hypnose Ericksonienne',
   'Constructions linguistiques qui lient deux propositions par « pendant que », « alors que », « à mesure que »... Crée une cause-effet hypnotique qui facilite l''acceptation de la seconde proposition.',
   '5-10 min (intégré)',
   'Intermédiaire',
   ARRAY['hypnose', 'expressions composées', 'Milton', 'liens', 'cause-effet'],
   '#2E8A7B',
   1,
   ARRAY['Maîtriser les liens hypnotiques de cause-effet', 'Faciliter l''acceptation des suggestions', 'Fluidifier le discours hypnotique', 'Pattern Milton de base à automatiser'],
   'GS Formation — Praticien Hypnose Ericksonienne',
   ARRAY['Anxiété & stress']
  ),
  (912,
   'Métaphore des 4 archétypes — Voyage du héros',
   'Praticien — Métaphore',
   'Hypnose Ericksonienne',
   'Métaphore structurée autour de 4 archétypes universels (Guerrier, Magicien, Souverain, Amant — Moore & Gillette). Le client traverse le récit et active l''archétype manquant ou déséquilibré.',
   '60-90 min',
   'Avancé',
   ARRAY['hypnose', 'métaphore', 'archétypes', 'Jung', 'voyage héros'],
   '#7C5CBF',
   1,
   ARRAY['Activer un archétype manquant ou déséquilibré', 'Travail identitaire profond par récit', 'Approche jungienne en hypnose ericksonienne', 'Particulièrement efficace pour les hommes en quête de sens'],
   'GS Formation — Praticien Hypnose Ericksonienne',
   ARRAY['Quête de sens & spiritualité', 'Estime & confiance en soi']
  ),
  (913,
   'Formule magique pour construire une métaphore',
   'Praticien — Métaphore',
   'Hypnose Ericksonienne',
   'Méthode pas-à-pas pour construire une métaphore thérapeutique : isomorphisme problème/récit, choix de l''univers, héros, obstacle, allié, ressource, transformation. Outil pédagogique pour le praticien.',
   '30-45 min (préparation)',
   'Intermédiaire',
   ARRAY['hypnose', 'métaphore', 'construction', 'isomorphisme', 'pédagogie'],
   '#C8A030',
   1,
   ARRAY['Construire une métaphore sur mesure pour un client', 'Maîtriser l''isomorphisme problème/récit', 'Outil pédagogique reproductible', 'Formaliser sa créativité métaphorique'],
   'GS Formation — Praticien Hypnose Ericksonienne',
   ARRAY['Anxiété & stress', 'Trauma & deuil']
  ),
  (914,
   'Le nettoyage de printemps — Libération symbolique',
   'Praticien — Nettoyage',
   'Hypnose Ericksonienne',
   'Métaphore puissante de nettoyage intérieur : le client visualise sa maison intérieure, identifie ce qui doit partir (objets, mémoires, croyances), procède au tri et au nettoyage symbolique. Renouveau intérieur.',
   '60-75 min',
   'Intermédiaire',
   ARRAY['hypnose', 'nettoyage printemps', 'libération', 'symbolique', 'renouveau'],
   '#2E8A7B',
   1,
   ARRAY['Libérer symboliquement les charges anciennes', 'Faire l''inventaire de ce qui doit rester ou partir', 'Renouveler l''espace intérieur', 'Préparer un nouveau cycle de vie'],
   'GS Formation — Praticien Hypnose Ericksonienne',
   ARRAY['Anxiété & stress', 'Trauma & deuil', 'Burn-out & fatigue']
  ),
  (915,
   'Transformation Instantanée — Changement immédiat',
   'Praticien — Transformation',
   'Hypnose Ericksonienne',
   'Protocole rapide de transformation d''un état ou d''un comportement en transe profonde. Visualisation de soi transformé, association immédiate, ancrage. Effet souvent ressenti dès la sortie de séance.',
   '30-45 min',
   'Avancé',
   ARRAY['hypnose', 'transformation', 'instantanée', 'changement', 'rapide'],
   '#B85450',
   1,
   ARRAY['Produire un changement ressenti immédiatement', 'Renforcer la conviction du client en sa propre capacité', 'Outil de démarrage thérapeutique percutant', 'Préparer un travail plus profond'],
   'GS Formation — Praticien Hypnose Ericksonienne',
   ARRAY['Estime & confiance en soi', 'Anxiété & stress']
  ),
  (916,
   'Méthode du SUPER objectif — Anamnèse structurée',
   'Praticien — Anamnèse',
   'Hypnose Ericksonienne',
   'Méthode d''anamnèse SUPER : Spécifique, Utile, Positif, Écologique, Réaliste. Structure de premier entretien pour formaliser l''objectif thérapeutique de manière précise et engageante.',
   '60 min (1ère séance)',
   'Débutant',
   ARRAY['hypnose', 'anamnèse', 'SUPER', 'objectif', 'premier entretien'],
   '#5B8FB9',
   1,
   ARRAY['Formaliser un objectif thérapeutique SMART', 'Vérifier l''écologie du changement souhaité', 'Engager le client dans une démarche claire', 'Outil de premier entretien standardisé'],
   'GS Formation — Praticien Hypnose Ericksonienne',
   ARRAY['Estime & confiance en soi', 'Anxiété & stress']
  ),
  (917,
   'Distorsion du temps — Manipulation subjective',
   'Praticien — Phénomène hypnotique',
   'Hypnose Ericksonienne',
   'Phénomène hypnotique d''altération de la perception subjective du temps : 5 minutes ressenties comme 1 heure (expansion) ou 1 heure ressentie comme 5 minutes (contraction). Utile pour douleur chronique et apprentissage accéléré.',
   '20-30 min (intégré)',
   'Avancé',
   ARRAY['hypnose', 'distorsion temps', 'subjectif', 'douleur', 'apprentissage'],
   '#1B2D47',
   1,
   ARRAY['Allonger un moment de plaisir ou de ressource', 'Raccourcir une douleur ou un examen redouté', 'Accélérer un apprentissage par expansion temporelle', 'Outil avancé de praticien expérimenté'],
   'GS Formation — Praticien Hypnose Ericksonienne',
   ARRAY['Douleurs & psychosomatique', 'Performance & examens']
  ),
  (918,
   'Installer une permission — Lever un interdit',
   'Praticien — Permission',
   'Hypnose Ericksonienne',
   'Protocole pour lever un interdit interne hérité (ne pas réussir, ne pas être heureux, ne pas dire non). Le praticien donne en transe la permission explicite et solennelle. Particulièrement puissant pour les injonctions parentales.',
   '45-60 min',
   'Intermédiaire',
   ARRAY['hypnose', 'permission', 'interdit', 'injonction', 'parental'],
   '#C8A030',
   1,
   ARRAY['Identifier l''interdit hérité', 'Donner la permission solennelle en transe', 'Lever une injonction parentale ou sociale', 'Libérer une potentialité bloquée'],
   'GS Formation — Praticien Hypnose Ericksonienne',
   ARRAY['Estime & confiance en soi']
  ),
  (919,
   'Augmentation de l''état — Amplification ressource',
   'Praticien — Ressource',
   'Hypnose Ericksonienne',
   'Technique d''amplification d''un état ressource (joie, calme, force) en transe. Le praticien guide la montée en intensité jusqu''au pic, puis ancre l''état. Particulièrement utile en préparation d''un événement.',
   '20-30 min (intégré)',
   'Intermédiaire',
   ARRAY['hypnose', 'augmentation', 'état', 'amplification', 'ressource'],
   '#C8A030',
   1,
   ARRAY['Amplifier un état ressource jusqu''à son maximum', 'Ancrer le pic d''intensité', 'Préparer une performance ou un examen', 'Renforcer la conviction de la ressource intérieure'],
   'GS Formation — Praticien Hypnose Ericksonienne',
   ARRAY['Estime & confiance en soi', 'Performance & examens']
  ),
  (920,
   'Technique Erickson-Rossi — Idéodynamique',
   'Praticien — Idéodynamique',
   'Hypnose Ericksonienne',
   'Protocole co-créé par Erickson et Rossi : utilisation des signaux idéomoteurs pour explorer les ressources inconscientes, dialoguer avec une partie symptomatique, et co-construire la solution. Approche profondément respectueuse.',
   '60-90 min',
   'Avancé',
   ARRAY['hypnose', 'Erickson-Rossi', 'idéodynamique', 'parties', 'co-construction'],
   '#5B8FB9',
   1,
   ARRAY['Dialoguer avec une partie symptomatique via signaling', 'Explorer les ressources inconscientes', 'Co-construire la solution avec l''inconscient', 'Outil avancé de praticien expérimenté'],
   'GS Formation — Praticien Hypnose Ericksonienne',
   ARRAY['Anxiété & stress', 'Trauma & deuil']
  ),
  (921,
   'Régression en âge — Protocole complet',
   'Praticien — Régression',
   'Hypnose Ericksonienne',
   'Protocole complet de régression en âge : contrat de sécurité, induction profonde, pont d''affect, retour à l''événement, recadrage avec ressources adultes, pont sur le futur. Différent de la régression Elman par l''approche progressive et permissive.',
   '60-90 min',
   'Avancé',
   ARRAY['hypnose', 'régression', 'âge', 'recadrage', 'enfant intérieur'],
   '#7C5CBF',
   1,
   ARRAY['Remonter à un événement antérieur identifié', 'Recadrer avec les ressources adultes actuelles', 'Libérer une émotion ancienne bloquante', 'Reconstruire un schéma identitaire'],
   'GS Formation — Praticien Hypnose Ericksonienne',
   ARRAY['Trauma & deuil', 'Estime & confiance en soi']
  ),
  (922,
   'Processus pour les traumatismes — Approche douce',
   'Praticien — Trauma',
   'Hypnose Ericksonienne',
   'Protocole hypnotique de traitement du trauma sans revivification directe : stabilisation, écran protecteur, dissociation, recadrage symbolique, reconstruction. Adapté pour traumatismes simples et modérés.',
   '60-90 min × 3-6 séances',
   'Avancé',
   ARRAY['hypnose', 'trauma', 'douce', 'écran protecteur', 'dissociation'],
   '#B85450',
   4,
   ARRAY['Traiter un trauma sans revivification directe', 'Maintenir le client en sécurité émotionnelle', 'Dissocier la mémoire du ressenti actuel', 'Reconstruire l''identité au-delà du trauma'],
   'GS Formation — Praticien Hypnose Ericksonienne',
   ARRAY['Trauma & deuil', 'Anxiété & stress']
  ),
  (923,
   'Thérapie Ordalique — Paradoxe ritualisé',
   'Praticien — Paradoxe',
   'Hypnose Ericksonienne',
   'Méthode ericksonienne d''épreuve : le client doit accomplir une tâche pénible chaque fois que le symptôme apparaît (lever 30 min plus tôt, écrire 20 pages...). L''inconscient préfère renoncer au symptôme plutôt que subir l''ordalie.',
   '1-3 séances de 60 min',
   'Avancé',
   ARRAY['hypnose', 'ordalique', 'épreuve', 'paradoxe', 'Erickson'],
   '#1B2D47',
   1,
   ARRAY['Forcer l''inconscient à choisir entre symptôme et épreuve', 'Outil radical pour symptômes résistants', 'Cadre ritualisé strict et engageant', 'Approche emblématique d''Erickson'],
   'GS Formation — Praticien Hypnose Ericksonienne',
   ARRAY['Anxiété & stress', 'Addictions']
  ),
  (924,
   'Contrôler la douleur — Protocole complet',
   'Praticien — Douleur',
   'Hypnose Ericksonienne',
   'Protocole complet de gestion de la douleur en hypnose : évaluation sensorielle (SUDS, qualité), choix de la technique (gant anesthésique, transformation, déplacement, dissociation, distorsion temps), application, ancrage, autonomisation.',
   '45-60 min × 3-5 séances',
   'Avancé',
   ARRAY['hypnose', 'douleur', 'analgésie', 'gant', 'dissociation', 'SUDS'],
   '#B85450',
   4,
   ARRAY['Évaluer précisément la douleur (qualité, intensité, durée)', 'Choisir la technique adaptée au type de douleur', 'Réduire ou supprimer la perception douloureuse', 'Apprendre l''auto-hypnose antalgique au client'],
   'GS Formation — Praticien Hypnose Ericksonienne',
   ARRAY['Douleurs & psychosomatique']
  ),
  (925,
   'Recadrage en transe — Reframing profond',
   'Praticien — Recadrage',
   'Hypnose Ericksonienne',
   'Recadrage classique exécuté en transe profonde : changement de signification ou de contexte d''un événement ou comportement. Plus puissant que le recadrage en état conscient car les nouvelles significations sont ancrées au niveau inconscient.',
   '45-60 min',
   'Intermédiaire',
   ARRAY['hypnose', 'recadrage', 'reframing', 'transe', 'signification'],
   '#7C5CBF',
   1,
   ARRAY['Modifier la signification d''un événement passé', 'Modifier le contexte de perception d''un comportement', 'Ancrer le nouveau cadre au niveau inconscient', 'Outil quotidien du Praticien Erickson'],
   'GS Formation — Praticien Hypnose Ericksonienne',
   ARRAY['Anxiété & stress', 'Estime & confiance en soi']
  ),
  (926,
   'Processus de peur des Sénois — Apprivoisement onirique',
   'Praticien — Peur',
   'Hypnose Ericksonienne',
   'Inspiré du peuple Senoi (Malaisie) qui apprend à ses enfants à dialoguer avec leurs cauchemars. Le client en transe revient à son rêve/cauchemar, dialogue avec la figure menaçante, négocie un cadeau ou une transformation.',
   '60 min',
   'Intermédiaire',
   ARRAY['hypnose', 'Sénois', 'peur', 'cauchemar', 'rêve', 'apprivoisement'],
   '#7C5CBF',
   1,
   ARRAY['Transformer un cauchemar récurrent', 'Apprivoiser une figure de peur', 'Dialoguer avec l''inconscient onirique', 'Approche ethno-hypnotique douce et créative'],
   'GS Formation — Praticien Hypnose Ericksonienne',
   ARRAY['Phobies & peurs', 'Sommeil & insomnie']
  )
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  practice = EXCLUDED.practice,
  description = EXCLUDED.description,
  duration = EXCLUDED.duration,
  level = EXCLUDED.level,
  tags = EXCLUDED.tags,
  color = EXCLUDED.color,
  sessions = EXCLUDED.sessions,
  objectives = EXCLUDED.objectives,
  source = EXCLUDED.source,
  motifs = EXCLUDED.motifs;
