-- Seed protocoles Tabac — outils & techniques spécifiques
-- IDs : 804-809 (6 protocoles complémentaires aux 4 programmes 800-803)
-- Source : GS Formation — Module Tabacs V2

INSERT INTO public.protocols (id, name, category, practice, description, duration, level, tags, color, sessions, objectives, source, motifs)
VALUES
  (804,
   'Tests de dépendance & motivation tabac — Fagerström/Lagrue/Richmond',
   'Tabac — Évaluation',
   'Hypnose Ericksonienne',
   'Batterie de tests validés pour évaluer le fumeur en première séance : Fagerström (dépendance physique 0-10), Lagrue & Legeron (motivation à l''arrêt), Richmond (motivation alternative), HAD (anxiété-dépression). Permet d''adapter le programme et de prédire la réussite.',
   '30-45 min (1ère séance)',
   'Intermédiaire',
   ARRAY['tabac', 'Fagerström', 'Lagrue', 'Richmond', 'HAD', 'évaluation', 'dépendance'],
   '#5B8FB9',
   1,
   ARRAY['Évaluer la dépendance physique (Fagerström 0-10)', 'Mesurer la motivation à l''arrêt (Lagrue & Legeron)', 'Cartographie psychologique (Richmond + HAD)', 'Adapter le programme à la sévérité'],
   'GS Formation — Module Tabacs V2',
   ARRAY['Addictions']
  ),
  (805,
   'Casser les 12 croyances du fumeur',
   'Tabac — Croyances',
   'Hypnose Ericksonienne',
   'Travail systématique de recadrage des 12 croyances classiques du fumeur : « la cigarette est un plaisir », « ça me calme », « je suis libre de fumer », « il faut de la volonté », « je vais grossir », « je serai insupportable », « il y a un bon moment »... Chaque croyance déconstruite avec contre-exemples.',
   '60-90 min',
   'Intermédiaire',
   ARRAY['tabac', 'croyances', 'recadrage', 'volonté', 'plaisir', 'liberté'],
   '#C8A030',
   1,
   ARRAY['Identifier les croyances limitantes du client', 'Déconstruire systématiquement les 12 croyances classiques', 'Recadrer avec contre-exemples solides', 'Préparer l''engagement au sevrage'],
   'GS Formation — Module Tabacs V2',
   ARRAY['Addictions']
  ),
  (806,
   'Schéma émotionnel & intention positive — Tabac',
   'Tabac — Émotionnel',
   'Hypnose Ericksonienne',
   'Travail en transe sur le schéma émotionnel répétitif qui pousse à fumer : déclencheur émotionnel → réflexe cigarette → soulagement temporaire → culpabilité. Identification de l''intention positive du comportement (gérer stress, peur, ennui, colère). Substitution par alternative saine.',
   '60 min',
   'Avancé',
   ARRAY['tabac', 'schéma émotionnel', 'intention positive', 'déclencheurs', 'substitution'],
   '#B85450',
   1,
   ARRAY['Identifier le schéma émotionnel répétitif', 'Découvrir l''intention positive sous-jacente', 'Construire des alternatives comportementales', 'Ancrer la nouvelle réponse en transe'],
   'GS Formation — Module Tabacs V2',
   ARRAY['Addictions', 'Anxiété & stress']
  ),
  (807,
   'Visualisations tabac — Poison, nettoyage, victoire',
   'Tabac — Visualisations',
   'Hypnose Ericksonienne',
   'Suite de 3 visualisations en transe profonde : (1) Le tabac est un poison (perception cellulaire des dommages), (2) Nettoyage des toxines (purification corporelle progressive), (3) Victoire (visualisation du soi non-fumeur épanoui). Travail sensoriel puissant.',
   '60-75 min',
   'Avancé',
   ARRAY['tabac', 'visualisation', 'poison', 'nettoyage', 'victoire', 'transe'],
   '#7C5CBF',
   1,
   ARRAY['Visualiser sensoriellement les dégâts du tabac', 'Activer le nettoyage cellulaire en imagination', 'Ancrer l''image du soi victorieux non-fumeur', 'Renforcer la motivation par sensorialité'],
   'GS Formation — Module Tabacs V2',
   ARRAY['Addictions']
  ),
  (808,
   'Travail identitaire non-fumeur',
   'Tabac — Identité',
   'Hypnose Ericksonienne',
   'Travail au niveau identitaire (Niveaux logiques de Dilts) : passer de « Je suis un fumeur qui essaie d''arrêter » à « Je suis un non-fumeur ». Reconstruction du discours intérieur, ancrage de la nouvelle identité, projection dans le futur en tant que non-fumeur.',
   '60-90 min',
   'Avancé',
   ARRAY['tabac', 'identité', 'Dilts', 'non-fumeur', 'reconstruction'],
   '#2E8A7B',
   1,
   ARRAY['Distinguer « ne pas fumer » de « être non-fumeur »', 'Reconstruire l''identité au niveau Dilts', 'Ancrer le nouveau discours intérieur', 'Projeter dans le futur identité non-fumeur'],
   'GS Formation — Module Tabacs V2',
   ARRAY['Addictions', 'Estime & confiance en soi']
  ),
  (809,
   'Contrat moral d''arrêt + suivi 21 jours',
   'Tabac — Engagement',
   'Hypnose Ericksonienne',
   'Outil rituel d''engagement : signature solennelle d''un contrat moral d''arrêt, fixation de la date, programme d''activités alternatives, questionnaire de suivi à J+21 et M+3. Marque psychique forte du début de la nouvelle vie.',
   '20-30 min (en fin de programme)',
   'Intermédiaire',
   ARRAY['tabac', 'contrat moral', 'engagement', 'suivi', '21 jours'],
   '#E08550',
   1,
   ARRAY['Formaliser l''engagement par signature solennelle', 'Fixer la date précise d''arrêt', 'Construire le programme d''activités alternatives', 'Planifier le suivi J+21 et M+3'],
   'GS Formation — Module Tabacs V2',
   ARRAY['Addictions']
  )
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  practice = EXCLUDED.practice,
  description = EXCLUDED.description,
  duration = EXCLUDED.duration,
  level = EXCLUDED.level,
  tags = EXCLUDED.tags,
  color = EXCLUDED.color,
  sessions = EXCLUDED.sessions,
  objectives = EXCLUDED.objectives,
  source = EXCLUDED.source,
  motifs = EXCLUDED.motifs;
