-- Seed protocoles KIIKA Hammond (fiches détaillées Varinka Robert)
-- IDs : 600-674 (75 protocoles) — REMPLACENT les anciens Hammond 600-700
-- Source : KIIKA v3 — fiches détaillées par lot (Cercle 1 Noyau + Cercle 2 Anxiété/Sommeil/Douleur)

INSERT INTO public.protocols (id, name, category, practice, description, duration, level, tags, color, sessions, objectives, source, motifs)
VALUES
  (600,
   'Induction par escalier intérieur',
   'KIIKA — Induction',
   'Hypnose Ericksonienne',
   'Induction métaphorique douce par descente d''un escalier imaginaire, comptage de 10 à 1 avec dépose progressive des tensions corporelles. Convient à la majorité des patients en début de prise en charge.',
   '8 min',
   'Débutant',
   ARRAY['induction', 'escalier', 'comptage', 'imagerie de descente', 'fondamental', 'débutant'],
   '#7C5CBF',
   1,
   ARRAY['Imagerie kinesthésique', 'Comptage rythmé', 'Dépose progressive des tensions', 'Synchronisation avec la respiration'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-BASE-001',
   ARRAY['Anxiété & stress']
  ),
  (601,
   'Induction par fixation visuelle',
   'KIIKA — Induction',
   'Hypnose Ericksonienne',
   'Induction classique par focalisation du regard sur un point fixe (point au mur, flamme de bougie, doigt du thérapeute), avec installation progressive de la fatigue oculaire qui amène la fermeture spontanée des paupières.',
   '7 min',
   'Débutant',
   ARRAY['induction', 'fixation visuelle', 'fatigue oculaire', 'fermeture paupières', 'fondamental'],
   '#7C5CBF',
   1,
   ARRAY['Concentration soutenue', 'Fatigue physiologique des paupières', 'Suggestions ratifiantes', 'Lâcher-prise progressif'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-BASE-002',
   ARRAY['Anxiété & stress']
  ),
  (602,
   'Induction par relaxation progressive',
   'KIIKA — Induction',
   'Hypnose Ericksonienne',
   'Induction par balayage corporel descendant ou ascendant, en relaxant successivement chaque zone du corps. Méthode rassurante, transparente, particulièrement utile pour patients somatiques ou anxieux.',
   '12 min',
   'Débutant',
   ARRAY['induction', 'relaxation progressive', 'balayage corporel', 'kinesthésique', 'fondamental'],
   '#7C5CBF',
   1,
   ARRAY['Conscience corporelle', 'Relâchement musculaire progressif', 'Synchronisation respiratoire', 'Présence à soi'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-BASE-003',
   ARRAY['Anxiété & stress']
  ),
  (603,
   'Induction conversationnelle éricksonienne légère',
   'KIIKA — Induction',
   'Hypnose Ericksonienne',
   'Induction permissive par conversation orientée, utilisation de truismes, de sensations naturelles déjà présentes, et de suggestions indirectes. Sans annonce d''hypnose. Convient aux patients résistants ou défensifs.',
   '15 min',
   'Intermédiaire',
   ARRAY['induction', 'Erickson', 'conversationnelle', 'permissive', 'truismes', 'indirecte', 'résistance'],
   '#7C5CBF',
   1,
   ARRAY['Truismes (énoncés évidemment vrais)', 'Yes-set (enchaînement d''acquiescements)', 'Ratification progressive', 'Suggestions indirectes', 'Utilisation de ce qui se présente'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-BASE-004',
   ARRAY['Anxiété & stress']
  ),
  (604,
   'Induction par lévitation de la main',
   'KIIKA — Induction',
   'Hypnose Ericksonienne',
   'Induction kinesthésique avec démonstration : la main du patient se soulève apparemment toute seule sous l''effet de suggestions de légèreté. Ratification puissante de la transe pour patients qui ont besoin de preuves.',
   '10 min',
   'Intermédiaire',
   ARRAY['induction', 'lévitation', 'main', 'idéomoteur', 'ratification', 'dissociation', 'Erickson'],
   '#7C5CBF',
   1,
   ARRAY['Phénomène idéomoteur', 'Suggestions d''allègement progressif', 'Ratification par auto-observation', 'Dissociation main / volonté consciente'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-BASE-005',
   ARRAY['Anxiété & stress']
  ),
  (605,
   'Induction rapide par signal personnel',
   'KIIKA — Induction',
   'Hypnose Ericksonienne',
   'Induction de quelques secondes pour patients déjà entraînés, par activation d''un signal d''auto-induction préalablement installé (geste, respiration, mot-clé). Idéale pour les séances de suivi ou l''usage en autohypnose.',
   '2 min',
   'Intermédiaire',
   ARRAY['induction', 'rapide', 'signal', 'ancrage', 'autohypnose', 'suivi'],
   '#7C5CBF',
   1,
   ARRAY['Ancrage conditionné', 'Mémoire de transe', 'Économie de temps', 'Renforcement par usage'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-BASE-006',
   ARRAY['Anxiété & stress']
  ),
  (606,
   'Approfondissement par comptage descendant',
   'KIIKA — Approfondissement',
   'Hypnose Ericksonienne',
   'Approfondissement classique par comptage de 20 à 1, ou de 10 à 1, avec suggestion d''enfoncement progressif à chaque chiffre. Brique simple et fiable utilisable après n''importe quelle induction.',
   '4 min',
   'Débutant',
   ARRAY['approfondissement', 'comptage', 'fondamental', 'rythme'],
   '#7C5CBF',
   1,
   ARRAY['Rythme régulier', 'Suggestion d''enfoncement', 'Cumul progressif', 'Synchronisation respiratoire'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-BASE-007',
   ARRAY['Anxiété & stress']
  ),
  (607,
   'Approfondissement par fractionnement',
   'KIIKA — Approfondissement',
   'Hypnose Ericksonienne',
   'Approfondissement par cycles successifs de transe-éveil-retransition. À chaque cycle, la transe atteinte est plus profonde que la précédente. Très efficace pour patients qui résistent à un approfondissement linéaire.',
   '12 min',
   'Intermédiaire',
   ARRAY['approfondissement', 'fractionnement', 'cycles', 'Vogt'],
   '#7C5CBF',
   1,
   ARRAY['Effet de comparaison', 'Apprentissage par répétition', 'Confiance dans la réversibilité', 'Mémoire de la transe précédente'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-BASE-008',
   ARRAY['Anxiété & stress']
  ),
  (608,
   'Approfondissement par image de descente',
   'KIIKA — Approfondissement',
   'Hypnose Ericksonienne',
   'Approfondissement par imagerie kinesthésique de descente : ascenseur intérieur, racines qui s''enfoncent, plongée dans une eau calme. Choix de l''image selon le patient.',
   '6 min',
   'Débutant',
   ARRAY['approfondissement', 'imagerie', 'descente', 'ascenseur', 'racines', 'plongée'],
   '#7C5CBF',
   1,
   ARRAY['Imagerie multisensorielle', 'Synesthésie kinesthésique', 'Choix de la métaphore par le patient', 'Profondeur symbolique'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-BASE-009',
   ARRAY['Anxiété & stress']
  ),
  (609,
   'Approfondissement par ratification progressive',
   'KIIKA — Approfondissement',
   'Hypnose Ericksonienne',
   'Approfondissement par accumulation de ratifications : le thérapeute nomme des phénomènes hypnotiques observables ou subjectivement présents, et les utilise pour confirmer et amplifier la transe.',
   '8 min',
   'Avancé',
   ARRAY['approfondissement', 'ratification', 'Erickson', 'yes-set', 'subtil'],
   '#7C5CBF',
   1,
   ARRAY['Observation fine du patient', 'Accumulation de truismes ratifiants', 'Confirmation par auto-observation', 'Boucle de feedback positif'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-BASE-010',
   ARRAY['Anxiété & stress']
  ),
  (610,
   'Lieu sûr fondamental',
   'KIIKA — Lieu ressource',
   'Hypnose Ericksonienne',
   'Installation d''un lieu intérieur de sécurité absolue, accessible à tout moment. Pierre angulaire de tout travail hypnotique, particulièrement en contexte traumatique. À installer en première ou deuxième séance.',
   '20 min',
   'Débutant',
   ARRAY['lieu sûr', 'ressource', 'fondamental', 'trauma', 'ancrage', 'sécurité'],
   '#2E8A7B',
   1,
   ARRAY['Imagerie multisensorielle', 'Personnalisation totale', 'Ancrage gestuel associé', 'Renforcement par retours répétés'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-BASE-011',
   ARRAY['Anxiété & stress']
  ),
  (611,
   'Sanctuaire intérieur',
   'KIIKA — Lieu ressource',
   'Hypnose Ericksonienne',
   'Variante du lieu sûr orientée vers la dimension sacrée et spirituelle. Lieu de recueillement, de connexion à plus grand que soi. Particulièrement adapté à l''approche thérapeutique-spirituelle de KIIKA.',
   '25 min',
   'Intermédiaire',
   ARRAY['sanctuaire', 'sacré', 'spirituel', 'Ka', 'recueillement', 'lieu ressource'],
   '#2E8A7B',
   1,
   ARRAY['Imagerie sacrée non confessionnelle', 'Verticalité (sol-ciel)', 'Présence et silence', 'Connexion à plus grand que soi'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-BASE-012',
   ARRAY['Anxiété & stress']
  ),
  (612,
   'Jardin intérieur',
   'KIIKA — Lieu ressource',
   'Hypnose Ericksonienne',
   'Lieu ressource sous forme de jardin personnel, espace d''exploration et de soin. Permet le travail métaphorique sur la croissance, les saisons, les semis. Très utilisable avec enfants et adolescents.',
   '18 min',
   'Débutant',
   ARRAY['jardin', 'nature', 'croissance', 'lieu ressource', 'enfants', 'métaphore vivante'],
   '#2E8A7B',
   1,
   ARRAY['Imagerie naturelle', 'Métaphore de la croissance', 'Possibilité d''action (planter, arroser, cueillir)', 'Cycle des saisons'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-BASE-013',
   ARRAY['Anxiété & stress']
  ),
  (613,
   'Cabane refuge',
   'KIIKA — Lieu ressource',
   'Hypnose Ericksonienne',
   'Lieu ressource sous forme de cabane ou abri personnel : espace contenant, chaleureux, fortement délimité. Particulièrement adapté aux patients ayant besoin d''un sentiment de protection forte.',
   '15 min',
   'Débutant',
   ARRAY['cabane', 'refuge', 'abri', 'contenance', 'anxiété', 'protection'],
   '#2E8A7B',
   1,
   ARRAY['Délimitation forte', 'Chaleur et confort', 'Petite dimension protectrice', 'Contrôle d''accès'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-BASE-014',
   ARRAY['Anxiété & stress']
  ),
  (614,
   'Eau ressource',
   'KIIKA — Lieu ressource',
   'Hypnose Ericksonienne',
   'Lieu ressource organisé autour d''un élément aquatique (rivière, lac, mer, source, bain). Offre des qualités spécifiques : fluidité, contenance liquide, lavage symbolique, dépose des charges.',
   '18 min',
   'Débutant',
   ARRAY['eau', 'rivière', 'lac', 'mer', 'source', 'lieu ressource', 'fluidité'],
   '#2E8A7B',
   1,
   ARRAY['Qualité fluide et mouvante', 'Symbole de lavage et de renouvellement', 'Portage par l''élément', 'Sons apaisants de l''eau'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-BASE-015',
   ARRAY['Anxiété & stress']
  ),
  (615,
   'Ancre kinesthésique discrète',
   'KIIKA — Ancrage',
   'Hypnose Ericksonienne',
   'Installation d''un geste discret (pouce-index, main sur le sternum, paume sur le ventre) qui devient déclencheur d''un état ressource accessible en toute situation, y compris en public.',
   '10 min',
   'Débutant',
   ARRAY['ancrage', 'geste', 'kinesthésique', 'ressource accessible', 'fondamental'],
   '#C8A030',
   1,
   ARRAY['Association état-geste', 'Discrétion sociale', 'Répétition pour renforcement', 'Facilité d''accès'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-BASE-016',
   ARRAY['Anxiété & stress']
  ),
  (616,
   'Ancre respiratoire',
   'KIIKA — Ancrage',
   'Hypnose Ericksonienne',
   'Installation d''un schéma respiratoire spécifique (par exemple : inspiration 4 temps, rétention 2 temps, expiration 6 temps) comme déclencheur d''un état de calme accessible à tout moment.',
   '12 min',
   'Débutant',
   ARRAY['ancrage', 'respiration', 'souffle', 'régulation', 'anxiété', 'sport'],
   '#C8A030',
   1,
   ARRAY['Effet physiologique direct (système parasympathique)', 'Disponibilité universelle', 'Mémoire corporelle', 'Cumul avec les ancres gestuelles'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-BASE-017',
   ARRAY['Anxiété & stress']
  ),
  (617,
   'Mot-signal personnel',
   'KIIKA — Ancrage',
   'Hypnose Ericksonienne',
   'Choix et installation d''un mot-clef personnel (mot ressource ou mot inventé) qui devient déclencheur d''un état intérieur. Ancre verbale particulièrement adaptée aux patients qui pensent en mots.',
   '8 min',
   'Débutant',
   ARRAY['ancrage', 'mot signal', 'verbal', 'auto-suggestion', 'mantra'],
   '#C8A030',
   1,
   ARRAY['Association mot-état', 'Mémoire verbale', 'Auto-suggestion répétée', 'Accessibilité mentale'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-BASE-018',
   ARRAY['Anxiété & stress']
  ),
  (618,
   'Signal d''auto-induction',
   'KIIKA — Ancrage',
   'Hypnose Ericksonienne',
   'Installation du signal qui permettra au patient d''entrer rapidement en transe seul. Étape clef pour rendre le patient autonome et utilisable avec K-BASE-006 (induction rapide).',
   '15 min',
   'Intermédiaire',
   ARRAY['auto-hypnose', 'autonomie', 'signal', 'ancrage', 'induction rapide'],
   '#C8A030',
   1,
   ARRAY['Mémorisation de l''état de transe', 'Association signal-transe', 'Renforcement par pratique', 'Permission d''autonomie'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-BASE-019',
   ARRAY['Anxiété & stress']
  ),
  (619,
   'Observateur bienveillant',
   'KIIKA — Dissociation',
   'Hypnose Ericksonienne',
   'Installation d''une position d''observateur intérieur qui regarde l''expérience sans s''y identifier. Brique fondamentale pour tout travail dissociatif, particulièrement utile face à du contenu chargé.',
   '12 min',
   'Intermédiaire',
   ARRAY['dissociation', 'observateur', 'témoin', 'fondamental', 'trauma', 'régulation émotionnelle'],
   '#5B8FB9',
   1,
   ARRAY['Méta-position', 'Recul observant', 'Bienveillance envers soi', 'Différenciation observateur-vécu'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-BASE-020',
   ARRAY['Anxiété & stress']
  ),
  (620,
   'Écran de cinéma intérieur',
   'KIIKA — Dissociation',
   'Hypnose Ericksonienne',
   'Technique de dissociation par projection d''un contenu mental sur un écran de cinéma intérieur. Permet de regarder une scène pénible, un souvenir, un comportement à distance, avec contrôle des paramètres (taille, couleur, son, vitesse).',
   '25 min',
   'Avancé',
   ARRAY['dissociation', 'écran cinéma', 'projection', 'phobie', 'trauma léger', 'sous-modalités'],
   '#5B8FB9',
   1,
   ARRAY['Externalisation du contenu mental', 'Contrôle des sous-modalités (taille, couleur, son)', 'Position dissociée double (spectateur + projectionniste)', 'Manipulation expérimentale'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-BASE-021',
   ARRAY['Anxiété & stress']
  ),
  (621,
   'Voyage dans le temps intérieur',
   'KIIKA — Dissociation',
   'Hypnose Ericksonienne',
   'Installation d''une métaphore de déplacement temporel intérieur permettant régression et progression douces. Brique préalable aux protocoles de régression en âge ou de progression future.',
   '15 min',
   'Avancé',
   ARRAY['dissociation', 'régression', 'progression', 'temps', 'voyage', 'ligne de vie'],
   '#5B8FB9',
   1,
   ARRAY['Métaphore du voyage', 'Sécurité du véhicule', 'Réversibilité', 'Contrôle de la destination'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-BASE-022',
   ARRAY['Anxiété & stress']
  ),
  (622,
   'Voix sage intérieure',
   'KIIKA — Dissociation',
   'Hypnose Ericksonienne',
   'Installation d''une figure intérieure sage et bienveillante (conseiller, guide, vieil ami intérieur, ancêtre) à laquelle le patient peut s''adresser pour obtenir des éclairages venant de son inconscient.',
   '25 min',
   'Avancé',
   ARRAY['voix sage', 'guide intérieur', 'conseiller', 'Ka', 'introspection', 'spirituel'],
   '#5B8FB9',
   1,
   ARRAY['Personnification de la sagesse intérieure', 'Dialogue intrapsychique', 'Accès aux ressources inconscientes', 'Confiance en sa propre voix profonde'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-BASE-023',
   ARRAY['Anxiété & stress']
  ),
  (623,
   'Bulle protectrice',
   'KIIKA — Dissociation',
   'Hypnose Ericksonienne',
   'Installation d''une enveloppe protectrice imaginaire (bulle, cocon, halo) qui entoure le patient et filtre ce qui peut l''atteindre. Particulièrement utile pour patients hypersensibles et en travail psycho-spirituel.',
   '12 min',
   'Intermédiaire',
   ARRAY['bulle', 'protection', 'enveloppe', 'hypersensibilité', 'limites', 'KIIKA'],
   '#5B8FB9',
   1,
   ARRAY['Imagerie d''enveloppe', 'Filtrage sélectif', 'Sensation de souveraineté', 'Contrôle de la perméabilité'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-BASE-024',
   ARRAY['Anxiété & stress']
  ),
  (624,
   'Retour standard par escalier inverse',
   'KIIKA — Retour',
   'Hypnose Ericksonienne',
   'Retour à l''état de veille par remontée d''escalier inverse, comptage de 1 à 10 avec réintégration progressive du corps, des sens et de l''environnement. Brique de retour la plus utilisée.',
   '5 min',
   'Débutant',
   ARRAY['retour', 'réorientation', 'escalier inverse', 'fondamental'],
   '#E08550',
   1,
   ARRAY['Symétrie avec l''induction par escalier', 'Réintégration corporelle progressive', 'Réveil sensoriel ordonné', 'Suggestion de bien-être post-séance'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-BASE-025',
   ARRAY['Anxiété & stress']
  ),
  (625,
   'Retour rapide pour cabinet',
   'KIIKA — Retour',
   'Hypnose Ericksonienne',
   'Retour bref en quelques minutes pour situations cliniques pressées (séance courte, fin de consultation, patient pressé). À utiliser uniquement sur des transes légères à modérées.',
   '2 min',
   'Intermédiaire',
   ARRAY['retour', 'rapide', 'cabinet', 'court'],
   '#E08550',
   1,
   ARRAY['Suggestion directe de réveil', 'Mouvement physique d''activation', 'Confirmation de bien-être'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-BASE-026',
   ARRAY['Anxiété & stress']
  ),
  (626,
   'Retour avec consolidation des acquis',
   'KIIKA — Retour',
   'Hypnose Ericksonienne',
   'Retour qui inclut un temps de consolidation : revue rapide des bénéfices de la séance, ancrage des nouvelles ressources, suggestions de prolongement inconscient du travail entre les séances.',
   '8 min',
   'Intermédiaire',
   ARRAY['retour', 'consolidation', 'intégration', 'ancrage', 'post-hypnotique'],
   '#E08550',
   1,
   ARRAY['Revue des acquis', 'Ancrage des nouvelles ressources', 'Suggestion de prolongement inconscient', 'Suggestion d''intégration au quotidien'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-BASE-027',
   ARRAY['Anxiété & stress']
  ),
  (627,
   'Retour vers le sommeil enchaîné',
   'KIIKA — Retour',
   'Hypnose Ericksonienne',
   'Variante de retour qui guide la transe vers le sommeil naturel plutôt que vers la veille. Spécifique aux séances de soir ou aux protocoles d''aide à l''endormissement.',
   '5 min',
   'Débutant',
   ARRAY['retour', 'sommeil', 'endormissement', 'soir', 'insomnie'],
   '#E08550',
   1,
   ARRAY['Aucune suggestion de réveil', 'Approfondissement vers la somnolence', 'Permission explicite de s''endormir', 'Suggestion de qualité du sommeil'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-BASE-028',
   ARRAY['Anxiété & stress']
  ),
  (628,
   'Suggestions post-hypnotiques génériques',
   'KIIKA — Post-hypnotique',
   'Hypnose Ericksonienne',
   'Bibliothèque de suggestions post-hypnotiques génériques utilisables en fin de tout protocole : renforcement à chaque pratique, disponibilité des ressources, intégration au quotidien, confiance dans l''inconscient.',
   '5 min',
   'Débutant',
   ARRAY['post-hypnotique', 'suggestion', 'renforcement', 'intégration', 'fondamental'],
   '#C8A030',
   1,
   ARRAY['Renforcement à chaque pratique', 'Effet cumulatif', 'Confiance dans l''inconscient', 'Pont avec la vie quotidienne'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-BASE-029',
   ARRAY['Anxiété & stress']
  ),
  (629,
   'Clôture rituelle KIIKA',
   'KIIKA — Clôture',
   'Hypnose Ericksonienne',
   'Clôture spécifique à l''identité KIIKA : passage par les cinq dimensions (Ki, Introspection, Intuition, Ka, Alignement) pour intégrer la séance dans une cohérence d''ensemble. Réservée aux séances marquantes ou rituelles.',
   '12 min',
   'Avancé',
   ARRAY['clôture', 'rituel', 'KIIKA', 'cinq dimensions', 'spirituel', 'intégration'],
   '#E08550',
   1,
   ARRAY['Passage rituel par les 5 dimensions', 'Intégration symbolique', 'Cohérence d''ensemble', 'Marquage de la séance comme événement'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-BASE-030',
   ARRAY['Anxiété & stress']
  ),
  (630,
   'Anxiété généralisée — Régulation par souffle et lieu sûr',
   'KIIKA — Régulation de base',
   'Hypnose Ericksonienne',
   'Protocole de fond pour anxiété généralisée. Combine ancre respiratoire, lieu sûr et bulle protectrice. À installer en premières séances pour donner au patient des outils utilisables au quotidien.',
   '40 min',
   'Débutant',
   ARRAY['anxiété généralisée', 'régulation', 'souffle', 'lieu sûr', 'premier travail'],
   '#2E8A7B',
   1,
   ARRAY['Ancrage respiratoire physiologique', 'Lieu sûr disponible', 'Bulle protectrice', 'Suggestions de désinvestissement de la vigilance'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-ANX-001',
   ARRAY['Anxiété & stress']
  ),
  (631,
   'Crise d''angoisse aiguë — Protocole de désamorçage',
   'KIIKA — Crise aiguë',
   'Hypnose Ericksonienne',
   'Protocole bref pour gestion d''une crise d''angoisse en cours ou imminente. Inhalation forcée brève, exhalation lente, ancrage corporel par les cinq sens, recadrage de la sensation corporelle.',
   '15 min',
   'Intermédiaire',
   ARRAY['crise d''angoisse', 'panique', 'hyperventilation', 'urgence', '5 sens', 'ancrage'],
   '#B85450',
   1,
   ARRAY['Régulation respiratoire d''urgence', 'Ancrage par les cinq sens', 'Recadrage des sensations corporelles', 'Sortie de la spirale catastrophique'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-ANX-002',
   ARRAY['Anxiété & stress']
  ),
  (632,
   'Anxiété anticipatoire — Désamorçage du futur catastrophique',
   'KIIKA — Anticipation',
   'Hypnose Ericksonienne',
   'Pour patients qui s''épuisent à anticiper négativement les événements à venir. Travail de différenciation entre anticipation utile et anxiété anticipatoire. Installation d''un futur alternatif crédible.',
   '35 min',
   'Intermédiaire',
   ARRAY['anxiété anticipatoire', 'futur', 'catastrophisme', 'rumination', 'imagination', 'voyage temporel'],
   '#C8A030',
   1,
   ARRAY['Différenciation anticipation utile / anticipation toxique', 'Pluralité des futurs possibles', 'Imagination ressource', 'Voyage temporel intérieur'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-ANX-003',
   ARRAY['Anxiété & stress']
  ),
  (633,
   'Phobie sociale — Bulle, voix sage et regards alliés',
   'KIIKA — Phobie sociale',
   'Hypnose Ericksonienne',
   'Pour anxiété sociale et peur du jugement. Combine bulle protectrice, repérage des regards alliés (vs hostiles imaginaires), et installation d''une voix sage qui rappelle la valeur du patient.',
   '40 min',
   'Intermédiaire',
   ARRAY['phobie sociale', 'anxiété sociale', 'peur du jugement', 'bulle', 'voix sage', 'estime'],
   '#B85450',
   1,
   ARRAY['Bulle protectrice contre la perception envahissante', 'Différenciation regards réels / regards imaginés', 'Voix sage intérieure rappelant la valeur', 'Préparation imaginaire de situations sociales'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-ANX-004',
   ARRAY['Phobies & peurs', 'Anxiété & stress']
  ),
  (634,
   'Trac de performance — Préparation et activation juste',
   'KIIKA — Performance',
   'Hypnose Ericksonienne',
   'Trac avant prise de parole, examen, audition, compétition. Travail de transformation du trac en énergie disponible plutôt que tentative de le supprimer. Activation de l''attention juste, ni sur-engagée ni dispersée.',
   '35 min',
   'Intermédiaire',
   ARRAY['trac', 'performance', 'examen', 'prise de parole', 'compétition', 'activation', 'Storm'],
   '#C8A030',
   1,
   ARRAY['Recadrage trac comme énergie', 'Différenciation activation utile / activation parasite', 'Préparation imaginaire de la performance', 'Ancrage gestuel d''activation juste'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-ANX-005',
   ARRAY['Performance & examens', 'Anxiété & stress']
  ),
  (635,
   'Phobie spécifique — Désensibilisation graduée par hiérarchie',
   'KIIKA — Phobie spécifique',
   'Hypnose Ericksonienne',
   'Méthode de désensibilisation par construction d''une hiérarchie d''anxiété puis exposition imaginaire graduée en transe, avec extinction de l''anxiété à chaque palier avant progression.',
   '50 min',
   'Avancé',
   ARRAY['phobie spécifique', 'désensibilisation', 'hiérarchie', 'exposition imaginaire', 'Wolpe'],
   '#B85450',
   1,
   ARRAY['Hiérarchisation explicite', 'Exposition imaginaire graduée', 'Extinction par maintien jusqu''à apaisement', 'Inhibition réciproque relaxation/anxiété', 'Signal idéomoteur'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-ANX-006',
   ARRAY['Phobies & peurs', 'Anxiété & stress']
  ),
  (636,
   'Anxiété somatique — Du corps qui parle',
   'KIIKA — Somatisation',
   'Hypnose Ericksonienne',
   'Pour anxiété qui s''exprime principalement par des symptômes corporels (boule à l''estomac, oppression thoracique, tensions musculaires chroniques, troubles digestifs fonctionnels). Travail de dialogue avec la sensation.',
   '40 min',
   'Intermédiaire',
   ARRAY['anxiété somatique', 'somatisation', 'dialogue corporel', 'boule estomac', 'oppression'],
   '#5B8FB9',
   1,
   ARRAY['Personnification de la sensation', 'Reconnaissance de l''intention positive du symptôme', 'Dialogue intrapsychique', 'Recadrage du symptôme'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-ANX-007',
   ARRAY['Anxiété & stress']
  ),
  (637,
   'Rumination mentale — Sortir de la roue',
   'KIIKA — Rumination',
   'Hypnose Ericksonienne',
   'Pour pensées en boucle qui tournent sans déboucher sur l''action. Reconnaissance du mécanisme, distinction réflexion utile / rumination, technique de désengagement attentionnel par déplacement vers le corps et le présent.',
   '35 min',
   'Intermédiaire',
   ARRAY['rumination', 'boucle mentale', 'pensées intrusives', 'désengagement', 'présent'],
   '#7C5CBF',
   1,
   ARRAY['Reconnaissance du mécanisme de boucle', 'Distinction rumination / réflexion', 'Désidentification d''avec la pensée', 'Redirection vers le corps et le présent'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-ANX-008',
   ARRAY['Anxiété & stress']
  ),
  (638,
   'Hypervigilance — Permission de baisser la garde',
   'KIIKA — Hypervigilance',
   'Hypnose Ericksonienne',
   'Pour patients en état d''alerte permanent, souvent suite à un environnement éprouvant ou à un trauma léger. Travail de différenciation entre vigilance utile et vigilance parasite, permission progressive de relâcher.',
   '40 min',
   'Avancé',
   ARRAY['hypervigilance', 'alerte chronique', 'permission de relâcher', 'sursaut', 'post-environnement'],
   '#B85450',
   1,
   ARRAY['Reconnaissance du caractère adaptatif passé', 'Distinction vigilance utile / parasite', 'Permission progressive', 'Lieux de sécurité absolue'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-ANX-009',
   ARRAY['Anxiété & stress']
  ),
  (639,
   'Anxiété de séparation adulte — Lien intériorisé',
   'KIIKA — Attachement',
   'Hypnose Ericksonienne',
   'Pour anxiété massive lors de séparations (conjoint en déplacement, enfant qui part, deuil anticipé). Travail d''intériorisation du lien, distinction entre absence physique et perte du lien.',
   '40 min',
   'Avancé',
   ARRAY['anxiété de séparation', 'abandon', 'attachement', 'lien intériorisé', 'absence'],
   '#7C5CBF',
   1,
   ARRAY['Lien intériorisé toujours présent', 'Différenciation absence physique / perte de lien', 'Ressource du souvenir incarné', 'Auto-connexion'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-ANX-010',
   ARRAY['Anxiété & stress']
  ),
  (640,
   'Inquiétude pour un proche — Charge de soin et présence juste',
   'KIIKA — Sollicitude',
   'Hypnose Ericksonienne',
   'Pour patients qui se rongent pour un proche malade, en difficulté ou en danger. Travail de différenciation entre sollicitude utile et inquiétude paralysante. Recharge des aidants.',
   '40 min',
   'Intermédiaire',
   ARRAY['inquiétude', 'aidant', 'proche malade', 'charge mentale', 'lâcher-prise'],
   '#2E8A7B',
   1,
   ARRAY['Distinction sollicitude / inquiétude', 'Soin de soi comme condition du soin de l''autre', 'Lâcher-prise sur ce qui ne dépend pas de soi', 'Recharge énergétique'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-ANX-011',
   ARRAY['Anxiété & stress']
  ),
  (641,
   'Anxiété médicale — Examens, diagnostics, traitements',
   'KIIKA — Médical',
   'Hypnose Ericksonienne',
   'Pour anxiété face aux examens, attentes de résultats, traitements médicaux pesants. Travail sur la confiance corporelle, la gestion de l''attente, la différenciation entre vraie alerte et anxiété.',
   '35 min',
   'Intermédiaire',
   ARRAY['anxiété médicale', 'examen', 'résultats', 'diagnostic', 'soins', 'phobie médicale'],
   '#5B8FB9',
   1,
   ARRAY['Confiance corporelle', 'Distinction signal / bruit', 'Gestion de l''attente', 'Préparation imaginaire des soins'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-ANX-012',
   ARRAY['Anxiété & stress']
  ),
  (642,
   'Anxiété de transport — Avion, voiture, transports en commun',
   'KIIKA — Transport',
   'Hypnose Ericksonienne',
   'Pour anxiété spécifique aux transports : avion, voiture, métro, train. Combine désensibilisation par hiérarchie, contrôle perçu et installation d''un voyage intérieur parallèle au voyage réel.',
   '45 min',
   'Intermédiaire',
   ARRAY['transport', 'avion', 'voiture', 'métro', 'train', 'phobie', 'désensibilisation'],
   '#B85450',
   1,
   ARRAY['Désensibilisation graduée', 'Restauration du contrôle perçu', 'Voyage intérieur parallèle', 'Ancrages utilisables en transport'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-ANX-013',
   ARRAY['Anxiété & stress']
  ),
  (643,
   'Anxiété existentielle — Vertige du sens',
   'KIIKA — Existentiel',
   'Hypnose Ericksonienne',
   'Pour anxiété touchant les fondamentaux : finitude, sens de la vie, solitude existentielle, liberté. Travail spécifique à l''approche thérapie-spiritualité KIIKA, avec mobilisation forte du Ka.',
   '50 min',
   'Avancé',
   ARRAY['anxiété existentielle', 'sens', 'finitude', 'spiritualité', 'Ka', 'quête', 'vertige'],
   '#7C5CBF',
   1,
   ARRAY['Sanctuaire intérieur', 'Voix sage', 'Ka comme essence durable', 'Recadrage du vertige', 'Connexion à plus grand que soi'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-ANX-014',
   ARRAY['Anxiété & stress']
  ),
  (644,
   'Anxiété de l''incertitude — Apprivoiser le non-savoir',
   'KIIKA — Tolérance à l''incertitude',
   'Hypnose Ericksonienne',
   'Pour patients ayant un faible seuil de tolérance à l''incertitude : besoin compulsif de savoir, de contrôler, de prévoir. Travail sur la cohabitation possible avec le non-su.',
   '40 min',
   'Avancé',
   ARRAY['incertitude', 'non-savoir', 'contrôle', 'vérifications', 'tolérance', 'adaptabilité'],
   '#7C5CBF',
   1,
   ARRAY['Reconnaissance de l''incertitude comme constante de la vie', 'Différenciation gestion / élimination', 'Pratique de l''inconnu apprivoisé', 'Confiance dans l''adaptabilité'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-ANX-015',
   ARRAY['Anxiété & stress']
  ),
  (645,
   'Insomnie d''endormissement — Le glissement vers la nuit',
   'KIIKA — Endormissement',
   'Hypnose Ericksonienne',
   'Pour patients qui mettent plus de 30-45 minutes à s''endormir le soir. Travail sur le rapport au sommeil, déconditionnement de la lutte, installation d''une routine du glissement.',
   '30 min',
   'Intermédiaire',
   ARRAY['insomnie', 'endormissement', 'glissement', 'déconditionnement', 'premier travail sommeil'],
   '#7C5CBF',
   1,
   ARRAY['Recadrage : sommeil ne se commande pas', 'Désinvestissement de l''effort', 'Imagerie de glissement', 'Anti-attente du sommeil'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-SOM-001',
   ARRAY['Sommeil & insomnie']
  ),
  (646,
   'Réveils nocturnes — Le retour dans le sommeil',
   'KIIKA — Continuité',
   'Hypnose Ericksonienne',
   'Pour patients qui s''endorment correctement mais se réveillent une ou plusieurs fois dans la nuit et peinent à se rendormir. Installation d''un protocole de retour au sommeil sans dramatisation.',
   '30 min',
   'Intermédiaire',
   ARRAY['réveils nocturnes', 'rendormissement', 'continuité du sommeil', '3h du matin'],
   '#7C5CBF',
   1,
   ARRAY['Désinvestissement du temps qui passe', 'Routine de retour', 'Suggestion d''oubli de l''éveil', 'Pas de regard sur l''horloge'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-SOM-002',
   ARRAY['Sommeil & insomnie']
  ),
  (647,
   'Sommeil non réparateur — Approfondir la qualité',
   'KIIKA — Qualité',
   'Hypnose Ericksonienne',
   'Pour patients qui dorment leurs heures mais se réveillent fatigués. Travail sur la qualité du sommeil profond et le sentiment de récupération, par installation d''intentions de réparation pendant la nuit.',
   '30 min',
   'Intermédiaire',
   ARRAY['sommeil non réparateur', 'qualité', 'récupération', 'fatigue au réveil'],
   '#7C5CBF',
   1,
   ARRAY['Suggestions de réparation pendant le sommeil', 'Imagerie de récupération profonde', 'Confiance dans la nuit qui restaure', 'Préparation au coucher comme acte sacré'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-SOM-003',
   ARRAY['Sommeil & insomnie']
  ),
  (648,
   'Hypersomnie et somnolence diurne — Restaurer la vigilance juste',
   'KIIKA — Hypersomnie',
   'Hypnose Ericksonienne',
   'Pour patients qui dorment trop ou qui sont somnolents en journée. Travail de structuration des cycles veille-sommeil, restauration d''une vigilance diurne pleine.',
   '30 min',
   'Intermédiaire',
   ARRAY['hypersomnie', 'somnolence diurne', 'vigilance', 'cycles veille-sommeil'],
   '#7C5CBF',
   1,
   ARRAY['Activation matinale', 'Vigilance par micro-pauses', 'Ancrage de la vivacité', 'Recadrage du sommeil excessif'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-SOM-004',
   ARRAY['Sommeil & insomnie']
  ),
  (649,
   'Sommeil agité par les rêves — Pacifier la nuit',
   'KIIKA — Rêves',
   'Hypnose Ericksonienne',
   'Pour patients dont les rêves intenses ou anxieux perturbent le repos. Travail de pacification du contenu onirique sans le supprimer, installation d''une posture intérieure d''observateur des rêves.',
   '35 min',
   'Avancé',
   ARRAY['rêves agités', 'cauchemars', 'rêves anxieux', 'observateur des rêves'],
   '#7C5CBF',
   1,
   ARRAY['Posture d''observateur dans le rêve', 'Recadrage des rêves comme travail intérieur', 'Demande à l''inconscient', 'Continuité de la posture éveil-sommeil'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-SOM-005',
   ARRAY['Sommeil & insomnie']
  ),
  (650,
   'Décalage horaire et travail posté — Resynchronisation de l''horloge',
   'KIIKA — Rythmes',
   'Hypnose Ericksonienne',
   'Pour voyageurs traversant des fuseaux horaires ou travailleurs en horaires décalés. Aide à la resynchronisation de l''horloge interne et à la qualité du sommeil dans des conditions atypiques.',
   '30 min',
   'Intermédiaire',
   ARRAY['jet lag', 'travail posté', 'rythmes circadiens', 'voyageurs', 'garde'],
   '#7C5CBF',
   1,
   ARRAY['Programmation de l''horloge interne', 'Suggestions de sommeil profond malgré contexte difficile', 'Lumière comme synchroniseur', 'Acceptation de la situation'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-SOM-006',
   ARRAY['Sommeil & insomnie']
  ),
  (651,
   'Insomnie post-événementielle — Quand un événement perturbe la nuit',
   'KIIKA — Réactionnel',
   'Hypnose Ericksonienne',
   'Pour patients dont le sommeil est perturbé suite à un événement marquant : deuil, séparation, déménagement, changement professionnel. Aide à traverser sans que l''insomnie ne devienne chronique.',
   '35 min',
   'Intermédiaire',
   ARRAY['insomnie réactionnelle', 'événement', 'deuil', 'séparation', 'transition'],
   '#7C5CBF',
   1,
   ARRAY['Légitimation de l''agitation', 'Distinction nuit pour digérer / nuit pour reposer', 'Permission de la traversée', 'Reprise progressive'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-SOM-007',
   ARRAY['Sommeil & insomnie']
  ),
  (652,
   'Sommeil de l''enfant — Accompagner le coucher',
   'KIIKA — Pédiatrique',
   'Hypnose Ericksonienne',
   'Adaptation pour enfants de 4 à 12 ans souffrant de troubles d''endormissement, peurs nocturnes, cauchemars. Imagerie ludique, présence rassurante des parents.',
   '25 min',
   'Intermédiaire',
   ARRAY['sommeil enfant', 'pédiatrique', 'peur du noir', 'cauchemars enfants', 'rituel coucher'],
   '#7C5CBF',
   1,
   ARRAY['Imagerie ludique adaptée à l''âge', 'Implication des parents', 'Personnages protecteurs imaginaires', 'Rituel du coucher renforcé'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-SOM-008',
   ARRAY['Sommeil & insomnie']
  ),
  (653,
   'Sommeil et grossesse — Accompagner les nuits du dernier trimestre',
   'KIIKA — Grossesse',
   'Hypnose Ericksonienne',
   'Pour femmes enceintes en fin de grossesse confrontées à inconforts physiques, anxiétés, réveils fréquents. Adaptations spécifiques au contexte gravidique.',
   '35 min',
   'Intermédiaire',
   ARRAY['grossesse', 'obstétrique', 'fin de grossesse', 'préparation accouchement', 'sommeil maternel'],
   '#7C5CBF',
   1,
   ARRAY['Acceptation des inconforts comme passagers', 'Connexion au bébé pendant le repos', 'Dépose des anxiétés de l''accouchement', 'Repos même fragmenté'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-SOM-009',
   ARRAY['Sommeil & insomnie']
  ),
  (654,
   'Sommeil de la personne âgée — Adapter aux nouveaux rythmes',
   'KIIKA — Personne âgée',
   'Hypnose Ericksonienne',
   'Pour seniors confrontés aux modifications physiologiques du sommeil avec l''âge : nuits plus courtes, plus fragmentées, réveils précoces. Adaptation des attentes et optimisation du repos.',
   '30 min',
   'Intermédiaire',
   ARRAY['sommeil personne âgée', 'seniors', 'réveils précoces', 'fragmentation'],
   '#7C5CBF',
   1,
   ARRAY['Dédramatisation des changements physiologiques', 'Acceptation de nuits différentes', 'Optimisation du sommeil possible', 'Sieste comme complément'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-SOM-010',
   ARRAY['Sommeil & insomnie']
  ),
  (655,
   'Bruxisme nocturne — Relâcher la mâchoire qui serre',
   'KIIKA — Bruxisme',
   'Hypnose Ericksonienne',
   'Pour patients qui serrent ou grincent des dents la nuit. Travail sur la relaxation de la mâchoire au coucher, dépose des tensions accumulées, suggestion de relâchement nocturne.',
   '30 min',
   'Intermédiaire',
   ARRAY['bruxisme', 'mâchoire', 'tension mandibulaire', 'ATM', 'stress nocturne'],
   '#7C5CBF',
   1,
   ARRAY['Relaxation spécifique de la mâchoire', 'Identification des tensions diurnes refoulées', 'Suggestion de relâchement nocturne', 'Conscience corporelle de la mâchoire'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-SOM-011',
   ARRAY['Sommeil & insomnie']
  ),
  (656,
   'Cauchemars récurrents non traumatiques — Réécrire le scénario',
   'KIIKA — Cauchemars',
   'Hypnose Ericksonienne',
   'Technique de répétition imaginaire (rehearsal) pour cauchemars récurrents non liés à un trauma identifiable. Réécriture du scénario en éveil pour modifier le contenu nocturne.',
   '40 min',
   'Avancé',
   ARRAY['cauchemars récurrents', 'rehearsal', 'réécriture', 'scénario', 'imagerie thérapeutique'],
   '#7C5CBF',
   1,
   ARRAY['Reprise consciente du contenu', 'Modification créative du scénario', 'Répétition mentale en éveil', 'Reprogrammation onirique'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-SOM-012',
   ARRAY['Sommeil & insomnie']
  ),
  (657,
   'Sevrage des somnifères — Transition accompagnée',
   'KIIKA — Sevrage',
   'Hypnose Ericksonienne',
   'Accompagnement hypnotique du sevrage progressif de somnifères (benzodiazépines, Z-drugs) en coordination avec le médecin prescripteur. Transition vers ressources autonomes.',
   '40 min',
   'Avancé',
   ARRAY['sevrage somnifères', 'benzodiazépines', 'zolpidem', 'dépendance médicamenteuse'],
   '#7C5CBF',
   1,
   ARRAY['Installation préalable de ressources de sommeil', 'Confiance dans la capacité naturelle à dormir', 'Suggestion de potentialisation décroissante', 'Acceptation des nuits transitoires'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-SOM-013',
   ARRAY['Sommeil & insomnie']
  ),
  (658,
   'Sieste réparatrice — L''art du repos court',
   'KIIKA — Sieste',
   'Hypnose Ericksonienne',
   'Technique de sieste courte et efficace : 15-20 minutes de récupération profonde sans entrer en sommeil paradoxal. Pour patients qui peinent à faire la sieste ou qui veulent en optimiser la qualité.',
   '20 min',
   'Débutant',
   ARRAY['sieste', 'récupération diurne', 'power nap', 'repos court'],
   '#7C5CBF',
   1,
   ARRAY['Cadre temporel court délibéré', 'Profondeur sans paradoxal', 'Suggestion de réveil automatique', 'Récupération maximale en temps minimal'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-SOM-014',
   ARRAY['Sommeil & insomnie']
  ),
  (659,
   'Hygiène du sommeil et rituel du soir — Préparation profonde',
   'KIIKA — Rituel',
   'Hypnose Ericksonienne',
   'Construction d''un rituel de coucher complet, à la fois pratique (hygiène du sommeil) et symbolique (rituel KIIKA). Brique fondatrice du sommeil sur le long terme.',
   '30 min',
   'Débutant',
   ARRAY['hygiène sommeil', 'rituel coucher', 'préparation soir', 'fondamental sommeil'],
   '#7C5CBF',
   1,
   ARRAY['Hygiène du sommeil concrète', 'Marqueurs de transition', 'Rituel symbolique KIIKA', 'Renforcement par répétition'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-SOM-015',
   ARRAY['Sommeil & insomnie']
  ),
  (660,
   'Douleur chronique généralisée — Restaurer une relation soutenable',
   'KIIKA — Chronique',
   'Hypnose Ericksonienne',
   'Protocole de fond pour patients vivant avec une douleur chronique persistante. Travail sur le rapport à la douleur plutôt que sur sa suppression : différenciation douleur primaire / souffrance secondaire, restauration de zones non-douloureuses, dépose de la lutte épuisante.',
   '45 min',
   'Intermédiaire',
   ARRAY['douleur chronique', 'fond', 'premier travail', 'cohabitation', 'souffrance'],
   '#7C5CBF',
   1,
   ARRAY['Différenciation douleur / souffrance', 'Cartographie corporelle des zones non-douloureuses', 'Dépose de la lutte', 'Restauration de la qualité de vie'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-DOUL-001',
   ARRAY['Douleurs & psychosomatique']
  ),
  (661,
   'Lombalgie chronique — Décrisper le bas du dos',
   'KIIKA — Lombaire',
   'Hypnose Ericksonienne',
   'Pour douleur lombaire chronique non spécifique. Travail spécifique sur la décrispation de la zone lombaire, désinvestissement du cycle peur-tension-douleur, restauration progressive du mouvement.',
   '40 min',
   'Intermédiaire',
   ARRAY['lombalgie', 'lumbago', 'bas du dos', 'kinésiophobie', 'mouvement'],
   '#7C5CBF',
   1,
   ARRAY['Relaxation localisée des muscles paravertébraux', 'Désinvestissement du cycle peur-tension', 'Imagerie de souplesse retrouvée', 'Préparation du mouvement en confiance'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-DOUL-002',
   ARRAY['Douleurs & psychosomatique']
  ),
  (662,
   'Migraines et céphalées — Désamorçage et prévention',
   'KIIKA — Céphalées',
   'Hypnose Ericksonienne',
   'Pour migraines récurrentes et céphalées de tension. Travail en deux temps : désamorçage de la crise installée par modification des sous-modalités, et travail préventif entre les crises sur les facteurs déclenchants.',
   '40 min',
   'Intermédiaire',
   ARRAY['migraine', 'céphalée', 'tension', 'prodrome', 'désamorçage'],
   '#7C5CBF',
   1,
   ARRAY['Modification des sous-modalités douloureuses', 'Imagerie de fraîcheur localisée', 'Repérage et désamorçage des prodromes', 'Travail sur les déclencheurs'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-DOUL-003',
   ARRAY['Douleurs & psychosomatique']
  ),
  (663,
   'Fibromyalgie — Apaiser le système nerveux sensibilisé',
   'KIIKA — Fibromyalgie',
   'Hypnose Ericksonienne',
   'Pour patients atteints de fibromyalgie. Travail spécifique sur l''hypersensibilisation centrale, restauration des zones de moindre douleur, gestion de la fatigue associée, dépose progressive de l''épuisement.',
   '50 min',
   'Avancé',
   ARRAY['fibromyalgie', 'sensibilisation centrale', 'douleurs diffuses', 'fatigue chronique'],
   '#7C5CBF',
   1,
   ARRAY['Apaisement du système nerveux', 'Cartographie corporelle nuancée', 'Légitimation de la condition', 'Économie d''énergie', 'Gestion par paliers'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-DOUL-004',
   ARRAY['Douleurs & psychosomatique']
  ),
  (664,
   'Douleur post-opératoire — Récupération accélérée',
   'KIIKA — Post-opératoire',
   'Hypnose Ericksonienne',
   'Préparation pré-opératoire et accompagnement post-opératoire pour réduction de la douleur, accélération de la récupération, diminution des besoins en antalgiques. Idéalement pratiqué en plusieurs séances.',
   '40 min',
   'Intermédiaire',
   ARRAY['post-opératoire', 'chirurgie', 'préparation', 'récupération', 'antalgique'],
   '#7C5CBF',
   1,
   ARRAY['Suggestions de récupération rapide', 'Programmation du confort post-opératoire', 'Confiance dans l''équipe soignante', 'Imagerie de cicatrisation'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-DOUL-005',
   ARRAY['Douleurs & psychosomatique']
  ),
  (665,
   'Douleur neuropathique — Apprivoiser le signal défaillant',
   'KIIKA — Neuropathique',
   'Hypnose Ericksonienne',
   'Pour douleurs neuropathiques (neuropathie diabétique, post-zostérienne, post-chimio, neuropathie périphérique). Travail spécifique sur la nature particulière de cette douleur, modification des sensations brûlantes ou électriques.',
   '45 min',
   'Avancé',
   ARRAY['neuropathie', 'douleur neuropathique', 'brûlure', 'fourmillements', 'décharges'],
   '#7C5CBF',
   1,
   ARRAY['Modification des qualités sensorielles', 'Substitution sensorielle (chaleur agréable, fraîcheur)', 'Recadrage du signal défaillant', 'Auto-régulation des décharges'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-DOUL-006',
   ARRAY['Douleurs & psychosomatique']
  ),
  (666,
   'Douleur aiguë et soins répétés — Traverser sans s''épuiser',
   'KIIKA — Aiguë et soins',
   'Hypnose Ericksonienne',
   'Pour douleurs aiguës répétées liées à des soins (pansements, ponctions, kinésithérapie douloureuse, soins dentaires longs). Installation rapide de dispositifs anti-douleur utilisables en soin.',
   '35 min',
   'Intermédiaire',
   ARRAY['soins répétés', 'pansement', 'ponction', 'douleur procédurale', 'kinésithérapie'],
   '#7C5CBF',
   1,
   ARRAY['Dissociation par le lieu sûr', 'Anesthésie locale par imagerie', 'Modification des sensations en cours de soin', 'Ancrage rapide activable'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-DOUL-007',
   ARRAY['Douleurs & psychosomatique']
  ),
  (667,
   'Douleur cancéreuse — Confort dans la traversée',
   'KIIKA — Oncologie',
   'Hypnose Ericksonienne',
   'Accompagnement hypnotique de la douleur en contexte de cancer. Travail spécifique adapté à un parcours souvent long et complexe : douleurs liées à la maladie, aux traitements, à la fatigue, à l''angoisse. En strict complément du suivi oncologique.',
   '45 min',
   'Intermédiaire',
   ARRAY['cancer', 'oncologie', 'soins palliatifs', 'chimiothérapie', 'douleur cancéreuse'],
   '#7C5CBF',
   1,
   ARRAY['Confort multidimensionnel', 'Soutien à la résistance physique et psychique', 'Restauration de zones de bien-être', 'Allègement des effets secondaires', 'Présence à ce qui reste vivant'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-DOUL-008',
   ARRAY['Douleurs & psychosomatique']
  ),
  (668,
   'Douleur articulaire chronique — Arthrose et inflammations',
   'KIIKA — Articulaire',
   'Hypnose Ericksonienne',
   'Pour douleurs articulaires chroniques (arthrose, polyarthrite stabilisée, séquelles articulaires). Travail sur le confort des articulations, la lubrification imagée, la diminution de l''inflammation perçue.',
   '35 min',
   'Intermédiaire',
   ARRAY['arthrose', 'polyarthrite', 'articulation', 'inflammation', 'mobilité'],
   '#7C5CBF',
   1,
   ARRAY['Imagerie de lubrification', 'Diminution de l''inflammation perçue', 'Mobilité progressive', 'Apaisement local'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-DOUL-009',
   ARRAY['Douleurs & psychosomatique']
  ),
  (669,
   'Douleur post-traumatique chronique — Quand la blessure ancienne reste vive',
   'KIIKA — Post-traumatique',
   'Hypnose Ericksonienne',
   'Pour douleurs persistant longtemps après un traumatisme physique guéri (accident, fracture consolidée, blessure réparée). Travail sur le décalage entre tissu réparé et système nerveux qui continue à signaler.',
   '45 min',
   'Avancé',
   ARRAY['post-traumatique', 'douleur résiduelle', 'algodystrophie', 'consolidation', 'signal nerveux'],
   '#7C5CBF',
   1,
   ARRAY['Reconnaissance de la guérison anatomique', 'Mise à jour du système nerveux', 'Reconnexion de la zone au schéma corporel sain', 'Effacement progressif du signal résiduel'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-DOUL-010',
   ARRAY['Douleurs & psychosomatique']
  ),
  (670,
   'Douleurs viscérales chroniques — Apaiser le ventre qui parle',
   'KIIKA — Viscérale',
   'Hypnose Ericksonienne',
   'Pour douleurs viscérales chroniques fonctionnelles : côlon irritable, dyspepsie fonctionnelle, douleurs pelviennes chroniques. Travail sur l''axe cerveau-intestin et l''apaisement des viscères.',
   '40 min',
   'Intermédiaire',
   ARRAY['viscéral', 'côlon irritable', 'dyspepsie', 'douleur pelvienne', 'axe cerveau-intestin'],
   '#7C5CBF',
   1,
   ARRAY['Imagerie d''apaisement viscéral', 'Chaleur ou fraîcheur abdominale selon ressenti', 'Régulation de l''axe cerveau-intestin', 'Détente du système nerveux entérique'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-DOUL-011',
   ARRAY['Douleurs & psychosomatique']
  ),
  (671,
   'Douleurs menstruelles — Accompagner les cycles',
   'KIIKA — Gynécologique',
   'Hypnose Ericksonienne',
   'Pour dysménorrhée invalidante. Travail spécifique sur les douleurs des règles : préparation du cycle, gestion de la phase douloureuse, apaisement utérin par imagerie chaleur et lâcher-prise.',
   '35 min',
   'Intermédiaire',
   ARRAY['règles', 'dysménorrhée', 'menstruations', 'cycle', 'utérus'],
   '#7C5CBF',
   1,
   ARRAY['Préparation à l''arrivée des règles', 'Imagerie chaleur ventrale', 'Lâcher-prise utérin', 'Réconciliation avec le cycle'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-DOUL-012',
   ARRAY['Douleurs & psychosomatique']
  ),
  (672,
   'Douleur du membre fantôme — Apprivoiser ce qui n''est plus là',
   'KIIKA — Membre fantôme',
   'Hypnose Ericksonienne',
   'Pour patients amputés présentant des douleurs du membre fantôme. Travail spécifique sur cette douleur particulière : reconnaissance, modification par imagerie, miroir mental, intégration progressive de l''absence.',
   '45 min',
   'Avancé',
   ARRAY['membre fantôme', 'amputation', 'douleur fantôme', 'cartographie cérébrale', 'schéma corporel'],
   '#7C5CBF',
   1,
   ARRAY['Reconnaissance du phénomène', 'Imagerie de mouvement libre du membre fantôme', 'Effet miroir mental', 'Modification des sensations', 'Intégration progressive'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-DOUL-013',
   ARRAY['Douleurs & psychosomatique']
  ),
  (673,
   'Douleur dentaire et soins longs — Confort dans le fauteuil',
   'KIIKA — Dentaire',
   'Hypnose Ericksonienne',
   'Pour patients devant subir des soins dentaires longs ou douloureux : implants, extractions multiples, traitements de canaux, chirurgie maxillo-faciale. Préparation et accompagnement.',
   '35 min',
   'Intermédiaire',
   ARRAY['dentaire', 'soin dentaire', 'implant', 'extraction', 'phobie dentaire'],
   '#7C5CBF',
   1,
   ARRAY['Lieu sûr accessible en fauteuil', 'Anesthésie imaginée complémentaire', 'Modification du temps perçu', 'Confort dans la position'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-DOUL-014',
   ARRAY['Douleurs & psychosomatique']
  ),
  (674,
   'Auto-hypnose anti-douleur — Le dispositif quotidien',
   'KIIKA — Auto-hypnose',
   'Hypnose Ericksonienne',
   'Protocole-pivot d''apprentissage de l''auto-hypnose anti-douleur. Pour patients avancés dans le travail anti-douleur, ayant déjà installé les ressources de base. Permet la pratique autonome quotidienne.',
   '50 min',
   'Avancé',
   ARRAY['auto-hypnose', 'douleur', 'autonomie', 'pratique quotidienne', 'synthèse'],
   '#7C5CBF',
   1,
   ARRAY['Synthèse des techniques apprises', 'Installation d''un protocole personnel court', 'Pratique guidée puis autonome', 'Programmation de la régularité'],
   'KIIKA — Fiches détaillées (Varinka Robert) — K-DOUL-015',
   ARRAY['Douleurs & psychosomatique']
  )
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  practice = EXCLUDED.practice,
  description = EXCLUDED.description,
  duration = EXCLUDED.duration,
  level = EXCLUDED.level,
  tags = EXCLUDED.tags,
  color = EXCLUDED.color,
  sessions = EXCLUDED.sessions,
  objectives = EXCLUDED.objectives,
  source = EXCLUDED.source,
  motifs = EXCLUDED.motifs;