-- Protocoles d'Hypnose Spirituelle et Énergétique (GS Formation)
-- IDs 500-514 pour éviter collision avec NLP (100-475)

insert into public.protocols (id, name, category, practice, description, duration, level, tags, color, sessions, objectives, source, motifs)
values
(500, 'Récupérer des savoir-être et des ressources',
 'Vies antérieures & ressources', 'Hypnose Spirituelle',
 'Régression dans une vie antérieure choisie par l''esprit directeur pour récupérer une ressource manquante (courage, joie, confiance) et l''intégrer au présent.',
 '1 séance', 'Intermédiaire',
 array['Régression', 'Ressources', 'Esprit directeur', 'Ancrage'],
 '#7C5CBF', 1,
 array['Confiance', 'Courage', 'Joie', 'Estime de soi', 'Ressources oubliées'],
 'Hypnose Spirituelle GS Formation',
 array['Estime & confiance en soi', 'Procrastination & motivation']),

(501, 'Réparation karmique — Pardon',
 'Karma & contrats d''âmes', 'Hypnose Spirituelle',
 'Remontée à la vie d''origine d''un blocage récurrent. Médiation entre âmes concernées dans un lieu de lumière intemporel pour obtenir le pardon et dissoudre le karma.',
 '1-2 séances', 'Avancé',
 array['Karma', 'Pardon', 'Vies antérieures', 'Médiation'],
 '#5B8FB9', 1,
 array['Pardon', 'Libération karmique', 'Schémas répétitifs', 'Trauma transgénérationnel'],
 'Hypnose Spirituelle GS Formation',
 array['Trauma & deuil', 'Famille & enfance', 'Estime & confiance en soi']),

(502, 'Travail sur les contrats d''âmes',
 'Karma & contrats d''âmes', 'Hypnose Spirituelle',
 'Exploration et renégociation d''un contrat d''âme avec une personne de la vie présente. Dialogue avec l''âme concernée dans un espace de lumière intemporel.',
 '1 séance', 'Avancé',
 array['Contrats d''âmes', 'Relations', 'Négociation'],
 '#5B8FB9', 1,
 array['Relations toxiques', 'Liens passionnels', 'Détachement', 'Compréhension relationnelle'],
 'Hypnose Spirituelle GS Formation',
 array['Couple & sexualité', 'Famille & enfance', 'Conflits & communication']),

(503, 'Contrat de vie (pré-conception)',
 'Karma & contrats d''âmes', 'Hypnose Spirituelle',
 'Accès au conseil des sages pour comprendre les objectifs d''incarnation choisis et éventuellement renégocier certaines modalités lourdes du chemin de vie.',
 '1 séance', 'Avancé',
 array['Chemin de vie', 'Conseil', 'Mission d''âme'],
 '#C8A030', 1,
 array['Sens de la vie', 'Mission', 'Souffrance existentielle', 'Acceptation'],
 'Hypnose Spirituelle GS Formation',
 array['Quête de sens & spiritualité', 'Décision & orientation']),

(504, 'L''entre-vie (voyage complet)',
 'Entre-vie & guidance', 'Hypnose Spirituelle',
 'Visite complète de l''entre-vie : tunnel de lumière, accueil, réparation, jardin, bibliothèque, famille d''âmes, conseil, choix du corps, répétition. Protocole long (1h30-2h).',
 '1 séance longue', 'Avancé',
 array['Entre-vie', 'Famille d''âmes', 'Conseil', 'Bibliothèque akashique'],
 '#C8A030', 1,
 array['Connaissance de soi', 'Mission d''âme', 'Famille d''âmes', 'Sens spirituel'],
 'Hypnose Spirituelle GS Formation',
 array['Quête de sens & spiritualité']),

(505, 'Libération d''âmes (passeur)',
 'Libération d''âmes', 'Hypnose Spirituelle',
 'Communication avec les entités/âmes errantes accrochées au corps énergétique du client. Négociation et accompagnement vers la lumière. Réparation énergétique finale.',
 '1 séance', 'Avancé',
 array['Entités', 'Passeur d''âmes', 'Désenvoûtement', 'Astral'],
 '#B85450', 1,
 array['Parasitage énergétique', 'Fatigue chronique inexpliquée', 'Humeurs anormales', 'Présences perçues'],
 'Hypnose Spirituelle GS Formation',
 array['Anxiété & stress', 'Burn-out & fatigue', 'Dépression & humeur']),

(506, 'Désenvoûtement énergétique',
 'Énergétique & protections', 'Énergétique',
 'Identification et nettoyage des liens énergétiques toxiques, formes-pensées et envoûtements. Tranchage des cordons relationnels parasites. Aide des êtres de lumière.',
 '1 séance', 'Avancé',
 array['Envoûtement', 'Liens énergétiques', 'Formes-pensées', 'Nettoyage'],
 '#B85450', 1,
 array['Oppression énergétique', 'Liens toxiques', 'Jalousie subie', 'Fatigue relationnelle'],
 'Hypnose Spirituelle GS Formation',
 array['Anxiété & stress', 'Conflits & communication', 'Burn-out & fatigue']),

(507, 'Guidance — Dialogue avec les guides',
 'Entre-vie & guidance', 'Hypnose Spirituelle',
 'Convocation des guides de lumière dans un espace intemporel pour poser questions sur le chemin de vie, recevoir des enseignements et messages personnalisés.',
 '1 séance', 'Intermédiaire',
 array['Guides', 'Guidance', 'Sagesse', 'Intuition'],
 '#C8A030', 1,
 array['Choix de vie', 'Orientation spirituelle', 'Connaissance de soi', 'Guidance'],
 'Hypnose Spirituelle GS Formation',
 array['Décision & orientation', 'Quête de sens & spiritualité']),

(508, 'Nettoyage de printemps énergétique',
 'Énergétique & protections', 'Énergétique',
 'Visite d''un jardin intérieur où sont stockés schémas, croyances et énergies obsolètes. Transmutation par les flammes violettes dans un calice d''or. Réception d''une nouvelle ressource.',
 '1 séance', 'Débutant',
 array['Nettoyage', 'Transmutation', 'Flammes violettes', 'Renouveau'],
 '#7C5CBF', 1,
 array['Lourdeur mentale', 'Schémas obsolètes', 'Renouveau', 'Lâcher-prise'],
 'Hypnose Spirituelle GS Formation',
 array['Anxiété & stress', 'Burn-out & fatigue', 'Procrastination & motivation']),

(509, 'Réactivation des 14 couleurs',
 'Énergétique & protections', 'Énergétique',
 'Visualisation méthodique des 14 couleurs énergétiques (rouge, orange, jaune, vert, rose, bleu, indigo, blanc, violet, turquoise, cuivré, argenté, doré, nacré irisé) pour rééquilibrer le spectre vibratoire et la vitalité cellulaire.',
 'Quotidien — 15 min', 'Débutant',
 array['Couleurs', 'Vitalité', 'Cellules', 'Auto-soin'],
 '#2E8A7B', 21,
 array['Vitalité', 'Tonus', 'Régénération', 'Auto-soin quotidien'],
 'Hypnose Spirituelle GS Formation',
 array['Burn-out & fatigue', 'Douleurs & psychosomatique']),

(510, 'Mur de protection énergétique permanent',
 'Énergétique & protections', 'Énergétique',
 'Création d''un mur astral permanent entre soi et une personne nuisible, avec face miroir qui renvoie les énergies hostiles à leur expéditeur. Alimenté en continu depuis le haut astral.',
 '1 création', 'Intermédiaire',
 array['Protection', 'Astral', 'Miroir énergétique'],
 '#2E8A7B', 1,
 array['Harcèlement énergétique', 'Personne toxique', 'Jalousie', 'Protection durable'],
 'Hypnose Spirituelle GS Formation',
 array['Anxiété & stress', 'Conflits & communication']),

(511, 'Bulle de régénération durable',
 'Énergétique & protections', 'Énergétique',
 'Création d''une bulle astrale rechargée en énergies vertes (régénération), roses (recharge) et violettes (transmutation), réutilisable à volonté pour récupération rapide.',
 '1 création', 'Intermédiaire',
 array['Régénération', 'Recharge', 'Bulle astrale'],
 '#2E8A7B', 1,
 array['Récupération', 'Fatigue', 'Recharge énergétique', 'Auto-soin'],
 'Hypnose Spirituelle GS Formation',
 array['Burn-out & fatigue', 'Sommeil & insomnie']),

(512, 'Ancrage ciel-terre & ouverture du cœur',
 'Énergétique & protections', 'Énergétique',
 'Visualisation rapide (30 sec) en 3 étapes : racines rouges vers le centre de la terre, tube de lumière blanche depuis le ciel, ouverture du chakra du cœur en lumière verte. Rééquilibre cosmo-tellurique.',
 'Quotidien — 30 sec', 'Débutant',
 array['Ancrage', 'Chakras', 'Cœur', 'Cosmo-tellurique'],
 '#2E8A7B', 30,
 array['Centrage', 'Présence', 'Ancrage', 'Ouverture relationnelle'],
 'Hypnose Spirituelle GS Formation',
 array['Anxiété & stress', 'Décision & orientation']),

(513, 'Coque de lumière du thérapeute',
 'Énergétique & protections', 'Énergétique',
 'Création d''une coque de protection astrale permanente pour le praticien, isolant des énergies vibratoirement inférieures et du vampirisme énergétique. Indispensable avant chaque séance.',
 '1 création', 'Intermédiaire',
 array['Protection', 'Praticien', 'Astral', 'Vampirisme énergétique'],
 '#2E8A7B', 1,
 array['Protection praticien', 'Transports en commun', 'Lieux chargés', 'Personnes drainantes'],
 'Hypnose Spirituelle GS Formation',
 array['Anxiété & stress', 'Burn-out & fatigue']),

(514, 'Tamis de lumière — auto-nettoyage',
 'Énergétique & protections', 'Énergétique',
 'Tamis énergétique blanc multi-couches que l''on fait descendre lentement à travers le corps pour capturer et évacuer les énergies étrangères vers le centre de la terre. Pratique cumulative.',
 'Quotidien — 5 min', 'Débutant',
 array['Auto-nettoyage', 'Tamis', 'Praticien'],
 '#2E8A7B', 1,
 array['Nettoyage post-séance', 'Décharge énergétique', 'Auto-soin praticien'],
 'Hypnose Spirituelle GS Formation',
 array['Burn-out & fatigue', 'Anxiété & stress'])
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  practice = excluded.practice,
  description = excluded.description,
  duration = excluded.duration,
  level = excluded.level,
  tags = excluded.tags,
  color = excluded.color,
  sessions = excluded.sessions,
  objectives = excluded.objectives,
  source = excluded.source,
  motifs = excluded.motifs;
