-- Seed protocoles Reiki étendus — techniques spécifiques du 3ème degré
-- IDs : 824-839 (12 protocoles complémentaires aux 4 degrés 820-823)
-- Source : GS Formation — 3ème degré Reiki USUI (livret Danielle Paolini)

INSERT INTO public.protocols (id, name, category, practice, description, duration, level, tags, color, sessions, objectives, source, motifs)
VALUES
  (824,
   'Auto-traitement avec symboles — 21 jours d''intégration',
   'Reiki — Auto-traitement avancé',
   'Reiki',
   'Protocole d''intégration vibratoire des 4 symboles Reiki sur 21 jours. Travail d''un symbole par semaine puis combinaison. Centration au chakra du cœur, dessin des symboles, visualisation à chaque position des mains, mantra mental ×3.',
   '20-30 min/jour pendant 21 jours',
   'Avancé',
   ARRAY['reiki', 'auto-traitement', 'symboles', '21 jours', 'intégration', 'vibratoire'],
   '#7C5CBF',
   1,
   ARRAY['Intégrer la vibration de chacun des 4 symboles', 'Auto-traitement quotidien renforcé', 'Approfondir la pratique post-3ème degré', 'Entretenir le canal énergétique'],
   'GS Formation — 3ème degré Reiki USUI',
   ARRAY['Quête de sens & spiritualité', 'Anxiété & stress']
  ),
  (825,
   'Lieu de force avec Dai Ko Myo',
   'Reiki — Espace sacré',
   'Reiki',
   'Création d''un espace énergétique puissant : triangle dessiné au sol, symbole Dai Ko Myo à chaque pictogramme, mantra ×3. Permet méditation profonde, recentrage et accès à un lieu de force personnel. Particulièrement puissant en pleine nature.',
   '15-30 min (création) + utilisation libre',
   'Avancé',
   ARRAY['reiki', 'lieu de force', 'DKM', 'triangle', 'méditation', 'espace sacré'],
   '#C8A030',
   1,
   ARRAY['Créer un espace énergétique sacré', 'Méditer dans une zone amplifiée', 'Recentrage rapide en cas de stress', 'Préparer une séance de soin importante'],
   'GS Formation — 3ème degré Reiki USUI',
   ARRAY['Quête de sens & spiritualité', 'Anxiété & stress']
  ),
  (826,
   'Purification & programmation des cristaux',
   'Reiki — Cristaux',
   'Reiki',
   'Protocole d''utilisation des cristaux en Reiki : purification (Dai Ko Myo Tibétain + Sei He Ki), programmation à la guérison (Cho Ku Rei), demande d''auto-purification. Le cristal devient amplificateur d''énergie pour les soins ultérieurs.',
   '15-20 min par cristal',
   'Avancé',
   ARRAY['reiki', 'cristaux', 'purification', 'programmation', 'amplification'],
   '#5B8FB9',
   1,
   ARRAY['Purifier un cristal de toute énergie négative', 'Programmer un cristal à un objectif précis', 'Créer des outils d''amplification permanents', 'Compléter la pratique Reiki avec la lithothérapie'],
   'GS Formation — 3ème degré Reiki USUI',
   ARRAY['Quête de sens & spiritualité']
  ),
  (827,
   'Souffle Reiki — Respiration énergétique approfondie',
   'Reiki — Respiration',
   'Reiki',
   'Pratique respiratoire approfondie issue du Reiki Usui. Visualisation du souffle comme lumière blanche descendant dans les bras, sortant par les chakras des mains comme rayons de lumière. Évacue 90 % des toxines, intensifie le flux énergétique, calme le mental.',
   '5-15 min/jour',
   'Intermédiaire',
   ARRAY['reiki', 'souffle', 'respiration', 'lumière blanche', 'chakras des mains'],
   '#2E8A7B',
   1,
   ARRAY['Approfondir la respiration jusqu''à 90 % de capacité', 'Évacuer les toxines par la respiration consciente', 'Intensifier le flux Reiki dans les mains', 'Calmer le mental et centrer l''attention'],
   'GS Formation — 3ème degré Reiki USUI',
   ARRAY['Anxiété & stress', 'Burn-out & fatigue']
  ),
  (828,
   'Activation Kundalini Reiki — Canaux énergétiques',
   'Reiki — Kundalini',
   'Reiki',
   'Travail sur les canaux énergétiques principaux : Sushumna (canal central), Ida et Pingala (canaux latéraux). Activation et nettoyage par la respiration et la visualisation. Augmente la capacité du Maître Reiki à canaliser et transmettre l''énergie.',
   '20-30 min',
   'Avancé',
   ARRAY['reiki', 'kundalini', 'canaux', 'sushumna', 'ida', 'pingala', 'chakras'],
   '#7C5CBF',
   1,
   ARRAY['Activer la circulation énergétique dans les 3 canaux', 'Augmenter la capacité de canalisation Reiki', 'Préparer le corps subtil aux initiations supérieures', 'Travail de yoga énergétique complémentaire'],
   'GS Formation — 3ème degré Reiki USUI',
   ARRAY['Quête de sens & spiritualité', 'Burn-out & fatigue']
  ),
  (829,
   'Stimulation Dai Ko Myo Tibétain — Thymus & immunité',
   'Reiki — Stimulation immunitaire',
   'Reiki',
   'Protocole d''activation immunitaire : pression et massage du point sur l''omoplate (1 min en cercle horaire) avec visualisation du DKM Tibétain, répété 3× par épaule. Puis 25 frappes douces sur le centre de la poitrine (thymus) avec visualisation continue.',
   '10-15 min',
   'Intermédiaire',
   ARRAY['reiki', 'DKM tibétain', 'thymus', 'immunité', 'stimulation'],
   '#B85450',
   1,
   ARRAY['Activer les défenses immunitaires par stimulation du thymus', 'Renforcer l''énergie vitale par DKM Tibétain', 'Soutien physique en complément médical', 'Pratique quotidienne préventive'],
   'GS Formation — 3ème degré Reiki USUI',
   ARRAY['Burn-out & fatigue', 'Anxiété & stress']
  ),
  (834,
   'Symbole Antahkarana — Yang, Yin, Multiple',
   'Reiki — Symbole complémentaire',
   'Reiki',
   'Symbole tibétain ancien (« Pont »), complémentaire au Reiki, n''exigeant pas d''initiation. 4 variantes : Yang (masculin, énergie), Yin (féminin, méditation), Croix Cosmique, Multiple (déblocage). Amplifie tout soin, purifie cristaux, protège les lieux.',
   'Utilisation continue',
   'Intermédiaire',
   ARRAY['reiki', 'antahkarana', 'yang', 'yin', 'tibétain', 'amplification'],
   '#5B8FB9',
   1,
   ARRAY['Amplifier la puissance de tout soin Reiki', 'Méditer avec le symbole Yang ou Yin selon polarité', 'Protéger un lieu (sous le lit, sous la table de soin)', 'Purifier cristaux et objets'],
   'GS Formation — 3ème degré Reiki USUI',
   ARRAY['Quête de sens & spiritualité', 'Sommeil & insomnie']
  ),
  (835,
   'Croix Cosmique — Chakra du cœur',
   'Reiki — Symbole complémentaire',
   'Reiki',
   'Symbole Antahkarana spécialisé pour le travail sur le chakra du cœur. 7 croix verticales et horizontales. Sert à ouvrir, équilibrer et activer le chakra du cœur. Lance l''Orbite Microcosmique en méditation. Peut être porté à même le corps face contre le chakra.',
   '15-30 min (méditation)',
   'Intermédiaire',
   ARRAY['reiki', 'croix cosmique', 'chakra du cœur', 'antahkarana', 'orbite microcosmique'],
   '#B85450',
   1,
   ARRAY['Ouvrir et équilibrer le chakra du cœur', 'Lancer l''Orbite Microcosmique', 'Travailler la connexion cerveau-cœur-couronne', 'Développer l''amour inconditionnel'],
   'GS Formation — 3ème degré Reiki USUI',
   ARRAY['Quête de sens & spiritualité', 'Trauma & deuil']
  ),
  (836,
   'Bonhommes allumettes — Couper les liens disharmonieux',
   'Reiki — Libération',
   'Reiki',
   'Technique de libération énergétique pour couper les liens disharmonieux avec une personne ou une situation. Dessin de deux bonhommes allumettes (soi et l''autre/situation), processus rituel de coupure. Règle éthique : ne JAMAIS faire à la place d''un tiers.',
   '15-20 min',
   'Intermédiaire',
   ARRAY['reiki', 'bonhommes allumettes', 'couper les liens', 'libération', 'éthique'],
   '#E08550',
   1,
   ARRAY['Libérer un lien énergétique disharmonieux', 'Couper symboliquement avec une situation toxique', 'Protéger son champ énergétique', 'Pratique éthique respectueuse du libre arbitre'],
   'GS Formation — 3ème degré Reiki USUI',
   ARRAY['Conflits & communication', 'Trauma & deuil']
  ),
  (837,
   'Méditation avec le Maître Mikao Usui',
   'Reiki — Méditation',
   'Reiki',
   'Méditation guidée de connexion au lignage Reiki face à la photo du Maître Mikao Usui. Visualisation des 3 symboles avancés (DKM Tibétain front, DKM Maître gorge, Hon Sha Ze Sho Nen cœur) reliés par 3 rayons colorés. Union vibratoire avec l''énergie du Maître.',
   '20-30 min',
   'Avancé',
   ARRAY['reiki', 'méditation', 'Mikao Usui', 'lignage', 'symboles', 'union'],
   '#7C5CBF',
   1,
   ARRAY['Se connecter au lignage Usui', 'Activer simultanément les 3 symboles avancés', 'Recevoir la transmission vibratoire du Maître', 'Approfondir la pratique du 3ème degré'],
   'GS Formation — 3ème degré Reiki USUI',
   ARRAY['Quête de sens & spiritualité']
  ),
  (838,
   'Œuf d''Or & Ceinture de lumière — Protection énergétique',
   'Reiki — Protection',
   'Reiki',
   'Deux techniques de protection énergétique : (1) L''Œuf d''Or — enveloppe de lumière blanche entourée d''une coquille d''or réfléchissant les énergies négatives. (2) Ceinture de lumière blanche au plexus solaire. À utiliser en environnement énergétiquement difficile.',
   '5-10 min (installation)',
   'Intermédiaire',
   ARRAY['reiki', 'œuf d''or', 'protection', 'ceinture de lumière', 'bouclier'],
   '#C8A030',
   1,
   ARRAY['Se protéger des énergies négatives ambiantes', 'Préserver son champ énergétique en milieu hostile', 'Outil quotidien d''auto-protection', 'Compléter le travail Reiki en hypersensibilité'],
   'GS Formation — 3ème degré Reiki USUI',
   ARRAY['Anxiété & stress', 'Burn-out & fatigue']
  ),
  (839,
   'Grille de cristaux William Rand — Paix Mondiale & soins amplifiés',
   'Reiki — Grille de cristaux',
   'Reiki',
   'Technique du Reiki Karuna® de William Rand : utilisation des photos des grilles de cristaux placées aux pôles Nord et Sud (1997-1999) pour amplifier les soins. Sandwich de soin : photo du receveur entre les 2 pôles + Reiki sur l''ensemble. Puissance amplifiée par résonance planétaire.',
   '30-60 min (sandwich + Reiki)',
   'Avancé',
   ARRAY['reiki', 'grille de cristaux', 'William Rand', 'pôles', 'sandwich', 'paix mondiale'],
   '#5B8FB9',
   1,
   ARRAY['Amplifier un soin Reiki par résonance planétaire', 'Soigner à distance avec puissance maximale', 'Contribuer à la grille de Paix Mondiale', 'Pratique Reiki Karuna® de William Rand'],
   'GS Formation — 3ème degré Reiki USUI / Reiki Karuna',
   ARRAY['Quête de sens & spiritualité', 'Trauma & deuil']
  )
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  practice = EXCLUDED.practice,
  description = EXCLUDED.description,
  duration = EXCLUDED.duration,
  level = EXCLUDED.level,
  tags = EXCLUDED.tags,
  color = EXCLUDED.color,
  sessions = EXCLUDED.sessions,
  objectives = EXCLUDED.objectives,
  source = EXCLUDED.source,
  motifs = EXCLUDED.motifs;
