-- INTIO — Seed protocols (Big Book of NLP, ~190 protocoles)
-- Run after 0002_protocols.sql in Supabase SQL editor.

delete from public.protocols where source = 'The Big Book of NLP';

insert into public.protocols (id, name, category, description, color, objectives, tags) values
-- 1. Objectifs & motivation (gold)
(100, 'Well-Defined Outcomes', 'Objectifs & motivation', 'Formuler un objectif clair et écologique, aligné avec l''ensemble du système.', '#C8A030', '{"Motivation","Goal-setting","Écologie"}', '{"Objectif","SMART","Cadrage"}'),
(101, 'E & E.P. Formation Pattern', 'Objectifs & motivation', 'Structurer un but sous forme d''« état désiré » émotionnel et physique.', '#C8A030', '{"Motivation","Goal-setting"}', '{"État désiré","Visualisation"}'),
(102, 'Advantageous NLP Beliefs', 'Objectifs & motivation', 'Installer des croyances facilitantes au service d''un objectif.', '#C8A030', '{"Motivation","Croyances"}', '{"Croyances","Installation"}'),
(103, 'Creating Positive Expectations', 'Objectifs & motivation', 'Pré-programmer le succès en orientant les attentes vers le résultat désiré.', '#C8A030', '{"Motivation","Anticipation"}', '{"Attentes","Pré-programmation"}'),
(104, 'Basic Motivation Pattern', 'Objectifs & motivation', 'Déclencher l''élan et l''envie d''agir vers un but.', '#C8A030', '{"Motivation","Action"}', '{"Élan","Action"}'),
(105, 'Honored Values Elicitation', 'Objectifs & motivation', 'Identifier les valeurs profondes qui servent d''ancres motivationnelles.', '#C8A030', '{"Valeurs","Sens"}', '{"Valeurs","Élicitation"}'),
(106, 'Values Hierarchy Identification', 'Objectifs & motivation', 'Hiérarchiser les valeurs pour arbitrer les priorités de vie.', '#C8A030', '{"Valeurs","Décision"}', '{"Hiérarchie","Priorités"}'),
(107, 'Commitment', 'Objectifs & motivation', 'Verrouiller l''engagement envers un objectif.', '#C8A030', '{"Engagement","Motivation"}', '{"Engagement","Contrat"}'),
(108, 'Curiosity Enhancement', 'Objectifs & motivation', 'Alimenter la curiosité comme moteur de progression continue.', '#C8A030', '{"Apprentissage","Motivation"}', '{"Curiosité"}'),
(109, 'Positive Contribution', 'Objectifs & motivation', 'Donner du sens à l''action via le « pour quoi » et la contribution.', '#C8A030', '{"Sens","Motivation"}', '{"Contribution","Sens"}'),
(110, 'Positive Personal Significance', 'Objectifs & motivation', 'Construire la légitimité intérieure et le sentiment de mérite.', '#C8A030', '{"Estime de soi","Identité"}', '{"Légitimité"}'),

-- 2. États & ancrage (purple)
(120, 'Anchoring', 'États & ancrage', 'Créer un déclencheur conditionné d''un état ressource.', '#7C5CBF', '{"Ancrage","Performance"}', '{"Ancre","État"}'),
(121, 'Self Anchoring', 'États & ancrage', 'Permettre au client d''activer seul un ancrage pré-installé.', '#7C5CBF', '{"Ancrage","Autonomie"}', '{"Auto-ancrage"}'),
(122, 'Collapsing Anchors', 'États & ancrage', 'Neutraliser une ancre négative par superposition d''une ancre positive.', '#7C5CBF', '{"Ancrage","Émotions"}', '{"Effacement","Ancres"}'),
(123, 'Chaining States', 'États & ancrage', 'Construire une séquence d''états progressive vers l''état cible.', '#7C5CBF', '{"États","Transition"}', '{"Chaîne","Progression"}'),
(124, 'State Induction', 'États & ancrage', 'Amener rapidement le client dans un état précis.', '#7C5CBF', '{"États","Performance"}', '{"Induction"}'),
(125, 'Accessing Resourceful States', 'États & ancrage', 'Aller chercher dans le passé une ressource interne pour la mobiliser.', '#7C5CBF', '{"Ressources","Mémoire"}', '{"Ressources","Réactivation"}'),
(126, 'Physiomental State Interruption', 'États & ancrage', 'Casser brutalement un état négatif par rupture de pattern.', '#7C5CBF', '{"États","Régulation"}', '{"Pattern interrupt"}'),
(127, 'Kinesthetic Swish Pattern', 'États & ancrage', 'Variation kinesthésique du Swish pour basculer un état corporel.', '#7C5CBF', '{"Swish","Corps"}', '{"Swish","Kinesthésique"}'),
(128, 'Circle of Excellence', 'États & ancrage', 'Cercle au sol qui ancre un état d''excellence accessible à la demande.', '#7C5CBF', '{"Performance","Ancrage"}', '{"Cercle","Excellence"}'),
(129, 'Collecting Resources', 'États & ancrage', 'Constituer une banque interne de ressources mobilisables.', '#7C5CBF', '{"Ressources","Bilan"}', '{"Inventaire"}'),
(130, 'Downtime', 'États & ancrage', 'Accès à l''introspection et au temps intérieur de récupération.', '#7C5CBF', '{"Repos","Introspection"}', '{"Repos"}'),
(131, 'Eliciting Subconscious Responses', 'États & ancrage', 'Lire les réponses non-conscientes (idéomoteur, micro-mouvements).', '#7C5CBF', '{"Inconscient","Calibration"}', '{"Idéomoteur"}'),
(132, 'Submodality Overlapping', 'États & ancrage', 'Transférer les qualités d''une expérience à une autre via les sous-modalités.', '#7C5CBF', '{"Sous-modalités"}', '{"Transfert","Sous-modalités"}'),
(133, 'External Stimulus Threshold', 'États & ancrage', 'Calibrer les seuils de déclenchement aux stimuli externes.', '#7C5CBF', '{"Calibration","Régulation"}', '{"Seuils"}'),
(134, 'State Of Consciousness Awareness', 'États & ancrage', 'Développer la conscience en temps réel de son propre état.', '#7C5CBF', '{"Conscience","Méta"}', '{"Méta-conscience"}'),
(135, 'Pragmagraphic Swish Design', 'États & ancrage', 'Concevoir un Swish sur mesure pour un comportement spécifique.', '#7C5CBF', '{"Swish","Comportement"}', '{"Swish","Sur-mesure"}'),
(136, 'Pleasure Installation', 'États & ancrage', 'Associer du plaisir à une tâche utile mais ingrate.', '#7C5CBF', '{"Plaisir","Habitudes"}', '{"Conditionnement"}'),
(137, 'Pleasure Reduction', 'États & ancrage', 'Déconditionner un plaisir toxique (junk food, écrans, etc.).', '#7C5CBF', '{"Addictions","Plaisir"}', '{"Déconditionnement"}'),
(138, 'Godiva Chocolate Pattern', 'États & ancrage', 'Relier un plaisir intense à une discipline pour la rendre désirable.', '#7C5CBF', '{"Habitudes","Plaisir"}', '{"Pairing"}'),
(139, 'Smart Eating Pattern', 'États & ancrage', 'Reprogrammer le rapport à l''alimentation.', '#7C5CBF', '{"Alimentation","Habitudes"}', '{"Alimentation"}'),

-- 3. Communication & rapport (teal)
(150, 'Pacing and Matching', 'Communication & rapport', 'Se synchroniser au rythme et au registre de l''autre pour créer le rapport.', '#2E8A7B', '{"Rapport","Communication"}', '{"Pacing","Synchronisation"}'),
(151, 'Mirroring', 'Communication & rapport', 'Refléter posture, énergie et tonalité de l''autre.', '#2E8A7B', '{"Rapport","Communication"}', '{"Miroir"}'),
(152, 'Behavioral Mirroring', 'Communication & rapport', 'Imiter discrètement les comportements observables.', '#2E8A7B', '{"Rapport"}', '{"Miroir","Comportement"}'),
(153, 'Symbolic Mirroring', 'Communication & rapport', 'Refléter par métaphore ce que l''autre vit ou exprime.', '#2E8A7B', '{"Rapport","Métaphore"}', '{"Métaphore"}'),
(154, 'Exchanged Matches', 'Communication & rapport', 'Synchroniser sur un canal différent (geste → ton, etc.).', '#2E8A7B', '{"Rapport"}', '{"Cross-matching"}'),
(155, 'When NOT to Mirror or Match', 'Communication & rapport', 'Reconnaître les situations où le mirroring nuit (colère, manipulation).', '#2E8A7B', '{"Rapport","Discernement"}', '{"Limites"}'),
(156, 'Category Rapport-Building', 'Communication & rapport', 'Établir le rapport via les catégories de Satir.', '#2E8A7B', '{"Rapport","Profilage"}', '{"Satir"}'),
(157, 'Calibration', 'Communication & rapport', 'Lecture fine des signaux internes via les changements physiologiques.', '#2E8A7B', '{"Calibration","Observation"}', '{"Calibration"}'),
(158, 'Developing Sensory Acuity', 'Communication & rapport', 'Aiguiser les 5 sens pour percevoir plus finement l''autre et le monde.', '#2E8A7B', '{"Observation","Conscience"}', '{"Acuité sensorielle"}'),
(159, 'Non-Verbal Cues Recognition', 'Communication & rapport', 'Décoder les signaux non-verbaux (micro-expressions, posture, regard).', '#2E8A7B', '{"Observation","Communication"}', '{"Non-verbal"}'),
(160, 'Holding Attention', 'Communication & rapport', 'Maintenir le focus d''un groupe ou d''une personne dans la durée.', '#2E8A7B', '{"Communication","Influence"}', '{"Attention"}'),
(161, 'Nuanced Gesturing', 'Communication & rapport', 'Utiliser une gestuelle intentionnelle pour appuyer le discours.', '#2E8A7B', '{"Communication","Présence"}', '{"Gestuelle"}'),
(162, 'Satir Categories', 'Communication & rapport', 'Typologie de Virginia Satir : Blamer, Placater, Computer, Distracter, Leveler.', '#2E8A7B', '{"Profilage","Communication"}', '{"Satir","Typologie"}'),
(163, 'Utilizing Flexibility', 'Communication & rapport', 'Changer de canal ou de registre à la volée selon la réponse de l''autre.', '#2E8A7B', '{"Adaptabilité"}', '{"Flexibilité"}'),

-- 4. Peurs, phobies, douleurs, compulsions (red)
(180, 'Phobia Cure Pattern', 'Peurs & phobies', 'Dissociation rapide pour neutraliser une phobie en quelques minutes.', '#B85450', '{"Phobies","Trauma"}', '{"Fast phobia","Dissociation"}'),
(181, 'Allergy Pattern', 'Peurs & phobies', 'Reprogrammer une réaction allergique exagérée par recodage interne.', '#B85450', '{"Allergies","Somatique"}', '{"Allergie","Recodage"}'),
(182, 'Emotional Pain Management', 'Peurs & phobies', 'Gérer et atténuer la douleur émotionnelle aiguë.', '#B85450', '{"Douleur émotionnelle"}', '{"Douleur","Émotions"}'),
(183, 'Compulsion Blow-Out', 'Peurs & phobies', 'Neutraliser une compulsion par sur-exposition contrôlée à la sous-modalité critique.', '#B85450', '{"Compulsions","TOC"}', '{"Blow-out"}'),
(184, 'Decision Destroyer', 'Peurs & phobies', 'Effacer une décision limitante prise dans le passé.', '#B85450', '{"Croyances","Décisions"}', '{"Décision","Effacement"}'),
(185, 'Excuse Blow-Out Pattern', 'Peurs & phobies', 'Casser le cycle des excuses auto-justificatrices.', '#B85450', '{"Auto-sabotage"}', '{"Excuses"}'),
(186, 'Breaking Limiting Associations', 'Peurs & phobies', 'Découpler des associations toxiques (lieu = échec, etc.).', '#B85450', '{"Associations","Conditionnement"}', '{"Découplage"}'),
(187, 'Inducing Amnesia', 'Peurs & phobies', 'Aider un souvenir spécifique à s''estomper consciemment.', '#B85450', '{"Mémoire","Trauma"}', '{"Amnésie"}'),
(188, 'Remember To Forget', 'Peurs & phobies', 'Stocker un événement puis l''ignorer activement.', '#B85450', '{"Mémoire"}', '{"Lâcher-prise"}'),
(189, 'Binary Code of Forgetfulness', 'Peurs & phobies', 'Encodage en double étape pour favoriser l''oubli d''un événement.', '#B85450', '{"Mémoire"}', '{"Encodage"}'),
(190, 'Memory De-Energizing', 'Peurs & phobies', 'Retirer la charge émotionnelle d''un souvenir.', '#B85450', '{"Mémoire","Émotions"}', '{"Désénergisation"}'),
(191, 'Negative Associated Emotions Dissolving', 'Peurs & phobies', 'Dissoudre les émotions négatives liées à un événement ou à une personne.', '#B85450', '{"Émotions","Pardon"}', '{"Dissolution"}'),
(192, 'Cyber-Porn Addiction Removal', 'Peurs & phobies', 'Protocole spécifique aux addictions liées aux contenus en ligne.', '#B85450', '{"Addictions"}', '{"Addiction","Écrans"}'),
(193, 'Identifying Self Sabotage Elements', 'Peurs & phobies', 'Détecter les patterns d''auto-sabotage récurrents.', '#B85450', '{"Auto-sabotage"}', '{"Détection"}'),
(194, 'Winning Over The Internal War Zone', 'Peurs & phobies', 'Pacifier les conflits internes destructeurs.', '#B85450', '{"Conflits internes"}', '{"Pacification"}'),

-- 5. Croyances (blue)
(210, 'The Swish', 'Croyances', 'Remplacer une image limitante par une image désirée à grande vitesse.', '#5B8FB9', '{"Croyances limitantes","Habitudes"}', '{"Swish"}'),
(211, 'Belief Out-Framing', 'Croyances', 'Sortir du cadre d''une croyance pour la mettre en question.', '#5B8FB9', '{"Croyances","Recadrage"}', '{"Out-framing"}'),
(212, 'Conflicting Beliefs Integration', 'Croyances', 'Intégrer deux croyances apparemment opposées.', '#5B8FB9', '{"Croyances","Intégration"}', '{"Intégration"}'),
(213, 'Colliding & Colluding Beliefs', 'Croyances', 'Démêler des croyances qui s''entretiennent ou se renforcent mutuellement.', '#5B8FB9', '{"Croyances"}', '{"Démêlage"}'),
(214, 'Thought Virus Inoculation', 'Croyances', 'Immuniser contre les idées parasites (presse, réseaux, entourage).', '#5B8FB9', '{"Croyances","Protection"}', '{"Inoculation"}'),
(215, 'Changing Beliefs: Logic Approach', 'Croyances', 'Remplacement rationnel d''une croyance par une autre, plus aidante.', '#5B8FB9', '{"Croyances","Logique"}', '{"Logique"}'),
(216, 'Belief Systems Dis-Integration', 'Croyances', 'Désintégrer un système de croyances entier devenu obsolète.', '#5B8FB9', '{"Croyances"}', '{"Désintégration"}'),
(217, 'Basic Belief Chaining', 'Croyances', 'Enchaîner des croyances passerelles vers une croyance cible.', '#5B8FB9', '{"Croyances"}', '{"Chaînage"}'),
(218, 'Advanced Belief Chaining', 'Croyances', 'Version avancée du chaînage de croyances pour reconstruction profonde.', '#5B8FB9', '{"Croyances"}', '{"Chaînage avancé"}'),
(219, 'Criteria Installation', 'Croyances', 'Installer de nouveaux critères d''évaluation pour soi ou un domaine.', '#5B8FB9', '{"Critères","Valeurs"}', '{"Critères"}'),
(220, 'Kinesthetic Criteria', 'Croyances', 'Définir des critères à partir du ressenti corporel.', '#5B8FB9', '{"Critères","Corps"}', '{"Critères corporels"}'),
(221, 'Hierarchy Of Criteria', 'Croyances', 'Hiérarchiser les critères pour décider sans ambiguïté.', '#5B8FB9', '{"Critères","Décision"}', '{"Hiérarchie"}'),
(222, 'Re-Imprinting', 'Croyances', 'Réécrire un événement fondateur qui a imprimé une croyance limitante.', '#5B8FB9', '{"Trauma","Croyances"}', '{"Re-imprinting"}'),
(223, 'The Spinning Icons Pattern', 'Croyances', 'Rotation visuelle de symboles internes pour basculer rapidement de croyance.', '#5B8FB9', '{"Croyances","Sous-modalités"}', '{"Spinning"}'),

-- 6. Recadrage, perspective, intégration (orange)
(240, 'Six Step Reframe', 'Recadrage', 'Recadrage en six étapes d''un comportement non désiré.', '#D4622A', '{"Recadrage","Comportement"}', '{"Six steps"}'),
(241, 'Content Reframing', 'Recadrage', 'Recadrer le contenu d''une expérience.', '#D4622A', '{"Recadrage"}', '{"Contenu"}'),
(242, 'Context Reframing', 'Recadrage', 'Recadrer le contexte dans lequel un comportement prend sens.', '#D4622A', '{"Recadrage"}', '{"Contexte"}'),
(243, 'Reframing Beliefs & Opinions', 'Recadrage', 'Pratique guidée du recadrage de croyances et d''opinions.', '#D4622A', '{"Recadrage","Croyances"}', '{"Pratique"}'),
(244, 'Perceptual Positions', 'Recadrage', 'Soi / Autre / Observateur — explorer un sujet depuis 3 angles.', '#D4622A', '{"Recadrage","Empathie"}', '{"Positions"}'),
(245, 'Aligning Perceptual Positions', 'Recadrage', 'Aligner les trois positions perceptuelles pour une vision cohérente.', '#D4622A', '{"Recadrage","Cohérence"}', '{"Alignement"}'),
(246, 'Failure Into Feedback', 'Recadrage', 'Transformer un échec en donnée d''apprentissage.', '#D4622A', '{"Résilience","Apprentissage"}', '{"Feedback"}'),
(247, 'Mistakes Into Experience', 'Recadrage', 'Capitaliser les erreurs comme expérience structurante.', '#D4622A', '{"Apprentissage"}', '{"Erreurs"}'),
(248, 'Ecology Check', 'Recadrage', 'Vérifier les effets secondaires d''un changement sur le système global.', '#D4622A', '{"Écologie","Sécurité"}', '{"Écologie"}'),
(249, 'Whole System Ecology', 'Recadrage', 'Vue systémique totale incluant entourage et contextes liés.', '#D4622A', '{"Écologie"}', '{"Systémique"}'),
(250, 'Secondary Gain & Personal Ecology', 'Recadrage', 'Détecter les bénéfices cachés d''un symptôme ou d''un comportement.', '#D4622A', '{"Bénéfices secondaires"}', '{"Gain secondaire"}'),
(251, 'Finding Positive Intention', 'Recadrage', 'Identifier l''intention positive derrière un comportement gênant.', '#D4622A', '{"Intention","Recadrage"}', '{"Intention positive"}'),
(252, 'Behavior Appreciation', 'Recadrage', 'Reconnaître la valeur d''un comportement avant de le faire évoluer.', '#D4622A', '{"Recadrage"}', '{"Appréciation"}'),
(253, 'Meta Transformation', 'Recadrage', 'Transformation à un niveau supérieur (saut de niveau logique).', '#D4622A', '{"Identité","Transformation"}', '{"Méta"}'),
(254, 'Core Transformation', 'Recadrage', 'Aller au cœur du besoin profond derrière un comportement.', '#D4622A', '{"Identité","Transformation"}', '{"Core","Profond"}'),
(255, 'Apposition of Opposites', 'Recadrage', 'Tenir ensemble deux contraires apparemment incompatibles.', '#D4622A', '{"Intégration"}', '{"Contraires"}'),
(256, 'Choice Expansion', 'Recadrage', 'Multiplier les options disponibles dans une situation.', '#D4622A', '{"Choix","Flexibilité"}', '{"Options"}'),
(257, 'Undetermined State Integration', 'Recadrage', 'Intégrer le flou et l''incertitude comme état acceptable.', '#D4622A', '{"Incertitude","Lâcher-prise"}', '{"Flou"}'),
(258, 'Gentling', 'Recadrage', 'Cultiver la douceur envers soi-même.', '#D4622A', '{"Auto-compassion"}', '{"Douceur"}'),
(259, 'Forgiveness Pattern', 'Recadrage', 'Se pardonner et pardonner aux autres.', '#D4622A', '{"Pardon","Émotions"}', '{"Pardon"}'),
(260, 'Awakening to Freedom', 'Recadrage', 'Libération intérieure d''une contrainte ou d''un attachement.', '#D4622A', '{"Liberté","Identité"}', '{"Liberté"}'),

-- 7. Confiance, estime, identité (gold)
(280, 'Loving Yourself Pattern', 'Confiance & identité', 'Construire une estime de soi profonde et stable.', '#C8A030', '{"Estime de soi","Amour"}', '{"Estime"}'),
(281, 'Self-esteem Quick Fix', 'Confiance & identité', 'Boost express d''estime avant un événement à enjeu.', '#C8A030', '{"Estime de soi"}', '{"Express"}'),
(282, 'Assertiveness Installation', 'Confiance & identité', 'Installer la capacité à s''affirmer sereinement.', '#C8A030', '{"Affirmation"}', '{"Assertivité"}'),
(283, 'Criticism Analyzer', 'Confiance & identité', 'Trier les critiques utiles et les rejeter quand elles ne le sont pas.', '#C8A030', '{"Critique","Estime"}', '{"Critique"}'),
(284, 'Aligned Self', 'Confiance & identité', 'Soi aligné entre identité, valeurs et comportements.', '#C8A030', '{"Cohérence","Identité"}', '{"Alignement"}'),
(285, 'Inner Hero Pattern', 'Confiance & identité', 'Activer l''archétype du héros intérieur comme ressource.', '#C8A030', '{"Archétypes","Identité"}', '{"Héros"}'),
(286, 'Transformation Archetype Identification', 'Confiance & identité', 'Identifier l''archétype actif (Guerrier, Magicien, Sage, etc.).', '#C8A030', '{"Archétypes","Identité"}', '{"Archétypes"}'),
(287, 'Congruence', 'Confiance & identité', 'Cohérence entre mots, corps et actes.', '#C8A030', '{"Cohérence"}', '{"Congruence"}'),
(288, 'Boundaries Installation', 'Confiance & identité', 'Apprendre à poser ses limites avec clarté.', '#C8A030', '{"Limites"}', '{"Limites"}'),
(289, 'D.Y.P Pattern', 'Confiance & identité', 'Do Your Part — assumer sa part de responsabilité dans un système.', '#C8A030', '{"Responsabilité"}', '{"Responsabilité"}'),
(290, 'The FIB Pattern', 'Confiance & identité', 'Gestion du rapport à l''honnêteté et au mensonge.', '#C8A030', '{"Éthique","Identité"}', '{"Éthique"}'),
(291, 'Wholeness Pattern', 'Confiance & identité', 'Sentiment d''unité et d''intégrité personnelle.', '#C8A030', '{"Identité","Intégration"}', '{"Unité"}'),
(292, 'Abandoned Predisposition', 'Confiance & identité', 'Retrouver une disposition naturelle perdue ou refoulée.', '#C8A030', '{"Identité"}', '{"Disposition"}'),
(293, 'Relationship Clarifying Pattern', 'Confiance & identité', 'Clarifier la nature et les enjeux d''une relation.', '#C8A030', '{"Relations"}', '{"Relations"}'),
(294, 'Falling In-Love Pattern', 'Confiance & identité', 'Modéliser les mécanismes d''attachement et de passion.', '#C8A030', '{"Relations","Émotions"}', '{"Attachement"}'),

-- 8. Parts internes, conflits (purple)
(310, 'Parts Negotiation', 'Parts internes', 'Négocier entre parts internes en conflit.', '#7C5CBF', '{"Conflits internes"}', '{"Négociation"}'),
(311, 'Resolving Internal Conflicts', 'Parts internes', 'Résolution globale d''un conflit interne complexe.', '#7C5CBF', '{"Conflits internes"}', '{"Résolution"}'),
(312, 'Basic Inner Conflict Integration', 'Parts internes', 'Intégration basique de deux parts opposées.', '#7C5CBF', '{"Intégration"}', '{"Intégration"}'),
(313, 'Advanced Visual Squash', 'Parts internes', 'Fusion avancée de deux parts en un nouveau soi intégré.', '#7C5CBF', '{"Intégration","Identité"}', '{"Visual squash"}'),
(314, 'Dis-Identification', 'Parts internes', 'Se désidentifier d''une part ou d''un état pour reprendre du recul.', '#7C5CBF', '{"Identité","Recul"}', '{"Désidentification"}'),
(315, 'Making Peace With Your Parents', 'Parts internes', 'Apaiser le rapport intérieur aux figures parentales.', '#7C5CBF', '{"Famille","Pardon"}', '{"Parents"}'),
(316, 'Co-Dependency Resolution', 'Parts internes', 'Sortir d''une relation codépendante.', '#7C5CBF', '{"Relations","Limites"}', '{"Codépendance"}'),
(317, 'Conflict Resolution', 'Parts internes', 'Résolution interpersonnelle d''un conflit avec autrui.', '#7C5CBF', '{"Relations","Conflits"}', '{"Conflit"}'),
(318, 'Frame of Agreement', 'Parts internes', 'Cadre commun de négociation et d''accord.', '#7C5CBF', '{"Négociation"}', '{"Cadre"}'),

-- 9. Apprentissage, modélisation, stratégies (blue)
(340, 'Basic 2nd Position Modeling', 'Apprentissage & modélisation', 'Se mettre dans la peau de quelqu''un pour modéliser son fonctionnement.', '#5B8FB9', '{"Modélisation"}', '{"2ème position"}'),
(341, '2nd Position Intuitive Modeling', 'Apprentissage & modélisation', 'Modélisation intuitive en 2ème position.', '#5B8FB9', '{"Modélisation"}', '{"Intuitif"}'),
(342, 'Basic 3rd Position Modeling', 'Apprentissage & modélisation', 'Modélisation depuis la position d''observateur.', '#5B8FB9', '{"Modélisation"}', '{"3ème position"}'),
(343, 'Basic States Of Excellence Modeling', 'Apprentissage & modélisation', 'Modéliser l''état peak d''un expert.', '#5B8FB9', '{"Modélisation","Performance"}', '{"Excellence"}'),
(344, 'New Behavior Generator', 'Apprentissage & modélisation', 'Générer un nouveau comportement par projection mentale.', '#5B8FB9', '{"Comportement","Apprentissage"}', '{"Générateur"}'),
(345, 'New Language Rapid Learning', 'Apprentissage & modélisation', 'Apprentissage rapide d''une langue.', '#5B8FB9', '{"Apprentissage","Langue"}', '{"Langues"}'),
(346, 'Rhythmic Learning', 'Apprentissage & modélisation', 'Apprentissage par rythme et séquences.', '#5B8FB9', '{"Apprentissage"}', '{"Rythme"}'),
(347, 'Accelerated Learning Chain', 'Apprentissage & modélisation', 'Chaîne d''apprentissage accélérée.', '#5B8FB9', '{"Apprentissage"}', '{"Accéléré"}'),
(348, 'Elicitation of Learning Strategies', 'Apprentissage & modélisation', 'Élicitation de la stratégie d''apprentissage personnelle.', '#5B8FB9', '{"Apprentissage","Stratégies"}', '{"Élicitation"}'),
(349, 'Spelling Strategy', 'Apprentissage & modélisation', 'Stratégie visuelle d''orthographe et de mémorisation.', '#5B8FB9', '{"Apprentissage","Mémoire"}', '{"Orthographe"}'),
(350, 'Walt Disney Strategy', 'Apprentissage & modélisation', 'Rêveur — Réaliste — Critique : trois positions pour tout projet.', '#5B8FB9', '{"Stratégies","Créativité"}', '{"Disney"}'),
(351, 'Active Dreaming', 'Apprentissage & modélisation', 'Rêve éveillé dirigé pour explorer un sujet.', '#5B8FB9', '{"Visualisation","Créativité"}', '{"Rêve éveillé"}'),
(352, 'Future Now', 'Apprentissage & modélisation', 'Se projeter au futur déjà réalisé.', '#5B8FB9', '{"Visualisation","Goal-setting"}', '{"Projection"}'),
(353, 'Matrixing', 'Apprentissage & modélisation', 'Cartographier mentalement un système complexe.', '#5B8FB9', '{"Stratégies","Systémique"}', '{"Mapping"}'),
(354, 'Deconstructing into Modalities', 'Apprentissage & modélisation', 'Décomposer une expérience en V/A/K/O/G.', '#5B8FB9', '{"Modélisation","Sous-modalités"}', '{"VAK"}'),
(355, 'Reconstructing into Values', 'Apprentissage & modélisation', 'Reconstruire une motivation à partir des valeurs identifiées.', '#5B8FB9', '{"Valeurs","Motivation"}', '{"Reconstruction"}'),
(356, 'Vision Communication Protocol', 'Apprentissage & modélisation', 'Communiquer efficacement une vision.', '#5B8FB9', '{"Leadership","Communication"}', '{"Vision"}'),
(357, 'Communicating from Vision Down', 'Apprentissage & modélisation', 'Décliner une vision top-down jusqu''aux actions concrètes.', '#5B8FB9', '{"Leadership","Stratégies"}', '{"Top-down"}'),
(358, 'Problem Definition', 'Apprentissage & modélisation', 'Bien poser le problème avant de chercher la solution.', '#5B8FB9', '{"Résolution","Stratégies"}', '{"Définition"}'),
(359, 'Problem Solving Strategy I', 'Apprentissage & modélisation', 'Stratégie simple de résolution de problème.', '#5B8FB9', '{"Résolution"}', '{"Résolution"}'),
(360, 'Problem Solving Strategy II', 'Apprentissage & modélisation', 'Stratégie avancée de résolution de problème.', '#5B8FB9', '{"Résolution"}', '{"Résolution avancée"}'),
(361, 'Persuasion By Chunking Up/Down', 'Apprentissage & modélisation', 'Monter ou descendre dans le niveau d''abstraction pour persuader.', '#5B8FB9', '{"Influence","Communication"}', '{"Chunking"}'),
(362, 'Mapping Anyone''s Brain', 'Apprentissage & modélisation', 'Cartographier le fonctionnement cognitif d''une personne.', '#5B8FB9', '{"Profilage","Modélisation"}', '{"Mapping mental"}'),
(363, 'Dipole', 'Apprentissage & modélisation', 'Tenir deux pôles en tension productive.', '#5B8FB9', '{"Stratégies"}', '{"Polarité"}'),

-- 10. Alignement identitaire & transitions (navy)
(390, 'Applying Logical Levels', 'Alignement & transitions', 'Diagnostiquer via Environnement-Comportement-Capacité-Croyances-Identité-Mission.', '#1A2238', '{"Identité","Diagnostic"}', '{"Niveaux logiques"}'),
(391, 'Logical Levels Co-Alignment', 'Alignement & transitions', 'Aligner tous les niveaux logiques entre eux.', '#1A2238', '{"Cohérence","Identité"}', '{"Alignement"}'),
(392, 'SCORE Pattern', 'Alignement & transitions', 'Symptom — Cause — Outcome — Resource — Effect : grille universelle de coaching.', '#1A2238', '{"Coaching","Diagnostic"}', '{"SCORE"}'),
(393, 'Dancing SCORE Pattern', 'Alignement & transitions', 'Version kinesthésique du SCORE, en mouvement.', '#1A2238', '{"Coaching","Corps"}', '{"SCORE","Kinesthésique"}'),
(394, 'Life Transitions Tracking', 'Alignement & transitions', 'Suivre et accompagner les transitions de vie.', '#1A2238', '{"Transitions"}', '{"Transitions"}'),
(395, 'Longevity Pattern', 'Alignement & transitions', 'Inscrire un projet ou une posture dans la durée.', '#1A2238', '{"Identité","Durée"}', '{"Longévité"}'),
(396, 'Change Personal History', 'Alignement & transitions', 'Réécrire son histoire personnelle pour libérer le présent.', '#1A2238', '{"Histoire","Trauma"}', '{"Histoire"}'),
(397, 'Autobiography Pattern', 'Alignement & transitions', 'Structurer le récit de sa vie de façon cohérente.', '#1A2238', '{"Récit","Identité"}', '{"Autobiographie"}'),
(398, 'Exploring Causes & Effects', 'Alignement & transitions', 'Tracer les liens de cause à effet d''une situation.', '#1A2238', '{"Diagnostic"}', '{"Causalité"}'),
(399, 'Grief Pattern', 'Alignement & transitions', 'Accompagner le processus de deuil.', '#1A2238', '{"Deuil"}', '{"Deuil"}'),
(400, 'Pre-Grieving Pattern', 'Alignement & transitions', 'Anticiper et préparer un deuil prévisible.', '#1A2238', '{"Deuil","Anticipation"}', '{"Anticipation"}'),
(401, 'Self-Nurturing', 'Alignement & transitions', 'Prendre soin de soi au quotidien.', '#1A2238', '{"Auto-soin"}', '{"Self-care"}'),
(402, 'Inner Peace Questionnaire', 'Alignement & transitions', 'Auto-évaluer régulièrement sa paix intérieure.', '#1A2238', '{"Conscience","Bien-être"}', '{"Questionnaire"}'),
(403, 'Essence Leading', 'Alignement & transitions', 'Leadership par l''essence plutôt que par l''ordre.', '#1A2238', '{"Leadership","Identité"}', '{"Essence"}'),
(404, 'Somatic Leading', 'Alignement & transitions', 'Leadership par la présence corporelle.', '#1A2238', '{"Leadership","Corps"}', '{"Somatique"}'),
(405, 'Somatic Awareness Enhancement', 'Alignement & transitions', 'Développer la conscience corporelle et la proprioception.', '#1A2238', '{"Corps","Conscience"}', '{"Proprioception"}'),
(406, 'Symbolic Somatic Priming', 'Alignement & transitions', 'Amorçage symbolique par un geste rituel d''entrée en activité.', '#1A2238', '{"Rituels","Corps"}', '{"Amorçage"}'),

-- 11. Langage, hypnose, influence (purple)
(430, 'Meta-Model', 'Langage & hypnose', 'Ensemble des questions pour clarifier le langage et le réel sous-jacent.', '#7C5CBF', '{"Langage","Précision"}', '{"Méta-Modèle"}'),
(431, 'Meta-Model Challenging', 'Langage & hypnose', 'Interroger les affirmations vagues, généralisantes ou déformées.', '#7C5CBF', '{"Langage"}', '{"Challenge"}'),
(432, 'Meta-Model Intentional Usage', 'Langage & hypnose', 'Usage volontaire du Méta-Modèle pour la précision en discours.', '#7C5CBF', '{"Langage","Communication"}', '{"Précision"}'),
(433, 'De-Nominalizing', 'Langage & hypnose', 'Re-verber un nom figé pour rendre l''action modifiable.', '#7C5CBF', '{"Langage"}', '{"Dénominalisation"}'),
(434, 'Milton-Model', 'Langage & hypnose', 'Modèle de langage hypnotique conversationnel d''Erickson.', '#7C5CBF', '{"Hypnose","Langage"}', '{"Milton","Hypnose"}'),
(435, 'Intonation', 'Langage & hypnose', 'Travailler la voix et ses variations pour induire et marquer.', '#7C5CBF', '{"Voix","Hypnose"}', '{"Intonation"}'),
(436, 'Embedded Command I', 'Langage & hypnose', 'Commandes implantées basiques dans un discours apparemment anodin.', '#7C5CBF', '{"Hypnose","Influence"}', '{"Commande implantée"}'),
(437, 'Embedded Command II', 'Langage & hypnose', 'Version avancée des commandes implantées multi-couches.', '#7C5CBF', '{"Hypnose","Influence"}', '{"Avancé"}'),
(438, 'Embedded Command In A Question', 'Langage & hypnose', 'Commande implantée formulée sous forme de question.', '#7C5CBF', '{"Hypnose"}', '{"Question"}'),
(439, 'Analogical Marking', 'Langage & hypnose', 'Marquage analogique des suggestions par ton, geste ou pause.', '#7C5CBF', '{"Hypnose"}', '{"Marquage"}'),
(440, 'Classic Confusion Method', 'Langage & hypnose', 'Induire la confusion pour ouvrir une fenêtre suggestive.', '#7C5CBF', '{"Hypnose"}', '{"Confusion"}'),
(441, 'Law of Reversed Effect', 'Langage & hypnose', 'Tenir compte de l''effet inverse des injonctions négatives.', '#7C5CBF', '{"Langage","Influence"}', '{"Effet inverse"}'),
(442, 'Nested Loops', 'Langage & hypnose', 'Histoires imbriquées pour transporter des suggestions.', '#7C5CBF', '{"Hypnose","Métaphore"}', '{"Boucles imbriquées"}'),
(443, 'Double Bind', 'Langage & hypnose', 'Choix illusoire qui conduit dans tous les cas au résultat désiré.', '#7C5CBF', '{"Influence","Hypnose"}', '{"Double bind"}'),
(444, 'Ambiguity Method', 'Langage & hypnose', 'Utiliser l''ambiguïté pour ouvrir l''interprétation.', '#7C5CBF', '{"Hypnose"}', '{"Ambiguïté"}'),
(445, 'Presupposition Method', 'Langage & hypnose', 'Présupposer l''état désiré dans la formulation.', '#7C5CBF', '{"Langage","Influence"}', '{"Présupposition"}'),
(446, 'Metaphor Method', 'Langage & hypnose', 'Construire et délivrer un récit métaphorique.', '#7C5CBF', '{"Métaphore","Hypnose"}', '{"Métaphore"}'),
(447, 'Shared Resource', 'Langage & hypnose', 'Co-activer une ressource entre soi et le client.', '#7C5CBF', '{"Rapport","Ressources"}', '{"Co-activation"}'),
(448, 'Generative Relational Priming', 'Langage & hypnose', 'Amorçage relationnel pour installer une tonalité.', '#7C5CBF', '{"Relation","Amorçage"}', '{"Priming"}'),
(449, 'Recognition Expression', 'Langage & hypnose', 'Exprimer la reconnaissance comme posture relationnelle.', '#7C5CBF', '{"Relation"}', '{"Reconnaissance"}'),
(450, 'TDS Manipulation', 'Langage & hypnose', 'Time-Duration-Sequence : jouer sur la temporalité du discours.', '#7C5CBF', '{"Langage","Temporalité"}', '{"Temps","Séquence"}'),
(451, 'Avoiding Counter-Productive Suggestions', 'Langage & hypnose', 'Éviter les injonctions négatives qui produisent l''inverse.', '#7C5CBF', '{"Langage"}', '{"Vigilance"}'),

-- 12. Meta-Programs & Sub-modalities (teal)
(470, 'Meta-Programs Identification', 'Meta-Programs', 'Identifier les filtres cognitifs (Toward/Away, Internal/External, etc.).', '#2E8A7B', '{"Profilage","Cognition"}', '{"Méta-Programmes"}'),
(471, 'Limiting Meta-Programs Challenging', 'Meta-Programs', 'Contester les filtres cognitifs limitants chez le client.', '#2E8A7B', '{"Profilage","Cognition"}', '{"Challenge"}'),
(472, 'Meta-Programs Change Pattern', 'Meta-Programs', 'Faire évoluer un filtre cognitif (ex. Options → Procedures).', '#2E8A7B', '{"Cognition","Flexibilité"}', '{"Changement"}'),
(473, 'Auditory Rep System Development', 'Meta-Programs', 'Développer le canal auditif comme système de représentation.', '#2E8A7B', '{"Sensoriel"}', '{"Auditif"}'),
(474, 'Visual Rep System Development', 'Meta-Programs', 'Développer le canal visuel comme système de représentation.', '#2E8A7B', '{"Sensoriel"}', '{"Visuel"}'),
(475, 'Reprocessing', 'Meta-Programs', 'Retraitement des mémoires (think physiology, time line, active ingredients).', '#2E8A7B', '{"Trauma","Mémoire"}', '{"Reprocessing"}');
